export default {
    setup: {
        new_form_id: 'new-budget-line',
        info_form_id: 'budget-line-info',
        title: "Budget Line",
        layout_columns: 3,
        model: "Budget_Line",
        allow_submit: true,
        allow_councel: false,
        allow_print: false,
        allow_delete: false,
    },
    fields: [
        {
            id: "name",
            fieldlabel: "Budget Line Name",
            fieldname: "name",
            fieldtype: "text",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "description",
            fieldlabel: "Description",
            fieldname: "description",
            fieldtype: "rich",
            columns: 3,
            required: false,
            hidden: false,
            height: 300,
        },
    ],
}