export default {
    setup: {
        new_form_id: 'new-cs-seasonal-employment',
        info_form_id: 'cs-seasonal-employment-info',
        title: "Certificate of Service",
        layout_columns: 5,
        allow_print: true,
        model: "CS_Seasonal_Employment",
        allow_submit: true,
        allow_cancel: true,
        allow_delete: false,
        allow_print: true,
        allow_preview: true,
        allow_download: true,
        allow_sending_mail: false,
    },        
    fields: [
        {
            id: "employee_id",
            fieldlabel: "Employee No",
            fieldname: "employee_id",
            fieldtype: "link",
            model: "Employee",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },    
        {
            id: "employee_name",
            fieldlabel: "Employee Name",
            fieldname: "employee_name",
            fieldtype: "text",
            columns: 1,
            // placeholder: "Enter Employee Full Name",
            required: true,
            hidden: false,
            fetchfrom: "employee_id",
            fetchfield: "full_name",
        },    
        {
            id: "nrc",
            fieldlabel: "National Registration Card Number",
            fieldname: "nrc",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            fetchfrom: "employee_id",
            fetchfield: "nrc"
        },    
        {
            id: "employed-by-the-examinations-council-of-zambia-as",
            fieldlabel: "Job Title",
            fieldname: "designation",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
            fetchfrom: "employee_id",
            fetchfield: "nrc"
        },   
        {
            id: "napsa-membership-number",
            fieldlabel: "NAPSA Membership Number",
            fieldname: "napsa_membership_number",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },    
        {
            id: "employers-napsa-account-number",
            fieldlabel: "Employer's NAPSA  A/C No",
            fieldname: "employee_napsa_account_number",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },     
        // {
        //     id: "section-break-001",
        //     fieldlabel: "",
        //     fieldtype: "section-break"

        // },
        {
            id: "designation",
            fieldlabel: "Job Title",
            fieldname: "designation",
            fieldtype: "link",
            model: "Designation",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee_id",
            fetchfield: "designation"
        },  
        {
            id: "from-date",
            fieldlabel: "From Date",
            fieldname: "from_date",
            fieldtype: "date",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },    
        {
            id: "to-date",
            fieldlabel: "To Date",
            fieldname: "to_date",
            fieldtype: "date",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },    
        {
            id: "name-of-employer",
            fieldlabel: "Name of Employer",
            fieldname: "company",
            fieldtype: "link",
            model: "Company",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            default: lite?.user?.company?.name 
        },    
        {
            id: "Address of Employer",
            fieldlabel: "Address of Employer",
            fieldname: "address_of_employer",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            default: lite?.user?.company?.physical_address,
        },    
    ],
}