
export default {
    setup: {
        new_form_id: 'new-certificate-of-service',
        info_form_id: 'certificate-of-service-info',
        title: "Certificate of Service",
        layout_columns: 5,
        model: "Certificate_Of_Service",
        allow_submit: true,
        allow_cancel: true,
        allow_delete: false,
        allow_print: true,
        allow_preview: true,
        allow_download: true,
        allow_sending_mail: false,
    },
    fields: [
        {
            id: "employee_id",
            fieldlabel: "Employee No",
            fieldname: "employee_id",
            fieldtype: "link",
            model: "Employee",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },    
        {
            id: "nrc",
            fieldlabel: "National Registration Card",
            fieldname: "nrc",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee_id",
            fetchfield: "nrc"
        },    
        {
            id: "column-break-001",
            fieldtype: "column-break",
            columns: 1,
        },
        {
            id: "employee_full_name",
            fieldlabel: "Employee Name",
            fieldname: "employee_name",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee_id",
            fetchfield: "full_name"
        },    
        {
            id: "napsa-membership-number",
            fieldlabel: "NAPSA Membership Number",
            fieldname: "napsa_membership_number",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },    
        {
            id: "employer-napsa-account-no",
            fieldlabel: "Employer's NAPSA  A/C No",
            fieldname: "employer_napsa_account_no",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },    
        {
            id: "section-break",
            fieldlabel: "TOTAL CONTRIBUTIONS PAID",
            fieldname: "",
            fieldtype: "section-break",
            columns: 1,
        },    
        {
            id: "pror-year-statutory",
            fieldlabel: "Prior Years (Statutory)",
            fieldname: "prior_year_statutory",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },    
        {
            id: "prior-year-Savings",
            fieldlabel: "Prior Years (Savings)",
            fieldname: "prior_year_savings",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },    
        // {
        //     id: "column-break-002",
        //     fieldtype: "column-break",
        //     columns: 1,
        // },
        {
            id: "current-year-statutory",
            fieldlabel: "Current Year (Statutory)",
            fieldname: "current_year_statutory",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },    
        {
            id: "current-year-savings",
            fieldlabel: "Current Year (Savings)",
            fieldname: "current_year_savings",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },    
        {
            id: "section-break",
            fieldlabel: "Employment Details",
            fieldname: "",
            fieldtype: "section-break",
            columns: 1,
        },
        {
            id: "from_date",
            fieldlabel: "From",
            fieldname: "from_date",
            fieldtype: "date",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },    
        {
            id: "to_date",
            fieldlabel: "To",
            fieldname: "to_date",
            fieldtype: "date",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },    
        {
            id: "name-of-employer",
            fieldlabel: "Name of Employer",
            fieldname: "company",
            fieldtype: "link",
            model: "Company",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            default: lite?.user?.company?.name
        },    
        {
            id: "address-of-employer",
            fieldlabel: "Address of Employer",
            fieldname: "address_of_employer",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            default: lite?.user?.company?.physical_address,
            fetchfrom: "name-of-employer",
            fetchfield: "physical_address",
        },    
        {
            id: "submition-date",
            fieldlabel: "Date",
            fieldname: "submition_date",
            fieldtype: "date",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },      
    ],
}