export default {
    setup: {
        model: "Designation",
        new_form_id: 'new-designation',
        info_form_id: 'designation-info',
        title: "Designation",
        layout_columns: 4,
    },
    fields: [
        {
            id: "designation",
            fieldlabel: "Job Title",
            fieldname: "name",
            fieldtype: "text",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,
        },{
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "link",
            model: "Department",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "skill",
            fieldlabel: "Skills",
            fieldname: "skill",
            fieldtype: "table",
            model: "Job_Skill",
            required: false,
            hidden: false,
            columns: 2,
            fields: [
                {
                    id: "skill",
                    fieldlabel: "Skills",
                    fieldname: "skills",
                    fieldtype: "link",
                    model: "Skills",
                    filters: {
                        skill_qualification: "Skill"
                    },
                    columns: 10,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "must_have",
                    fieldlabel: "Must Have",
                    fieldname: "must_have",
                    fieldtype: "check",
                    columns: 3,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
            ]
        },
        {
            id: "qualification",
            fieldlabel: "Qualifications",
            fieldname: "qualification",
            fieldtype: "table",
            model: "Job_Qualification",
            required: false,
            hidden: false,
            columns: 2,
            fields: [
                {
                    id: "qualification",
                    fieldlabel: "Qualification",
                    fieldname: "qualification",
                    fieldtype: "link",
                    model: "Skills",
                    filters: {
                        skill_qualification: "Qualification"
                    },
                    columns: 10,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "must_have",
                    fieldlabel: "Must Have",
                    fieldname: "must_have",
                    fieldtype: "check",
                    columns: 2,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "is_added_advantage",
                    fieldlabel: "Is Added Advantage",
                    fieldname: "is_added_advantage",
                    fieldtype: "check",
                    columns: 3,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
            ]
        },
        {
            id: "competess_assessment",
            fieldlabel: "Competence Assessment",
            fieldname: "competess_assessment",
            fieldtype: "table",
            model: "Competess_Assessment",
            required: false,
            hidden: false,
            columns: 2,
            fields: [
                {
                    id: "competess_assessment",
                    fieldlabel: "Competence Assessment",
                    fieldname: "competess",
                    fieldtype: "text",
                    columns: 10,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "has_competess",
                    fieldlabel: "Has",
                    fieldname: "has_competess",
                    fieldtype: "check",
                    columns: 3,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
            ]
        },
        {
            id: "practical_skill",
            fieldlabel: "Practical Assessment",
            fieldname: "practical_assessment",
            fieldtype: "table",
            model: "Practical_Assessment",
            required: false,
            hidden: false,
            columns: 2,
            fields: [
                {
                    id: "practical_skill",
                    fieldlabel: "Practical Skill",
                    fieldname: "practical_skill",
                    fieldtype: "text",
                    columns: 10,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "has_practical_skill",
                    fieldlabel: "Has",
                    fieldname: "has_practical_skill",
                    fieldtype: "check",
                    columns: 2,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
            ]
        },
        {
            id: "description",
            fieldlabel: "Description",
            fieldname: "description",
            fieldtype: "rich",
            height: 300,
            columns: 4,
            placeholder: " ",
            required: false,
            hidden: false,
            description: ""
        },  

    ]
}
