export default {
    setup: {
        new_form_id: 'new-employee-files',
        info_form_id: 'employee-files-info',
        title: "Employee File",
        layout_columns: 4,
        allow_submit: true,
        allow_cancel: false,
        allow_delete: true,
        allow_print: false,
        allow_sending_mail: false,
        model: "Employee_File"
    },
    fields: [
        {
            id: "employee",
            fieldlabel: "Employee No",
            fieldname: "employee",
            fieldtype: "link",
            model: "Employee",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            filters: {
                status: "Active",
            }, 
        },
        {
            id: "employee-name",
            fieldlabel: "Employee Name",
            fieldname: "employee_name",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom:"employee",
            fetchfield: "full_name"
        },
       
  
        {
            id: "company",
            fieldlabel: "Council",
            fieldname: "company",
            fieldtype: "link",
            model: "Company",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
            fetchfrom:"employee",
            fetchfield: "company",
            default: lite.user.company.name
        },
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom:"employee",
            fetchfield: "department"
        },
        {
            id: "designation",
            fieldlabel: "Job Title",
            fieldname: "designation",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom:"employee",
            fetchfield: "designation"
        },
       {
            id: "sec",
            fieldlabel: "Files",
            fieldname: "sec",
            fieldtype: "section-break",
            addborder: true,
            columns: 1,
            hidden: false,
        },
        {
            id: "file",
            fieldlabel: "Files/Attachments",
            fieldname: "file_content",
            fieldtype: "table",
            columns: 4,
            required: false,
            hidden: false,
            model: "File",
            fields: [
                {
                    id: "file_name",
                    fieldlabel: "File Name",
                    fieldname: "file_name",
                    fieldtype: "text",
                    columns: 4,
                    placeholder: " ",
                    required: true,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "attachment",
                    fieldlabel: "Attachment",
                    fieldname: "attachment",
                    fieldtype: "file",
                    columns: 8,
                    placeholder: " ",
                    required: true,
                    hidden: false,
                    istablefield: true,
                },
            ]
        },
    ],
}