
import { do_exit_interview} from "../../overrides/form/hr/core.js"

export default {
    setup: {
        new_form_id: 'new-employee-seperation',
        info_form_id: 'employee-seperation-info',
        title: "Employee Separation",
        layout_columns: 3,
       model: "Employee_Seperation",
        allow_submit: true,
        allow_cancel: true,
        allow_delete: false,
        allow_print: false,
        allow_sending_mail: false,
    },
    form_actions: [
        {
            title: "Do An Exit Interview",
            icon: "content_copy",
            icon_color: "indigo",
            action: do_exit_interview,
            for_docstatus: [1],
            at_index: 1,
        },
    ],
    fields: [
        {
            id: "separation_type",
            fieldlabel: "Type of Separation",
            fieldname: "separation_type",
            fieldtype: "select",
            options: [
                "Termination of Contract",
                "Resignation",
                "End of Contract",
                "Retirement",
                "Redundancy",
                "Abolition of Office",
                "Health Discharge",
                "Mutual Separation",
                "End of Seasonal Employment",
                "End of Fixed Contract",
                "Death of Employee",
                "Surrender of Recall of Seconded Employee",
                "Unsatisfactory Performance",
            ],
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            default: "End of Contract",
        },    
    
        {
            id: "retirement-type",
            fieldlabel: "Retirement Type",
            fieldname: "retirement_type",
            fieldtype: "select",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            displayon: ["separation_type", "Retirement"],
            options:["Early", "Normal", "Late"],
        },
        {
            id: "employee",
            fieldlabel: "Employee No",
            fieldname: "employee",
            fieldtype: "link",
            model: "Employee",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            filters: {
                status: "Active",
            }, 
        },
    
        {
            id: "employee_name",
            fieldlabel: "Employee Name",
            fieldname: "employee_name",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom:"employee",
            fetchfield: "full_name",
            
        },
     
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom:"employee",
            fetchfield: "department"
        },
        {
            id: "designation",
            fieldlabel: "Job Title",
            fieldname: "designation",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom:"employee",
            fetchfield: "designation"
        },
        {
            id: "reports_to",
            fieldlabel: "Reports To",
            fieldname: "reports_to",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom:"employee",
            fetchfield: "report_to"
        },
        {
            id: "resignation_date",
            fieldlabel: "Submission Date",
            fieldname: "resignation_date",
            fieldtype: "date",
            columns: 1,
            required: true,
            hidden: false,
            default: lite.utils.today()
        },
        {
            id: "last_day_of_work",
            fieldlabel: "Last Day of Work",
            fieldname: "last_day_of_work",
            fieldtype: "date",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            default: lite.utils.add_days (lite.utils.today(), 30)
        },
        {
            id: "notice_period",
            fieldlabel: "Notice Period of last days of work",
            fieldname: "notice_period",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            default: 30,
        },
        {
            id: "skip_exit_interview",
            fieldlabel: "Skip Exit Interview",
            fieldname: "skip_exit_interview",
            fieldtype: "check",
            columns: 1,
            required: false,
            hidden: false,
        },
        {
            id: "skip_final_statement",
            fieldlabel: "Skip Final Statement",
            fieldname: "skip_final_statement",
            fieldtype: "check",
            columns: 1,
            addborder: true,
            required: false,
            hidden: false,
        },
        {
            id: "sec",
            fieldlabel: "",
            fieldname: "sec",
            fieldtype: "section-break",
            columns: 1,
            addborder: true,
            required: false,
            hidden: false,
        },
        {
            id: "reason",
            fieldlabel: "Reason",
            fieldname: "reason",
            fieldtype: "rich",
            height: 300,
            columns: 3,
            placeholder: " ",
            required: false,
            hidden: false,
        },
       
      
    ],
}