import { } from "../../overrides/form/hr/core.js"
export default {
    setup: {
        new_form_id: 'new-exit-interview_questionnair',
        info_form_id: 'exit-interview-questionnair-info',
        title: "Exit Interview",
        layout_columns: 3,
        model: "Exit_Interview_Questionnair",
        allow_submit: false,
        allow_cancel: true,
        allow_delete: false,
        allow_print: false,
        allow_sending_mail: false,
    },
    form_actions: [
        // {
        //     title: "Generate Final Statement",
        //     icon: "content_copy",
        //     icon_color: "indigo",
        //     action: generate_final_statement,
        //     for_docstatus: [1],
        //     at_index: 1,
        // },
    
    ],
    fields: [
        {
            id: "employee-email",
            fieldlabel: "Employee Email",
            fieldname: "email",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
            fetchfrom:"employee",
            fetchfield: "email",
            
        },
        {
            id: "date-of-joining",
            fieldlabel: "Date of Joining",
            fieldname: "date_of_joining",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
            fetchfrom:"employee",
            fetchfield: "date_of_joining",
            
        },
        {
            id: "designation",
            fieldlabel: "Job Title",
            fieldname: "designation",
            fieldtype: "link",
            model: "Designation",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfield: "designation"
        },
        {
            id: "designation-name",
            fieldlabel: "designation Name",
            fieldname: "name",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
            fetchfrom:"designation",
            fetchfield: "designation",
            
        },
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "link",
            model: "Department",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom:"employee",
            fetchfield: "department"
        },
        {
            id: "company",
            fieldlabel: "Council",
            fieldname: "company",
            fieldtype: "link",
            model: "Company",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
            fetchfrom:"employee",
            fetchfield: "company",
            default:lite.user.company.name
        },
        {
            id: "sec",
            fieldlabel: "Interview Questionnaire",
            fieldname: "sec",
            fieldtype: "section-break",
            columns: 1,
            addborder: true,
            required: false,
            hidden: false,
        },
        {
            id: "questions",
            fieldlabel: "Questions",
            fieldname: "questions",
            model: "Questions",
            fieldtype: "table",
            required: false,
            hidden: false,
            fields: [
                {
                    id: "question",
                    fieldlabel: "Question",
                    fieldname: "question",
                    fieldtype: "text",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                    filters: {
                        status: "Active",
                    }, 
                }, 
                {
                    id: "answer",
                    fieldlabel: "Answer",
                    fieldname: "answer",
                    fieldtype: "text",
                    columns: 2,
                    placeholder: " ",
                    required: false,
                    hidden: true,
                    istablefield: true,
                    filters: {
                        status: "Active",
                    }, 
                },   
            ] 
        },
        {
            id: "sec",
            fieldlabel: "",
            fieldname: "sec",
            fieldtype: "section-break",
            columns: 1,
            addborder: true,
            required: false,
            hidden: false,
        },
        {
            id: "interview-summary",
            fieldlabel: "Exit Interview Summary",
            fieldname: "interview_summary",
            fieldtype: "rich",
            height: 300,
            columns: 3,
            placeholder: " ",
            required: false,
            hidden: true,
        },
       
      
    ],
}