export default {
    setup: {
        new_form_id: 'new-gratuity',
        info_form_id: 'gratuity-info',
        title: "Gratuity",
        layout_columns: 3,
        model: "Graduate",
        allow_submit: true,
        allow_cancel: true,
        allow_delete: false,
        allow_print: false,
        allow_sending_mail: false,
    },
    fields: [
        {
            id: "name",
            fieldlabel: "Name",
            fieldname: "name",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
        },
        {
            id: "employee",
            fieldlabel:  "Employee No",
            fieldname: "employee",
            fieldtype: "link",
            model: "Employee",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "employee_name",
            fieldlabel: "Employee Name",
            fieldname: "employee_name",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "full_name",
        },
        {
            id: "basic_salary",
            fieldlabel: "Basic Salary",
            fieldname: "basic_salary",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "basic_pay",
        },
        {
            id: "contract",
            fieldlabel: "Contract",
            fieldname: "contract",
            fieldtype: "link",
            model: "Hr_Contract",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "contract-type",
            fieldlabel: "Contract Type",
            fieldname: "contract_type",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            fetchfrom: "contract",
            fetchfield: "contract_type",
        },
        {
            id: "effective_date",
            fieldlabel: "Contract Effective Date",
            fieldname: "effective_date",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            fetchfrom: "contract",
            fetchfield: "effective_date",
        },
        {
            id: "expiry_contract_date",
            fieldlabel: "Contract Expiry Date",
            fieldname: "expiry_contract_date",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            fetchfrom: "contract",
            fetchfield: "end_date",
        },
        {
            id: "gratuity_amount",
            fieldlabel: "Gratuity Amount",
            fieldname: "gratuity_amount",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "company",
            fieldlabel: "Council",
            fieldname: "company",
            fieldtype: "read-only",
            columns: 2,
            required: true,
            hidden: true,
            placeholder: " ",
            default: lite.user.company.name,
        },
    ],
}