export default {
    setup: {
        new_form_id: 'new-hr-budget',
        info_form_id: 'hr-budget-info',
        title: "Budget",
        layout_columns: 3,
        model: "HR_Budget",
        allow_submit: true,
        allow_cancel: true,
        allow_delete: false,
        allow_print: false,
        allow_sending_mail: false,
    },
    fields: [
        {
            id: "from_date",
            fieldlabel: "From Date",
            fieldname: "from_date",
            fieldtype: "date",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "to_date",
            fieldlabel: "To Date",
            fieldname: "to_date",
            fieldtype: "date",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "total_funds",
            fieldlabel: "Total Funds",
            fieldname: "total_funds",
            fieldtype: "float",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "budget_lines",
            fieldlabel: "Budget Lines",
            fieldname: "budget_lines",
            fieldtype: "table",
            required: true,
            columns: 4,
            hidden: false,
            model: "HR_Budget_Lines",
            fields: [
                {
                    id: "budget_line",
                    fieldlabel: "Budget Line",
                    fieldname: "budget_line",
                    fieldtype: "link",
                    model: "Budget_Line",
                    columns: 2,
                    placeholder: " ",
                    required: true,
                    hidden: false,
                },
                {
                    id: "budget_line_expense",
                    fieldlabel: "Allocated Amount",
                    fieldname: "budget_line_expense",
                    fieldtype: "float",
                    columns: 2,
                    required: true,
                    hidden: false,
                    placeholder: " ",
                },
               
            ]
        },
        {
            id: "impact_on_budget",
            fieldlabel: "Impact On Budget",
            fieldname: "impact_on_budget",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            is_figure: true,
            default: '0.00',
        },
        {
            id: "difference",
            fieldlabel: "Difference",
            fieldname: "difference",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            is_figure: true,
            default: '0.00',
        },
    ],
}