import {reject } from "../../overrides/form/hr/core.js"
export default {
    setup: {
        model: "Interview_Rating",
        new_form_id: 'new-interview-rating',
        info_form_id: 'interview-info-rating',
        title: "Interview Rating",
        layout_columns: 6,
        allow_submit: true,
        allow_cancel: true,
        allow_delete: false,
        allow_print: false,
        allow_sending_mail: false,
    },
    fields: [
        {
            id: "interview",
            fieldlabel: "Interview",
            fieldname: "interview",
            fieldtype: "link",
            model: "Interview",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,
            description: "",
        },
        {
            id: "applicant",
            fieldlabel: "Applicant",
            fieldname: "applicant",
            fieldtype: "read-only",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,
            description: "",
            fetchfrom: "interview",
            fetchfield: "applicant",
        },
        {
            id: "designation",
            fieldlabel: "Designation",
            fieldname: "designation",
            fieldtype: "read-only",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,
            description: "",
            fetchfrom: "interview",
            fetchfield: "designation",
        },
        {
            id: "interview_type",
            fieldlabel: "Interview Type",
            fieldname: "interview_type",
            fieldtype: "read-only",
            columns: 2,
            required: false,
            hidden: true,
            fetchfrom: "interview",
            fetchfield: "interview_type",
        },
        {
            id: "scheduled_on",
            fieldlabel: "Scheduled On",
            fieldname: "scheduled_on",
            fieldtype: "read-only",
            columns: 2,
            required: false,
            hidden: true,
        },
        {
            id: "from-time",
            fieldlabel: "From Time",
            fieldname: "from_time",
            fieldtype: "time",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: true,
            fetchfrom: "interview",
            fetchfield: "from_time",
        },
        {
            id: "to_time",
            fieldlabel: "To Time",
            fieldname: "to_time",
            fieldtype: "time",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: true,
            fetchfrom: "interview",
            fetchfield: "to_time",
        },
        {
            id: "rating_complement",
            fieldlabel: "Rate Comment",
            fieldname: "rating_complement",
            fieldtype: "select",
            columns: 2,
            required: false,
            hidden: true,
            default: "Cleared",
            options: [
                "Cleared",
                "Rejected",
            ],
        },
        {
            id: "evaluator",
            fieldlabel: "Interview Evaluator",
            fieldname: "evaluator",
            fieldtype: "read-only",
            columns: 2,
            required: false,
            hidden: false,
            default: lite?.user?.first_name  + " " + lite?.user?.last_name

        },
        {
            id: "section-break",
            fieldlabel: "Interview Rating",
            fieldname: "section-break",
            fieldtype: "section-break",
            columns: 2,
            required: false,
            hidden: false,
        },
        {
            id: "qualifications",
            fieldlabel: "Qualifications",
            fieldname: "qualifications_rating",
            fieldtype: "table",
            required: false,
            hidden: false,
            columns: 3,
            model: "Candidate_Qualification",
            fields: [
                {
                    id: "qualification_type",
                    fieldlabel: "Qualification",
                    fieldname: "qualification_type",
                    fieldtype: "read-only",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "qualification",
                    fieldlabel: "Qualification",
                    fieldname: "qualification",
                    fieldtype: "read-only",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                }
            ]  
        },

        
        {
            id: "skills",
            fieldlabel: "Skill Assessment",
            fieldname: "skills_rating",
            fieldtype: "table",
            model: "Skill_Rating",
            required: false,
            hidden: false,
            columns: 3,
            fields: [
                {
                    id: "skill",
                    fieldlabel: "Skills",
                    fieldname: "skill",
                    fieldtype: "read-only",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "rating",
                    fieldlabel: "Rating",
                    fieldname: "rating",
                    fieldtype: "select",
                    options: [1,2,3,4,5],
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },   
            ]  
        },
        {
            id: "section-break",
            fieldlabel: "Competence Assessment",
            fieldname: "section-break",
            fieldtype: "section-break",
            columns: 2,
            required: false,
            hidden: false,
        },
        {
            id: "competess_assessment",
            fieldlabel: "Competence Assessment",
            fieldname: "competess_assessment",
            fieldtype: "table",
            model: "Competess_Assessment",
            required: false,
            hidden: false,
            columns: 3,
            fields: [
                {
                    id: "competess_assessment",
                    fieldlabel: "Competence Assessment",
                    fieldname: "competess",
                    fieldtype: "text",
                    columns: 5,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "has_competess",
                    fieldlabel: "Has",
                    fieldname: "has_competess",
                    fieldtype: "check",
                    columns: 5,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "rating",
                    fieldlabel: "Rating",
                    fieldname: "rating",
                    fieldtype: "select",
                    options: [1,2,3,4,5],
                    columns: 5,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
            ]
        },
        {
            id: "practical_skill",
            fieldlabel: "Practical Assessment",
            fieldname: "practical_skill",
            fieldtype: "table",
            model: "Practical_Assement",
            required: false,
            hidden: false,
            columns: 3,
            fields: [
                {
                    id: "practical_skill",
                    fieldlabel: "Practical Skill",
                    fieldname: "practical_skill",
                    fieldtype: "text",
                    columns: 5,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "has_practical_skill",
                    fieldlabel: "Has",
                    fieldname: "has_practical_skill",
                    fieldtype: "check",
                    columns: 5,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "rating",
                    fieldlabel: "Rating",
                    fieldname: "rating",
                    fieldtype: "select",
                    options: [1,2,3,4,5],
                    columns: 5,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
            ]
        },
        {
            id: "si",
            fieldlabel: "Interview Summary",
            fieldname: "si",
            fieldtype: "section-break",
            columns: 1,
            bolder: true,
            required: false,
            hidden: false,
        },
        {
            id: "feed_back",
            fieldlabel: "Feedback",
            fieldname: "feed_back",
            fieldtype: "rich",
            height: 300,
            columns: 6,
            placeholder: " ",
            required: false,
            hidden: false,
        },

    ]
}
