import {
   create_interview
} from "../../overrides/form/hr/core.js";

export default {
    setup: {
        model: "Interview_Schedule",
        new_form_id: 'new-interview-schedule',
        info_form_id: 'interview-schedule-info',
        title: "Interview Schedule",
        layout_columns: 12, 
    },
    form_actions: [{
        title: "Create Interview",
        icon: "price_check",
        icon_color: "indigo",
        action: create_interview,
        for_docstatus: [1],
        for_status: ["Submitted"],
    },
    ],

    fields: [
        {
            id: "schedule_for",
            fieldlabel: "Interview Schedule For",
            fieldname: "schedule_for",
            fieldtype: "read-only",
            options: ["Multiple Applicants"],
            columns: 3,
            placeholder: " ",
            required: true,
            hidden: false,
            default: "Multiple Applicants"
        },
        {
            id: "application",
            fieldlabel: "Job Application",
            fieldname: "application",
            fieldtype: "link",
            model: "Job_Application",
            columns: 3,
            placeholder: " ",
            required: false,
            hidden: false,
            filters: {
                status: "Short Listed"
            },
            displayon: ["schedule_for", "For Single Applicant"]
        },
        {
            id: "name",
            fieldlabel: "Schedule Name",
            fieldname: "name",
            fieldtype: "text",
            columns: 3,
            placeholder: " ",
            required: true,
            hidden: false,
            fetchfrom: "application",
            fetchfield: "name",
        },
        {
            id: "applicant",
            fieldlabel: "Applicant",
            fieldname: "applicant",
            fieldtype: "read-only",
            columns: 3,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "application",
            fetchfield: "applicant_name",
            displayon: ["schedule_for", "For Single Applicant"]
        },
        {
            id: "applicant_email",
            fieldlabel: "Applicant Email",
            fieldname: "applicant_email",
            fieldtype: "read-only",
            columns: 3,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "application",
            fetchfield: "email",
            displayon: ["schedule_for", "For Single Applicant"]
        },
        {
            id: "designation",
            fieldlabel: "Job Title",
            fieldname: "designation",
            fieldtype: "read-only",
            model: "Designation",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: true,
            fetchfrom: "application",
            fetchfield: "designation",
        },
        {
            id: "schedule",
            fieldlabel: "Scheduled On",
            fieldname: "schedule",
            fieldtype: "date",
            columns: 3,
            placeholder: " ",
            required: false,
            hidden: false,
            value: lite.utils.today(),
            displayon: ["schedule_for", "For Single Applicant"]
        },
        {
            id: "panel_type",
            fieldlabel: "Panel Type",
            fieldname: "panel_type",
            fieldtype: "select",
            options: ["Use Defined Panel", "Pre Defined Panel"],
            columns: 3,
            placeholder: " ",
            required: false,
            hidden: false,
            default: "Use Defined Panel",
        },
        {
            id: "chairperson",
            fieldlabel: "Chairperson",
            fieldname: "chairperson",
            fieldtype: "link",
            model: "Lite_User",
            columns: 3,
            placeholder: " ",
            required: false,
            hidden: false,
            displayon: ["panel_type", "Use Defined Panel"],
        },
        {
            id: "from-time",
            fieldlabel: "From Time",
            fieldname: "from_time",
            fieldtype: "time",
            columns: 3,
            placeholder: " ",
            required: false,
            hidden: false,
            displayon: ["schedule_for", "For Single Applicant"]
        },
        {
            id: "to_time",
            fieldlabel: "To Time",
            fieldname: "to_time",
            fieldtype: "time",
            columns: 3,
            placeholder: " ",
            required: false,
            hidden: false,
            displayon: ["schedule_for", "For Single Applicant"]
        },
        {
            id: "section-break",
            fieldlabel: "Interview Type",
            fieldname: "section-break",
            fieldtype: "section-break",
            required: true,
            hidden: false,
            columns: 12,
            placeholder: " ",
            addborder: true,
        },
        {
            id: "interview-type-physical",
            fieldlabel: "Physcal",
            fieldname: "physical_interview",
            fieldtype: "check",
            columns: 3,
            placeholder: " ",
            required: false,
            hidden: false,
            default: 1,
        },
        {
            id: "location",
            fieldlabel: "Location",
            fieldname: "location",
            fieldtype: "text",
            columns: 3,
            placeholder: " ",
            required: false,
            hidden: false,
            displayon: ["interview-type-physical", 1]
        },
        {
            id: "interview-type-virtual",
            fieldlabel: "Virtual Interview",
            fieldname: "virtual_interview",
            fieldtype: "check",
            columns: 3,
            placeholder: " ",
            required: false,
            hidden: false,
            default: 0
        },
        {
            id: "link-virtual-meeting",
            fieldlabel: "Link to Virtual Meeting ",
            fieldname: "link_to_virtual_meeting",
            fieldtype: "text",
            columns: 3,
            placeholder: " ",
            required: false,
            hidden: false,
            displayon: ["interview-type-virtual", 1]
        },
        {
            id: "83873",
            fieldlabel: "Interviewer Panel",
            fieldname: "83873",
            fieldtype: "section-break",
            columns: 3,
            addborder: true,
        },
        {
            id: "link_panel",
            fieldlabel: "Choose Panel",
            fieldname: "link_panel",
            fieldtype: "link",
            model: "Interview_Panel",
            displayon: ["panel_type", "Pre Defined Panel"],
            columns: 3,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "internal_interviewers",
            fieldlabel: "Internal Interviewers",
            fieldname: "internal_interviewers",
            fieldtype: "table",
            required: false,
            columns: 6,
            hidden: false,
            model: "Internal_Interviewers_Schedule",
            displayon: ["panel_type", "Use Defined Panel"],
            fields: [
                {
                    id: "interviewer_email",
                    fieldlabel: "Interviewer",
                    fieldname: "interviewer_email",
                    fieldtype: "link",
                    model: "Lite_User",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "interviewer_first_name",
                    fieldlabel: "Interviewer First Name",
                    fieldname: "interviewer_first_name",
                    fieldtype: "read-only",
                    columns: 2,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                    fetchfrom: "interviewer_email",
                    fetchfield: "first_name",
                },  
                {
                    id: "interviewer_last_name",
                    fieldlabel: "Interviewer Last Name",
                    fieldname: "interviewer_last_name",
                    fieldtype: "read-only",
                    columns: 2,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                    fetchfrom: "interviewer_email",
                    fetchfield: "last_name",
                },
            ]
        },
        {
            id: "external_Interviewers",
            fieldlabel: "External Interviewers",
            fieldname: "external_Interviewers",
            fieldtype: "table",
            required: false,
            hidden: false,
            columns: 6,
            model: "External_Interviewers_Schedule",
            displayon: ["panel_type", "Use Defined Panel"],
            fields: [
                {
                    id: "interviewer_email",
                    fieldlabel: "Interviewer Email",
                    fieldname: "interviewer_email",
                    fieldtype: "text",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "interviewer_first_name",
                    fieldlabel: "Interviewer First Name",
                    fieldname: "interviewer_first_name",
                    fieldtype: "text",
                    columns: 2,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },  
                {
                    id: "interviewer_last_name",
                    fieldlabel: "Interviewer Last Name",
                    fieldname: "interviewer_last_name",
                    fieldtype: "text",
                    columns: 2,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
            ]
        },
        {
            id: "83873",
            fieldlabel: " ",
            fieldname: "83873",
            fieldtype: "section-break",
            columns: 12,
            addborder: true,
        },
        {
            id: "applicants_list",
            fieldlabel: "Selected Applicants",
            fieldname: "applicants_list",
            fieldtype: "table",
            required: false,
            hidden: false,
            model: "Applicants_Schedule_List",
            displayon: ["schedule_for", "Multiple Applicants"],
            fields: [
                {
                    id: "application_app",
                    fieldlabel: "Short Listed Applicant",
                    fieldname: "application",
                    fieldtype: "link",
                    model: "Applicant_Short_List",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                    ablefield: true,
                },
                {
                    id: "position",
                    fieldlabel: "Short Listed Applicant",
                    fieldname: "position",
                    fieldtype: "read-only",
                    model: "Designation",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                    ablefield: true,
                    fetchfrom: "application_app",
                    fetchfield: "job_position",
                },
                {
                    id: "applicant",
                    fieldlabel: "Applicant",
                    fieldname: "applicant",
                    fieldtype: "read-only",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: true,
                    istablefield: true,
                    ablefield: true,
                    fetchfrom: "application_app",
                    fetchfield: "applicant_first_name" + ""+  "applicant_last_name"
                },
                {
                    id: "applicant_email",
                    fieldlabel: "Applicant Email",
                    fieldname: "applicant_email",
                    fieldtype: "read-only",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                    ablefield: true,
                    fetchfrom: "application_app",
                    fetchfield: "applicant_email"
                },
                {
                    id: "interview_date",
                    fieldlabel: "Interview Date",
                    fieldname: "interview_date",
                    fieldtype: "date",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                    ablefield: true,
                },
                {
                    id: "form_time",
                    fieldlabel: "Form Time",
                    fieldname: "form_time",
                    fieldtype: "time",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                    ablefield: true,
                },
                {
                    id: "to_time",
                    fieldlabel: "To Time",
                    fieldname: "to_time",
                    fieldtype: "time",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                    ablefield: true,
                },
            ]
        },
    ]
}