export default {
    setup: {
        model: "Interview_Panel",
        new_form_id: 'new-interview-panel',
        info_form_id: 'interview-panel-info',
        title: "Interview Panel",
        layout_columns: 12,
    },
    form_actions: [],

    fields: [
        {
            id: "name",
            fieldlabel: "Interview Panel",
            fieldname: "name",
            fieldtype: "text",
            columns: 12,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "chairperson",
            fieldlabel: "Chairperson",
            fieldname: "chairperson",
            fieldtype: "link",
            model: "Lite_User",
            columns: 12,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "internal_interviewers",
            fieldlabel: "Internal Interviewers",
            fieldname: "internal_interviewers",
            fieldtype: "table",
            required: false,
            columns: 6,
            hidden: false,
            model: "Panel_Internal_Interviewer",
            fields: [
                {
                    id: "interviewer_email",
                    fieldlabel: "Interviewer",
                    fieldname: "interviewer_email",
                    fieldtype: "link",
                    model: "Lite_User",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "interviewer_first_name",
                    fieldlabel: "Interviewer First Name",
                    fieldname: "interviewer_first_name",
                    fieldtype: "read-only",
                    columns: 2,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                    fetchfrom: "interviewer_email",
                    fetchfield: "first_name",
                },  
                {
                    id: "interviewer_last_name",
                    fieldlabel: "Interviewer Last Name",
                    fieldname: "interviewer_last_name",
                    fieldtype: "read-only",
                    columns: 2,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                    fetchfrom: "interviewer_email",
                    fetchfield: "last_name",
                },
            ]
        },
        {
            id: "external_Interviewers",
            fieldlabel: "External Interviewers",
            fieldname: "external_Interviewers",
            fieldtype: "table",
            required: false,
            hidden: false,
            columns: 6,
            model: "Panel_External_Interviewer",
            fields: [
                {
                    id: "interviewer_email",
                    fieldlabel: "Interviewer Email",
                    fieldname: "interviewer_email",
                    fieldtype: "text",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "interviewer_first_name",
                    fieldlabel: "Interviewer First Name",
                    fieldname: "interviewer_first_name",
                    fieldtype: "text",
                    columns: 2,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "interviewer_last_name",
                    fieldlabel: "Interviewer Last Name",
                    fieldname: "interviewer_last_name",
                    fieldtype: "text",
                    columns: 2,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
            ]
        },
    ]
}