import { consider_applicant, create_job_offer, reject, reverse_job_cons} from "../../overrides/form/hr/core.js"

export default {
    setup: {
        model: "Interview",
        new_form_id: 'new-interview',
        info_form_id: 'interview-info',
        title: "Interview",
        layout_columns: 6,
        allow_submit: true,
        allow_cancel: true,
        allow_delete: false,
        allow_print: false,
        allow_sending_mail: false,
    },
    form_actions: [{
        title: "Consider Applicant",
        icon: "price_check",
        icon_color: "indigo",
        action: consider_applicant,
        for_docstatus: [1],
        for_status: ["Submitted"],
    },
    {
        title: "Consideration Reversal",
        icon: "reset_shadow",
        icon_color: "orange",
        action: reverse_job_cons,
        for_docstatus: [1],
        for_status: ["Submitted"],
    },
    {
        title: "Create Job Offer",
        icon: "work",
        icon_color: "indigo",
        action: create_job_offer,
        for_docstatus: [1],
        for_status: ["Short Listed"],
    },
    {
        title: "Reject",
        icon: "sentiment_dissatisfied",
        icon_color: "indigo",
        action: reject,
        for_docstatus: [1],
        for_status: ["Submitted"],
    },
    ],
    fields: [
        {
            id: "short_listed_applicant",
            fieldlabel: "Interview For",
            fieldname: "short_listed_applicant",
            fieldtype: "link",
            model: "Applicant_Short_List",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,
            description: "",
        },
        {
            id: "email",
            fieldlabel: "Applicant Email",
            fieldname: "email",
            fieldtype: "text",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "short_listed_applicant",
            fetchfield: "applicant_email",
        },
        {
            id: "applicant",
            fieldlabel: "Applicant",
            fieldname: "applicant",
            fieldtype: "text",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "short_listed_applicant",
            fetchfield: "applicant",
        },
        {
            id: "contact_no",
            fieldlabel: "Contact No.",
            fieldname: "contact_no",
            fieldtype: "text",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "short_listed_applicant",
            fetchfield: "contact_no",
        },
        
        {
            id: "designation",
            fieldlabel: "Job Title",
            fieldname: "designation",
            fieldtype: "read-only",
            columns: 2,
            required: false,
            hidden: false,
            fetchfrom: "short_listed_applicant",
            fetchfield: "job_position",
        },
        {
            id: "from_time",
            fieldlabel: "Start Time.",
            fieldname: "from_time",
            fieldtype: "time",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "to_time",
            fieldlabel: "End Time.",
            fieldname: "to_time",
            fieldtype: "time",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "section-break",
            fieldlabel: "Applicant Skill Set",
            fieldname: "section-break",
            fieldtype: "section-break",
            columns: 2,
            required: false,
            hidden: false,
        },
        {
            id: "qualifications",
            fieldlabel: "Documents/Qualifications",
            fieldname: "qualifications",
            fieldtype: "table",
            model: "Interview_Qualification",
            required: false,
            hidden: false,
            columns: 3,
            addemptyrow: false,
            fields: [
                {
                    id: "qualification",
                    fieldlabel: "Qualification",
                    fieldname: "qualification",
                    fieldtype: "file",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "qualification_type",
                    fieldlabel: "Qualification Type",
                    fieldname: "qualification_type",
                    fieldtype: "read-only",
                    columns: 3,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
            ]
        },
        {
            id: "skills",
            fieldlabel: "Skill Rating",
            fieldname: "skills",
            fieldtype: "table",
            model: "Skill_Assessment",
            required: false,
            hidden: false,
            columns: 3,
            addemptyrow: false,
            fields: [
                {
                    id: "skill",
                    fieldlabel: "Skills",
                    fieldname: "skill",
                    fieldtype: "read-only",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "rating",
                    fieldlabel: "Rating",
                    fieldname: "rating",
                    fieldtype: "text",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },   
            ]  
        },

        {
            id: "feedback",
            fieldlabel: "Feedback",
            fieldname: "feedback",
            fieldtype: "table",
            required: false,
            hidden: false,
            model: "Feedback",
            addemptyrow: false,
            fields: [
                {
                    id: "interviewer_email",
                    fieldlabel: "Interviewer",
                    fieldname: "evaluator",
                    fieldtype: "read-only",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true, 
                },
                {
                    id: "interview_feedback",
                    fieldlabel: "Interview Feedback",
                    fieldname: "interview_feedback",
                    fieldtype: "text",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "rating",
                    fieldlabel: "Average Rating",
                    fieldname: "average_rating",
                    fieldtype: "text",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "competence",
                    fieldlabel: "Competence Total Rate",
                    fieldname: "competence",
                    fieldtype: "float",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "practical",
                    fieldlabel: "Practial Skill Total Rate",
                    fieldname: "practical",
                    fieldtype: "float",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "result",
                    fieldlabel: "Result",
                    fieldname: "result",
                    fieldtype: "select",
                    columns: 4,
                    options: [
                        "Cleared ",
                        "Rejected",
                    ],
                    placeholder: " ",
                    required: false,
                    hidden: true,
                    istablefield: true,
                },   
            ] 
        },
    ]
}
