import { short_list_applicant, create_employee } from '../../overrides/form/hr/core.js';

export default {
  setup: {
    new_form_id: 'new-job-application',
    info_form_id: 'job-application-info',
    title: "Job Application",
    layout_columns: 12,
    allow_submit: true,
    allow_cancel: true,
    allow_delete: false,
    allow_print: false,
    model: "Job_Application"
  },
  form_actions: [
    {
      title: "Short List Applicant",
      icon: "price_check",
      icon_color: "convert_to_text",
      action: short_list_applicant,
      for_docstatus: [1],
      for_status: ["Applied"],
      index: 1,
    },
    {
      title: "Create Employee",
      icon: "price_check",
      icon_color: "convert_to_text",
      action: create_employee,
      for_docstatus: [1],
      for_status: ["Applied"],
      index: 2,
    },
  ],
  fields: [
    {
        id: "applicant_first_name",
        fieldlabel: "First Name",
        fieldname: "applicant_first_name",
        fieldtype: "text",
        columns: 4,
        placeholder: " ",
        required: true,
        hidden: false,
    },
    {
        id: "applicant_middle_name",
        fieldlabel: "Middle Name",
        fieldname: "applicant_middle_name",
        fieldtype: "text",
        columns: 4,
        placeholder: " ",
        required: false,
        hidden: false,
    },
    {
        id: "applicant_last_name",
        fieldlabel: "Last Name",
        fieldname: "applicant_last_name",
        fieldtype: "text",
        columns: 4,
        placeholder: " ",
        required: true,
        hidden: false,
    },
    {
        id: "designation",
        fieldlabel: "Job Title",
        fieldname: "designation",
        fieldtype: "link",
        model: "Designation",
        columns: 4,
        placeholder: " ",
        required: false,
        hidden: false,
    },
    {
        id: "date_of_birth",
        fieldlabel: "Date of Birth",
        fieldname: "date_of_birth",
        fieldtype: "date",
        columns: 4,
        placeholder: " ",
        required: true,
        hidden: false,
    },
    {
        id: "marital_status",
        fieldlabel: "Marital Status",
        fieldname: "marital_status",
        fieldtype: "select",
        options: ["Single", "Married"],
        placeholder: " ",
        columns: 4,
        required: true,
        hidden: false,
    },
    {
        id: "gender",
        fieldlabel: "Gender",
        fieldname: "gender",
        fieldtype: "select",
        options: ["Male", "Female", "Other"],
        placeholder: " ",
        columns: 4,
        required: false,
        hidden: false,
    },
    {
        id: "nationality",
        fieldlabel: "Nationality",
        fieldname: "country",
        fieldtype: "link",
        model: "Country",
        columns: 4,
        placeholder: " ",
        required: false,
        hidden: false,
    },
    {
        id: "id_nrc",
        fieldlabel: "ID/NRC",
        fieldname: "id_nrc",
        fieldtype: "text",
        columns: 4,
        placeholder: " ",
        required: false,
        hidden: false,
    },
    {
        id: "email",
        fieldlabel: "Email Address",
        fieldname: "email",
        fieldtype: "text",
        columns: 4,
        placeholder: " ",
        required: true,
        hidden: false,
    },
    {
        id: "postal_address",
        fieldlabel: "Postal Address",
        fieldname: "postal_address",
        fieldtype: "text",
        columns: 4,
        placeholder: " ",
        required: true,
        hidden: false,
    },
    {
        id: "physical_address",
        fieldlabel: "Physical Address",
        fieldname: "physical_address",
        fieldtype: "text",
        columns: 4,
        placeholder: " ",
        required: true,
        hidden: false,
    },
    {
        id: "mobile",
        fieldlabel: "Phone Number",
        fieldname: "mobile",
        fieldtype: "text",
        columns: 4,
        placeholder: " ",
        required: true,
        hidden: false,
    },
    {
        id: "Skills_Qualification",
        fieldlabel: "Skills/Qualification",
        fieldtype: "section-break",
        addborder: true
    },
    {
        id: "applicant_attachement",
        fieldlabel: "Files/Attachments",
        fieldname: "applicant_attachement",
        fieldtype: "table",
        columns: 6,
        required: false,
        hidden: false,
        model: "Application_Attachment",
        fields: [
            {
                id: "file_name",
                fieldlabel: "File Name",
                fieldname: "qualification_type",
                fieldtype: "text",
                columns: 4,
                placeholder: " ",
                required: false,
                hidden: false,
                istablefield: true,
            },
            {
                id: "qualification",
                fieldlabel: "Attachment",
                fieldname: "qualification",
                fieldtype: "file",
                columns: 8,
                placeholder: " ",
                required: false,
                hidden: false,
                istablefield: true,
            },
        ]
    },
    {
        id: "job_skills",
        fieldlabel: "Skills",
        fieldname: "job_skills",
        fieldtype: "table",
        model: "Job_Application_Skill",
        required: false,
        hidden: false,
        columns: 6,
        fields: [
            {
                id: "skill",
                fieldlabel: "Skill",
                fieldname: "skill",
                fieldtype: "text",
                columns: 3,
                placeholder: " ",
                required: false,
                hidden: false,
                istablefield: true,
            },
            {
                id: "has_skill",
                fieldlabel: "Must Have",
                fieldname: "has_skill",
                fieldtype: "check",
                columns: 3,
                placeholder: " ",
                required: false,
                hidden: true,
                istablefield: true,
            },
        ]
    },
  ],
};
