export default {
    setup: {
        new_form_id: 'new-leavetype',
        info_form_id: 'leave-type-info',
        title: "Leave Type",
        layout_columns: 6,
        model: "Leave_Type"
    },
    fields: [
        {
            id: "leave-type-name",
            fieldlabel: "Leave Type Name ",
            fieldname: "name",
            fieldtype: "text",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "total-days-allocated-per-month",
            fieldlabel: "Total Days Allocated Per Month",
            fieldname: "total_days_allocated_per_month",
            fieldtype: "int",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            default: "0"
        },
        {
            id: "maximum-leaves",
            fieldlabel: "Maximum Consecutive Leave Days Allowed",
            fieldname: "maximum_leave_allocated",
            fieldtype: "int",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            default: "0"
        },
        {
            id: "apply_on",
            fieldlabel: "Who to Apply On",
            fieldname: "apply_on",
            fieldtype: "select",
            columns: 2,
            required: false,
            hidden: false,
            placeholder: " ",
            options: ["Female", "Male", "Both"],
        },
        {
            id: "leave_days_type",
            fieldlabel: "Leave Days Type",
            fieldname: "leave_days_type",
            fieldtype: "select",
            columns: 2,
            required: false,
            hidden: false,
            placeholder: " ",
            options: ["Working Days", "Calendar Days"],
        },
        {
            id: "accrual_frequency",
            fieldlabel: "Accrual Frequency",
            fieldname: "accrual_frequency",
            fieldtype: "select",
            default: "Dose Not Accrual",
            options: ["Monthly", "Quarterly", "Two Months", "Six Months", "Dose Not Accrue"],
            columns: 2,
            required: false,
            hidden: false,
        },
        {
            id: "leave_type_year",
            fieldlabel: "Leave Type Year",
            fieldname: "leave_type_year",
            fieldtype: "select",
            options: ["Calendar Year", "Employee Year"],
            columns: 2,
            required: false,
            hidden: false,
        },

        {
            id: "carry_forward",
            fieldlabel: "Is Carry Forward",
            fieldname: "carry_forward",
            fieldtype: "check",
            columns: 1,
            required: false,
            hidden: false,
        },
        {
            id: "maximum_carry_forward_days",
            fieldlabel: "Carry Forward Days",
            fieldname: "maximum_carry_forward_days",
            fieldtype: "text",
            columns: 1,
            required: false,
            hidden: false,
            default: "0"
        },
        {
            id: "is-compensatory",
            fieldlabel: "Is Compensatory",
            fieldname: "is_compensatory",
            fieldtype: "check",
            columns: 1,
            required: false,
            hidden: false,
        },

        {
            id: "is_commutable",
            fieldlabel: "Is Commutable",
            fieldname: "is_commutable",
            fieldtype: "check",
            columns: 1,
            required: false,
            hidden: false,
        },
        {
            id: "maximum_commutable_days",
            fieldlabel: "Maximum Commutable Days",
            fieldname: "maximum_commutable_days",
            fieldtype: "float",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            default: '0',
            displayon: ["is_commutable", 1]
        },
        {
            id: "is-on_probation",
            fieldlabel: "Enabled On Probation",
            fieldname: "is_on_probation",
            fieldtype: "check",
            columns: 1,
            required: false,
            hidden: false,
        },
        {
            id: "show_on_payslip",
            fieldlabel: "Show On Payslip",
            fieldname: "show_on_payslip",
            fieldtype: "check",
            columns: 1,
            required: false,
            hidden: false,
        },
        {
            id: "allow_system_auto_accrual",
            fieldlabel: "Auto Accrual",
            fieldname: "allow_system_auto_accrual",
            fieldtype: "check",
            columns: 1,
            required: false,
            hidden: false,
            default: 0,
            displayon: ["accrual_frequency", "Monthly", "Quarterly", "Two Months", "Six Months"]
        },
    ],
}