import {
    create_leave_allocation,
} from "../../overrides/form/hr/core.js";

export default {
    setup: {
        model: "Leave_Policy",
        new_form_id: 'new-leave-policy',
        info_form_id: 'leave-policy-info',
        title: "Leave Policy",
        layout_columns: 4,
        allow_submit: false,
        allow_cancel: false,
        allow_delete: true,
        allow_print: false,
        allow_sending_mail: false,
    },
    form_actions: [{
        title: "Create Leave Allocation",
        icon: "price_check",
        icon_color: "indigo",
        action: create_leave_allocation,
        for_docstatus: [1],
        for_status: ["Submitted"],
    },
],
    fields: [
        {
            id: "name",
            fieldlabel: "Name",
            fieldname: "name",
            fieldtype: "text",
            columns: 2,
            placeholder: "Enter name",
            required: false,
            hidden: true,
            default: "Annual Leave",
        },
        {
            id: "leave_policy",
            fieldlabel: "Leave Policy",
            fieldname: "leave_policy",
            fieldtype: "read-only",
            columns: 2,
            placeholder: "Enter leave policy",
            required: true,
            hidden: false,
            description: "",
            default: "Annual Leave",
        },
        {
            id: "policy_for",
            fieldlabel: "Select Policy For",
            fieldname: "policy_for",
            fieldtype: "select",
            columns: 2,
            placeholder: "Enter Policy",
            required: true,
            hidden: false,
            description: "",
            options: ["Employment Type", "Employee Grade", "Designation"]
        },
        {
            id: "details",
            fieldlabel: "Leave Configurations",
            fieldname: "ci",
            fieldtype: "section-break",
            addborder: true,
            columns: 1,
            hidden: false,
        },
        {
            id: "policy_details",
            fieldlabel: "Leave Policy Details",
            fieldname: "policy_details",
            fieldtype: "table",
            required: false,
            hidden: false,
            model: "Policy_Details",
            // addemptyrow: false,
            fields: [
                {
                    id: "policy_type",
                    fieldlabel: "Policy Type",
                    fieldname: "policy_type",
                    fieldtype: "read-only",
                    columns: 4,
                    placeholder: "Enter policy type",
                    required: true,
                    hidden: false,
                    description: "",
                },
                {
                    id: "total-days-allocated-per-month",
                    fieldlabel: "Month's Allocation",
                    fieldname: "total_days_allocated_per_month",
                    fieldtype: "float",
                    columns: 4,
                    placeholder: "Enter policy type",
                    required: false,
                    hidden: false,
                    default: "0.00",
                },
                {
                    id: "annual_allocation",
                    fieldlabel: "Annual Allocated",
                    fieldname: "annual_allocation",
                    fieldtype: "float",
                    columns: 4,
                    default: "0",
                    placeholder: "Enter days",
                    required: false,
                    hidden: true,
                    description: ""
                },
            ]
        },
    ]
}