export default {
    setup: {
        new_form_id: 'new-locations',
        info_form_id: 'locations-info',
        title: "Location",
        layout_columns: 3,
        model: "Branch"
    },
    fields: [
        {
            id: "name",
            fieldlabel: "Location Name",
            fieldname: "name",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            description: "Location Name",
        },
        {
            id: "branch_id",
            fieldlabel: "Location ID",
            fieldname: "branch_id",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            description: "Location ID",
        },
        {
            id: "is_main_branch",
            fieldlabel: "Is Main Location",
            fieldname: "is_main_branch",
            fieldtype: "check",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            description: "Is Main Location",
        },
        {
            id: "branch_location",
            fieldlabel: "Location Insight",
            fieldname: "branch_location",
            fieldtype: "longtext",
            classnames: "h-[160px]",
            columns: 3,
            placeholder: " ",
            required: false,
            hidden: false,
            description: "Branch Location",
        },
    ],
}