export default {
    setup: {
        new_form_id: 'new-bpa',
        info_form_id: 'bpa-info',
        title: "Bonus Type",
        layout_columns: 6,
        model: "Long_Term_Sponsorship_Bonding_Period",
        // allow_submit: true,
        // allow_councel: true,
        // allow_print: true,
        // allow_delete: true,
    },
    fields: [
        {
            id: "agreement_date",
            fieldlabel: "Agreement Date",
            fieldname: "agreement_date",
            fieldtype: "date",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            default: lite.utils.today (),
        },
        {
            id: "employee",
            fieldlabel: "Employee No",
            fieldname: "employee",
            fieldtype: "link",
            model: "Employee",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "applicant_names",
            fieldlabel: "Applicant Names",
            fieldname: "applicant_names",
            fieldtype: "read-only",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "full_name",
        },
        {
            id: "nrc",
            fieldlabel: "Applicant Names",
            fieldname: "nrc",
            fieldtype: "txt",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "id_no",
        },
        {
            id: "qualification",
            fieldlabel: "Qualification",
            fieldname: "qualification",
            fieldtype: "link",
            model: "Skill",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "program",
            fieldlabel: "Program",
            fieldname: "program",
            fieldtype: "link",
            model: "Skill",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "start_date",
            fieldlabel: "Program Start Date",
            fieldname: "start_date",
            fieldtype: "date",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            default: lite.utils.today (),
        },
        {
            id: "end_date",
            fieldlabel: "Program End Date",
            fieldname: "end_date",
            fieldtype: "date",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            default: lite.utils.today (),
        },
    ],
}