const empInfo = lite.system_settings.employee_info
export default {
    setup: {
        new_form_id: 'new-performance-agreement',
        info_form_id: 'performance-agreement-info',
        title: "Performance Agreement",
        layout_columns: 4,
        model: "Performance_Agreement",
        allow_delete: false,
        allow_disable: false,
    },
    fields: [
        {
            id: "name",
            fieldlabel: "Applicant",
            fieldname: "name",
            fieldtype: "link",
            model: "Employee",
            columns: 1,
            required: true,
            hidden: false,
            placeholder: " ",
            default: empInfo?.name,
        },
        {
            id: "employee",
            fieldlabel:  "Employee No",
            fieldname: "employee",
            fieldtype: "read-only",
            columns: 1,
            required: false,
            hidden: true,
            placeholder: " ",
            default: empInfo?.name,
        },
        {
            id: "full_name",
            fieldlabel: "Full Names",
            fieldname: "full_name",
            fieldtype: "text",
            columns: 1,
            required: true,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "first_name",
            fieldlabel: "First Name",
            fieldname: "first_name",
            fieldtype: "text",
            columns: 1,
            required: false,
            hidden: true,
            fetchfrom: "name",
            fetchfield: "first_name",
            placeholder: " ",

        },
        {
            id: "last_name",
            fieldlabel: "Last Name",
            fieldname: "last_name",
            fieldtype: "text",
            columns: 1,
            required: false,
            hidden: true,
            fetchfrom: "name",
            fetchfield: "last_name",
            placeholder: " ",

        }, 
        {
            id: "middle_name",
            fieldlabel: "Middle Name",
            fieldname: "middle_name",
            fieldtype: "text",
            columns: 1,
            required: false,
            hidden: true,
            fetchfrom: "name",
            fetchfield: "middle_name",
            placeholder: " ",

        }, 
        {
            id: "report_to",
            fieldlabel: "Report To",
            fieldname: "report_to",
            fieldtype: "link",
            model: "Lite_User",
            columns: 1,
            required: true,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "period",
            fieldlabel: "Period",
            fieldname: "period",
            fieldtype: "text",
            columns: 1,
            required: true,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "agreement_due_date",
            fieldlabel: "Agreement Due Date",
            fieldname: "agreement_due_date",
            fieldtype: "date",
            columns: 1,
            required: true,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "performance_kpi",
            fieldlabel: "Performance KPIS",
            fieldname: "performance_kpi",
            fieldtype: "table",
            model: "Performance_Agreement_KPIs",
            required: false,
            hidden: false,
            description: "Performance KPIS",
            columns: 4,
            fields: [
                {
                    id: "kpi",
                    fieldlabel: " KPI",
                    fieldname: "kpi",
                    fieldtype: "text",
                    columns: 2,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },

                {
                    id: "from_date",
                    fieldlabel: "From Date",
                    fieldname: "from_date",
                    fieldtype: "date",
                    columns: 2,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                },
                {
                    id: "to_date",
                    fieldlabel: "To Date",
                    fieldname: "to_date",
                    fieldtype: "date",
                    columns: 2,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                },

                {
                    id: "description",
                    fieldlabel: "Description",
                    fieldname: "description",
                    fieldtype: "expandable",
                    columns: 2,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
            ]
        },
    ],
}
