const ss = await lite.connect.get_system_settings()

export default {
    setup: {
        new_form_id: 'new-working-pattern',
        info_form_id: 'working-pattern-info',
        title: "Request For Absence",
        layout_columns: 3,
        model: "Request_For_Absence",
        allow_submit: true,
    },
    
    fields: [
        {
            id: "employee",
            fieldlabel: "Employee No",
            fieldname: "employee",
            fieldtype: "link",
            model: "Employee",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            filters: {
                status: "Active",
            }, 
        }, 
        {
            id: "name",
            fieldlabel: "Employee Name",
            fieldname: "name",
            fieldtype: "read-only",
            columns: 1,
            placeholder: "",
            required: false,
            hidden: false,
            fetchfrom:"employee",
            fetchfield: "first_name",
        }, 
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom:"employee",
            fetchfield: "department"
        },
        {
            id: "start_date",
            fieldlabel: "Absence Start Date",
            fieldname: "start_date",
            fieldtype: "date",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        }, 
        {
            id: "end_date",
            fieldlabel: "Absence End Date",
            fieldname: "end_date",
            fieldtype: "date",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "days",
            fieldlabel: "Days",
            fieldname: "days",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
        },
        {
            id: "hours",
            fieldlabel: "Hours",
            fieldname: "hours",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
        },
        {
            id: "absence_type",
            fieldlabel: "Absence Type",
            fieldname: "absence_type",
            fieldtype: "select",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            options: ["Sickness",]
        }, 
        {
            id: "sick_note",
            fieldlabel: "Sick Note",
            fieldname: "sick_note",
            fieldtype: "file",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            displayon: ["absence_type", "Sickness"]
        },
        {
            id: "absence_reason",
            fieldlabel: "Reason",
            fieldname: "absence_reason",
            fieldtype: "longtext",
            columns: 3,
            placeholder: " ",
            required: false,
            hidden: false,
            classnames: "h-[250px]",
        },
    ],
}