

export default {
    setup: {
        new_form_id: 'new-training-plan',
        info_form_id: 'training-plan-info',
        title: "Training Plan",
        layout_columns: 3,
        model: "Training_Plan",
        allow_submit: true,
        allow_cancel: true,
        allow_delete: false,
        allow_print: false,
        allow_sending_mail: false,
    },
    form_actions: [
    ],
    fields: [
        {
            id: "plan",
            fieldlabel: "Plan Name",
            fieldname: "name",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
        },
        {
            id: "company",
            fieldlabel: "Council",
            fieldname: "company",
            fieldtype: "link",
            model: "Company",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: true,
            default: lite?.user?.company?.name,
        },
        {
            id: "plan-period",
            fieldlabel: "Period",
            fieldname: "plan_period",
            fieldtype: "select",
            columns: 1,
            required: true,
            hidden: false,
            placeholder: " ",
            options: ["Quarter", "Bi Annual", "Annual",]
        },
        {
            id: "from-date",
            fieldlabel: "Start Date",
            fieldname: "from_date",
            fieldtype: "date",
            columns: 1,
            required: false,
            hidden: false,
            default: lite.utils.today(),
        },
        {
            id: "to-date",
            fieldlabel: "To Date",
            fieldname: "to_date",
            fieldtype: "date",
            columns: 1,
            required: false,
            hidden: false,
            default: lite.utils.today(),
        },


        {
            id: "sec",
            fieldlabel: "",
            fieldname: "sec",
            fieldtype: "section-break",
            columns: 1,
            addborder: true,
            required: false,
            hidden: false,
        },

        {
            id: "listed_trianing_plans",
            fieldlabel: "Training Plans",
            fieldname: "listed_trianing_plans",
            fieldtype: "table",
            required: true,
            hidden: false,
            model: "Listed_Trianing_Plans",
            fields: [
                {
                    id: "training",
                    fieldlabel: "Training Program",
                    fieldname: "training_program",
                    fieldtype: "text",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                },
                {
                    id: "type",
                    fieldlabel: "Program Type",
                    fieldname: "training_type",
                    fieldtype: "link",
                    model: "Training_Program_Type",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                },        
                {
                    id: "course",
                    fieldlabel: "Course",
                    fieldname: "course",
                    fieldtype: "text",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    // displayon: ["type","Course"]
                },
        
                {
                    id: "program-duration",
                    fieldlabel: "Program Duration",
                    fieldname: "program_duration",
                    fieldtype: "text",
                    columns: 4,
                    required: false,
                    hidden: false,
                    placeholder: " ",
                    default: "1 week"
                },
                {
                    id: "certification-type",
                    fieldlabel: "Certification Type",
                    fieldname: "certification_type",
                    fieldtype: "select", 
                    columns: 4,
                    required: false,
                    hidden: false, 
                    options: [
                        "Certificate",
                        "Diploma",
                        "Degree",
                        "Other",
                        "Certification of Attendance",
                        "Certification of Completion",
                        "Professional Certification",
                        "Industry Certification",
                        "License",
                        "Accreditation",
                        "Qualification",
                        "Award",
                        "Recognition",
                        "Specialized Certification",
                        "Advanced Certification",
                        "Master Certification",
                        "Expert Certification"
                    ],
                    placeholder: " ",
                    defualt: "Certificate",
                    // displayon: ["includes-certification", 1], 
                },  
                {
                    id: "description",
                    fieldlabel: "Program Description",
                    fieldname: "description",
                    fieldtype: "expandable",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: true,
                },
                {
                    id: "training-expense",
                    fieldlabel: "Training Expense",
                    fieldname: "training_expense",
                    fieldtype: "currency",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                },

            ]
        },
        {
            id: "description",
            fieldlabel: "Description",
            fieldname: "description",
            fieldtype: "rich",
            height: 200,
            columns: 3,
            placeholder: " ",
            required: false,
            hidden: false,
        },
    ],
}