
export default {
    setup: {
        new_form_id: 'new-transport-request',
        info_form_id: 'transport-request-info',
        title: "Transport Request",
        layout_columns: 4,
        model: "Transport_Request",
        include_logo: false,
        allow_submit: true,
        allow_cancel: false,
        allow_delete: false,
        allow_print: false,
        allow_sending_mail: false,
        allow_disable: false,
    },
    fields: [
        {
            id: "applicant",
            fieldlabel: "Employee No",
            fieldname: "applicant",
            fieldtype: "link",
            model: "Employee",
            columns: 1,
            required: true,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "full_name",
            fieldlabel: "Applicant",
            fieldname: "full_name",
            fieldtype: "read-only",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            fetchfrom: "applicant",
            fetchfield: "full_name",
            // default:lite?.employee_info?.full_name
        },
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "link",
            model: "Department",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            fetchfrom: "applicant",
            fetchfield: "department",
            // default: lite?.employee_info?.department
        },
        {
            id: "duration",
            fieldlabel: "Duration",
            fieldname: "duration",
            fieldtype: "select",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            options: ["Hours", "Days"]
        },
        {
            id: "hours",
            fieldlabel: "Hours",
            fieldname: "hours",
            fieldtype: "text",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            displayon: ["duration", "Hours"]
        },
        {
            id: "days",
            fieldlabel: "Days",
            fieldname: "days",
            fieldtype: "text",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            displayon: ["duration", "Days"]
        },
        {
            id: "transport_details",
            fieldlabel: "Transport Details",
            fieldname: "transport_details",
            fieldtype: "table",
            model: "Transport_Details",
            required: false,
            hidden: false,
            fields: [
                {
                    id: "date_required",
                    fieldlabel: "Date Required",
                    fieldname: "date_required",
                    fieldtype: "date",
                    placeholder: " ",
                    columns: 3,
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "time",
                    fieldlabel: "Time",
                    fieldname: "time",
                    fieldtype: "time",
                    columns: 3,
                    required: true,
                    hidden: false,
                    placeholder: " ",
                },
                {
                    id: "destination",
                    fieldlabel: "Destination",
                    fieldname: "destination",
                    fieldtype: "text",
                    columns: 2,
                    required: false,
                    hidden: false,
                    placeholder: " ",
                },
            ] ,
        },
        {
            id: "transport_purpose",
            fieldlabel: "Purpose for Requesting Transport",
            fieldname: "transport_purpose",
            fieldtype: "rich",
            height: 200,
            columns: 4,
            required: false,
            hidden: false,
        },
    ],
}