export default {
    setup: {
        new_form_id: 'new-tution-advance-of-salary',
        info_form_id: 'tution-advance-of-salary-info',
        title: "Tution Advance Of Salary Form",
        layout_columns: 4,
        model: "Tution_Advance_Of_Salary"
    },
    fields: [
        {
            id: "employee-id",
            fieldlabel: "Employee No",
            fieldname: "employee_on",
            fieldtype: "link",
            model: "Employee",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
       
        {
            id: "employee_full_names",
            fieldlabel: "Full Names",
            fieldname: "employee_full_names",
            fieldtype: "read-only",
            columns: 1,
            required: false,
            hidden: false,
            fetchfrom: "employee-id",
            fetchfield: "full_name"
        },
        {
            id: "email",
            fieldlabel: "Email",
            fieldname: "email",
            fieldtype: "read-only",
            columns: 1,
            required: false,
            hidden: true,
            fetchfrom: "employee-id",
            fetchfield: "email"
        },
        {
            id: "contact_no",
            fieldlabel: "Contact No",
            fieldname: "contact_no",
            fieldtype: "read-only",
            columns: 1,
            required: false,
            hidden: true,
            fetchfrom: "employee-id",
            fetchfield: "contact"
        },
        {
            id: "salary_scale",
            fieldlabel: "Salary Scale",
            fieldname: "salary_scale",
            fieldtype: "read-only",
            columns: 1,
            required: false,
            hidden: false,
            fetchfrom: "employee-id",
            fetchfield: "employee_grade"
        },
        {
            id: "maximum_loan_amount_requested",
            fieldlabel: "Loan Amount Requested",
            fieldname: "maximum_loan_amount_requested",
            fieldtype: "float",
            columns: 1,
            required: false,
            hidden: false,
        },
        {
            id: "company-info",
            fieldlabel: "",
            fieldname: "ci",
            fieldtype: "section-break",
            addborder: true,
            columns: 1,
            required: false,
            hidden: false,
        },
        {
            id: "maximum_loan_amount_approved",
            fieldlabel: "Loan Amount Approved",
            fieldname: "maximum_loan_amount_approved",
            fieldtype: "float",
            columns: 1,
            required: false,
            hidden: false,
        },
        {
            id: "company-info",
            fieldlabel: "Employee Consent",
            fieldname: "ci",
            fieldtype: "section-break",
            addborder: true,
            columns: 1,
            required: false,
            hidden: false,
        },
        {
            id: "repayment_period",
            fieldlabel: "Repayment Period",
            fieldname: "repayment_period",
            fieldtype: "text",
            columns: 1,
            required: false,
            hidden: false,
        },
        {
            id: "monthly_deduction_amount",
            fieldlabel: "Monthly Deduction Amount",
            fieldname: "monthly_deduction_amount",
            fieldtype: "float",
            columns: 1,
            required: false,
            hidden: false,
        },
        
        {
            id: "nrc_id",
            fieldlabel: "NRC/ID",
            fieldname: "nrc_id",
            fieldtype: "float",
            columns: 1,
            required: false,
            hidden: false,
            fetchfrom: "employee-id",
            fetchfield: "id_no"
        },
        {
            id: "date",
            fieldlabel: "Date",
            fieldname: "date",
            fieldtype: "date",
            columns: 1,
            required: false,
            hidden: false,
        },
        {
            id: "company-info",
            fieldlabel: "Accounts",
            fieldname: "ci",
            fieldtype: "section-break",
            addborder: true,
            columns: 1,
            required: false,
            hidden: true,
        },
    ],
    
}