# General
daemonize yes
pidfile /var/run/redis/redis-server.pid
bind 127.0.0.1
port 6379

# Logging
logfile /var/log/redis/redis-server.log
loglevel notice 

# Database
databases 16 
# Persistence
save 900 1   
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes 
dir /home/lite/startapp_framework
