export default {
    setup: {
        new_form_id: 'new-staff-charge-form',
        info_form_id: 'staff-charge-form-info',
        title: "Charge Form",
        layout_columns: 9,
        allow_submit: true,
        allow_cancel: false,
        allow_delete: false,
        allow_print: false,
        allow_sending_mail: true,
        model: "Charge_Form"
    },
    fields: [
        {
            id: "section-break-001",
            fieldlabel: "This form must be completed by the Supervisor/Head of Department charging the employee who has violated any Council rule",
            fieldname: "",
            fieldtype: "section-break",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "name",
            fieldlabel: "Document Id",
            fieldname: "name",
            fieldtype: "text",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: true,
        },
        {
            id: "employee",
            fieldlabel: "Employee No",
            fieldname: "employee",
            fieldtype: "link",
            model: "Employee",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,
            default: lite?.employee_info?.name
        },



        {
            id: "employee_name",
            fieldlabel: "Employee Names",
            fieldname: "employee_name",
            fieldtype: "text",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "full_name",
        },

        {
            id: "column-break-001",
            fieldlabel: "",
            fieldname: "",
            fieldtype: "column-break",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "engagement_date",
            fieldlabel: "Date of Engagement",
            fieldname: "engagement_date",
            fieldtype: "date",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "date_of_joining",
        },      
        


        {
            id: "job-title",
            fieldlabel: "Job Title",
            fieldname: "job_title",
            fieldtype: "link",
            model: "Designation",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "designation",
        },
        {
            id: "date_of_occurance",
            fieldlabel: "Date of Occurrence",
            fieldname: "date_of_occurance",
            fieldtype: "date",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,
            default: lite?.utils?.today(),
        },


        {
            id: "place-of-occurance",
            fieldlabel: "Place of Occurrence",
            fieldname: "place_of_occurance",
            fieldtype: "text",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "column-break-002",
            fieldlabel: "",
            fieldname: "",
            fieldtype: "column-break",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "offence",
            fieldlabel: "Offense",
            fieldname: "offence",
            fieldtype: "link",
            model: "Violation_Type",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "meantime",
            fieldlabel: "In the meantime",
            fieldname: "meantime",
            fieldtype: "select",
            options: ["You will cease working to enable us carry out investigation", "You will continue working"],
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "facts-of-occurance",
            fieldlabel: "Facts of Occurrence",
            fieldname: "facts_of_occurance",
            fieldtype: "rich",
            height: 200,
            columns: 9,
            placeholder: " ",
            required: false,
            hidden: false,
        },

        {
            id: "section-break-001",
            fieldlabel: "",
            fieldname: "",
            fieldtype: "read-only",
            columns: 9,
            placeholder: " ",
            classname: "border-none text-semibold text-xl h-[2rem] ",
            required: false,
            hidden: false,
            default: "Having read the charge, you are hereby required to submit a written exculpatory statement (using the statement form) to Human Resource Section within 5 working days. Management reserves the right to institute necessary disciplinary action if you fail to exculpate yourself within the stipulated time frame."
        },
        {
            id: "charging-officer-id",
            fieldlabel: "Charging Offense Id",
            fieldname: "charging_office_id",
            fieldtype: "link",
            model: "Employee",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "report_to",
            default: lite?.employee_info?.name
        },
        {
            id: "charging-officer",
            fieldlabel: "Charging Officer",
            fieldname: "charging_office_name",
            fieldtype: "read-only",
            model: "Employee",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "charging-officer-id",
            fetchfield: "full_name",
        },
        {
            id: "charging-date",
            fieldlabel: "Charge Date",
            fieldname: "charging_date",
            fieldtype: "date",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            default: lite?.utils.today()
        },
        {
            id: "atteachment",
            fieldlabel: "Attach Charge Evidence",
            fieldname: "atteachment_evidance",
            fieldtype: "file",
            columns: 3,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "charge-witness",
            fieldlabel: "Witnesses",
            fieldname: "charge_witness",
            fieldtype: "table",
            model: "Charge_Witness",
            columns: 9,
            placeholder: " ",
            required: false,
            hidden: false,
            fields:[
                {
                    id: "witness",
                    fieldlabel: "Witness ID",
                    fieldname: "witness",
                    fieldtype: "link",
                    model: "Employee",
                    columns: 8,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                },
                {
                    id: "witness-name",
                    fieldlabel: "Witness Full Name",
                    fieldname: "witness_name",
                    fieldtype: "text",
                    columns: 8,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    fetchfrom: "witness",
                    fetchfield: "full_name",
                },
                {
                    id: "department",
                    fieldlabel: "Department",
                    fieldname: "department",
                    fieldtype: "link",
                    model: "Department",
                    columns: 8,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    fetchfrom: "witness",
                    fetchfield: "department",
                },
            ]
        }
    ],
}