export default {
    setup: {
        new_form_id: 'new-staff-clearance-form',
        info_form_id: 'staff-clearance-form-info',
        title: "Clearance Form",
        layout_columns: 9,
        model: "Clearance_Form"
    },
    fields: [
        {
            id: "name",
            fieldlabel: "Document Id",
            fieldname: "name",
            fieldtype: "text",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: true,
        },
        {
            id: "employee",
            fieldlabel: "Employee No",
            fieldname: "employee",
            fieldtype: "link",
            model: "Employee",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            default: lite.employee_info?.name,
        },


        {
            id: "column-break-001",
            fieldlabel: "",
            fieldname: "",
            fieldtype: "column-break",
            columns: 2,
            placeholder: "",
            required: false,
            hidden: false,
        },


        {
            id: "employee_name",
            fieldlabel: "Employee Names",
            fieldname: "employee_name",
            fieldtype: "text",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "full_name",
        },
        {
            id: "engagement_date",
            fieldlabel: "Date of Engagement",
            fieldname: "engagement_date",
            fieldtype: "date",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "date_of_joining",
        },
        {
            id: "job-title",
            fieldlabel: "Job Title",
            fieldname: "job_title",
            fieldtype: "link",
            model: "Designation",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "designation",
        },
        {
            id: "date_of_separation",
            fieldlabel: "Date of Separation",
            fieldname: "date_of_separation",
            fieldtype: "date",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            default: lite?.utils?.today(),
        },


        {
            id: "column-break-002",
            fieldlabel: "",
            fieldname: "",
            fieldtype: "column-break",
            columns: 2,
            placeholder: "",
            required: false,
            hidden: false,
        },


        {
            id: "salary-grade",
            fieldlabel: "Salary Grade",
            fieldname: "salary_grade",
            fieldtype: "link",
            model: "Employee_Grade",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "employee_grade",
        },
        {
            id: "clearance-date",
            fieldlabel: "Clearance Date",
            fieldname: "clearance_date",
            fieldtype: "date",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
        },

        // TABLE
        {
            id: "section-break",
            fieldlabel: "Department Clearance",
            fieldname: "",
            fieldtype: "section-break",
            columns: 2,
            placeholder: "",
            required: false,
            hidden: false,
        },
        {
            id: "attach",
            fieldlabel: "Attach Clearance Notes",
            fieldname: "attach",
            fieldtype: "file",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "clearance-data",
            fieldlabel: "Clearance Data",
            fieldname: "clearance_data",
            fieldtype: "table",
            columns: 9,
            placeholder: " ",
            required: false,
            hidden: false,
            fields:[
                {
                    id: "department",
                    fieldlabel: "Department",
                    fieldname: "department",
                    fieldtype: "link",
                    model: "Department",
                    columns: 3,
                    placeholder: " ",
                    required: true,
                    hidden: false,
                },
                {
                    id: "item",
                    fieldlabel: "Item",
                    fieldname: "item",
                    fieldtype: "text",
                    // model: "Department",
                    columns: 3,
                    placeholder: " ",
                    required: true,
                    hidden: false,
                },
                {
                    id: "item-discription",
                    fieldlabel: "Item Description",
                    fieldname: "item_discrition",
                    fieldtype: "text",
                    // model: "Department",
                    columns: 3,
                    placeholder: " ",
                    required: true,
                    hidden: false,
                },
                {
                    id: "hand-in-status",
                    fieldlabel: "Handing Over Status",
                    fieldname: "hand_in_status",
                    fieldtype: "select",
                    // model: "Department",
                    columns: 3,
                    placeholder: " ",
                    required: true,
                    hidden: false,
                    options:["Handed Over", "Pending Hand Over"]
                },
                {
                    id: "hand-in-date",
                    fieldlabel: "Hand in Date",
                    fieldname: "hand_in_date",
                    fieldtype: "date",
                    // model: "Department",
                    columns: 3,
                    placeholder: " ",
                    required: true,
                    hidden: false,
                },
                {
                    id: "remarks",
                    fieldlabel: "Remarks",
                    fieldname: "remark",
                    fieldtype: "expandable",
                    // model: "Department",
                    columns: 3,
                    placeholder: " ",
                    required: true,
                    hidden: false,
                },
            ]
        },
    ],
}