export default {
    setup: {
        new_form_id: 'new-staff-graduate-development-enrollment-requisiton',
        info_form_id: 'staff-graduate-development-enrollment-requisiton-info',
        title: "Graduate Development Enrollment",
        layout_columns: 5,
        model: "Graduate_Development_Enrollment"
    },
    fields: [
        {
            id: "requisitioned-by",
            fieldlabel: "Requisitioned by (Employee No)",
            fieldname: "requisitioned_by",
            fieldtype: "link",
            model: "Employee",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            default: lite?.employee_info?.name,
        },  
        {
            id: "requisitioned-by",
            fieldlabel: "Full Names",
            fieldname: "requisitioned_by_full_name",
            fieldtype: "ready-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            default: lite?.employee_info?.full_name,
            fetchfrom: "requisitioned-by",
            fetchfield: "full_name",
        },   

 
        {
            id:"column-break-001",
            fieldtype: "column-break",
            columns: 1
        }, 
        {
            id: "duration-of-programme",
            fieldlabel: "Duration of programme",
            fieldname: "duration_of_programme",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },   
        {
            id: "budget",
            fieldlabel: "Budget",
            fieldname: "budget",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        }, 
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "link",
            model: "Department",
            columns: 1,
            placeholder: " ",

            required: false,
            hidden: false,
        },   
        {
            id: "section",
            fieldlabel: "Section",
            fieldname: "section",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },  
        {
            id:"column-break-002",
            fieldtype: "column-break",
            columns: 1
        },    
        {
            id: "number-required",
            fieldlabel: "Number Required",
            fieldname: "number_required",
            fieldtype: "int",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },   
        {
            id: "date-required",
            fieldlabel: "Date required",
            fieldname: "date_required",
            fieldtype: "date",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        }, 
        {
            id: "position",
            fieldlabel: "Position",
            fieldname: "position",
            fieldtype: "link",
            model: "Designation",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },   
        {
            id: "grade",
            fieldlabel: "Grade",
            fieldname: "grade",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },   
        {
            id: "number-required",
            fieldlabel: "Number Required",
            fieldname: "number_required",
            fieldtype: "int",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },   
        {
            id: "date-required",
            fieldlabel: "Date required",
            fieldname: "date_required",
            fieldtype: "date",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },   
        {
            id:"column-break-002",
            fieldtype: "column-break",
            columns: 1
        },
        {
            id: "duration-of-programme",
            fieldlabel: "Duration of programme",
            fieldname: "duration_of_programme",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },   
        {
            id: "budget",
            fieldlabel: "Budget",
            fieldname: "budget",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },   
        {
            id: "supervisor-id",
            fieldlabel: "Supervisor's Id",
            fieldname: "supervisor_id",
            fieldtype: "link",
            model: "Employee",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            default: lite?.employee_info?.report_to
        },   
        {
            id: "attach-role-profile",
            fieldlabel: "Attach role profile",
            fieldname: "attach_role_profile",
            fieldtype: "file",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },   
        {
            id: "attach-rotation-plan-and-areas-of-gd",
            fieldlabel: "Attach rotation plan and areas of GD",
            fieldname: "attach_rotation_plan_and_areas_of_gd",
            fieldtype: "file",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
        }, 
        {
            id: "supervisor-id",
            fieldlabel: "Supervisor's employee id",
            fieldname: "supervisor_id",
            fieldtype: "link",
            model: "Employee",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        }, 
        {
            id: "supervisor_fullname",
            fieldlabel: "Supervisor Name",
            fieldname: "supervisor_fullname",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "supervisor-id",
            fetchfield: "full_name",
        },   
        // {
        //     id: "column-break-002",
        //     fieldlabel: "",
        //     fieldname: "",
        //     fieldtype: "column-break",
        //     columns: 1,
        //     placeholder: " ",
        //     required: false,
        //     hidden: false,
        // }, 
        {
            id: "advertisement",
            fieldlabel: "Advertisement",
            fieldname: "advertisement",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            // options: ["Advertisement", "University or College"]
        },          
        {
            id: "university-or-college",
            fieldlabel: "University or College",
            fieldname: "university_or_college",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },  
        // {
        //     id:"column-break-002",
        //     fieldtype: "column-break",
        //     columns: 1
        // },
        //  {
        //     id: "section-break-001",
        //     fieldlabel: "Qualification",
        //     fieldname: "",
        //     fieldtype: "section-break",
        //     columns: 1,
        // },   
        {
            id: "academic",
            fieldlabel: "Academic",
            fieldname: "academic",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },   
        {
            id: "professional",
            fieldlabel: "Professional",
            fieldname: "professional",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },   
        // {
        //     id: "section-break-003",
        //     fieldlabel: "Requisitioned by",
        //     fieldname: "",
        //     fieldtype: "section-break",
        //     columns: 1,
        //     placeholder: " ",
        //     required: false,
        //     hidden: false,
        // },  
        {
            id: "job-title",
            fieldlabel: "Job Title",
            fieldname: "job_title",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
            fetchfrom: "requisitioned-by",
            fetchfield: "designation",
        }, 
    ],
}