export default {
    setup: {
        new_form_id: 'new-staff-id-card',
        info_form_id: 'staff-id-card-info',
        title: "ID Card",
        layout_columns: 3,
        model: "ID_Card",
        allow_submit: true,
        allow_councel: false,
        allow_print: false,
        allow_delete: false,
    },
    fields: [
        {
            id: "officer-id",
            fieldlabel: "Employee No",
            fieldname: "officer_id",
            fieldtype: "link",
            model: "Employee",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            default: lite?.employee_info?.name
        },
        {
            id: "officer-name",
            fieldlabel: "Employee Name",
            fieldname: "officer_name",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Employee Name",
            required: false,
            hidden: false,
            fetchfrom: "officer-id",
            fetchfield: "full_name"
        },
        {
            id: "job-title",
            fieldlabel: "Job Title",
            fieldname: "job_title",
            fieldtype: "link",
            model: "Designation",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "officer-id",
            fetchfield: "designation"
        },
        {
            id: "salary-scale",
            fieldlabel: "Salary Grade",
            fieldname: "salary_scale",
            fieldtype: "link",
            model: "Employee_Grade",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            // fetchfrom: "officer-id",
            // fetchfield: "basic_salary"
        },
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "link",
            model: "Department",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "officer-id",
            fetchfield: "department"
        },
        {
            id: "nrc",
            fieldlabel: "National Registration Card Number",
            fieldname: "nrc",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "officer-id",
            fetchfield: "id_no"
        },
        {
            id: "employee-cover-issues",
            fieldlabel: "The employee will meet the cost for replacement of a lost card",
            fieldname: "card_be_issued",
            fieldtype: "check",
            columns: 1,
            placeholder: "The employee will meet the cost for replacement of a lost card",
            required: true,
            hidden: false,
        },
        {
            id: "as-job-title",
            fieldlabel: "As ",
            fieldname: "as_job_title",
            fieldtype: "link",
            model: "Designation",
            columns: 1,
            placeholder: "Job Title",
            required: false,
            hidden: false,
            displayon: ["a_replacement_card_be_issued", 1]
        },
        {
            id: "on-date",
            fieldlabel: "On",
            fieldname: "on_date",
            fieldtype: "date",
            columns: 1,
            placeholder: "Date",
            required: false,
            hidden: false,
            displayon: ["a_replacement_card_be_issued", 1]
        },
        {
            id: "reason-for-application",
            fieldlabel: "Reason for Application",
            fieldname: "reason_for_application",
            fieldtype: "rich",
            height: "300px",
            columns: 3,
            placeholder: "Enter Reason for Application",
            required: true,
            hidden: false,
        },

    ]
}