;
export default {
    setup: {
        allow_submit: true,
        allow_download: false,
        allow_delete: false,
        allow_cancel: true,
        allow_print: false,
        allow_disable: false,
        new_form_id: 'new-si',
        info_form_id: 'si-info',
        title: "Imprest Retirement",
        layout_columns: 9,
        model: "ECZ_Imprest_Retirement"
    },
    fields: [
        {
            id: "employee-no",
            fieldlabel: "Employee No",
            fieldname: "employee_no",
            fieldtype: "link",
            model: "Employee",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
            default: lite?.employee_info?.name || ""
        },
        {
            id: "surname-name",
            fieldlabel: "Surname Name",
            fieldname: "surname",
            fieldtype: "text",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,
            default: lite?.employee_info?.last_name || ""
        },
        {
            id: "other-no",
            fieldlabel: "Other Name",
            fieldname: "other_name",
            fieldtype: "text",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,
            default: lite?.employee_info?.first_name || "" + lite?.employee_info?.middle_name || ""
        },
        {
            id: "column-break-001",
            fieldlabel: "",
            fieldtype: "column-break",
            columns: 1,
        },
        {
            id: "position",
            fieldlabel: "Position",
            fieldname: "position",
            fieldtype: "link",
            model: "Designation",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            default: lite?.employee_info?.designation || ""
        },
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "link",
            model: "Department",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            default: lite?.employee_info?.department || ""
        },
        {
            id: "section",
            fieldlabel: "Section",
            fieldname: "section",
            fieldtype: "text",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            default: ""
        },
        // {
        //     id: "section",
        //     fieldlabel: "Section",
        //     fieldname: "section",
        //     fieldtype: "text",
        //     columns: 1,
        //     placeholder: "Section",
        //     required: false,
        //     hidden: false,
        //     default: ""
        // },
        {
            id: "imprest",
            fieldlabel: "Imprest of Interest",
            fieldname: "imprest",
            fieldtype: "link",
            model: "ECZ_Imprest",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "column-break-002",
            fieldlabel: "",
            fieldtype: "column-break",
            columns: 1,
        },
        {
            id: "duration-of-tour-from",
            fieldlabel: "Duration of Tour From Date",
            fieldname: "duration_of_tour_from",
            fieldtype: "date",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            default: "",
            fetchfrom: "imprest",
            fetchfield: "duration_from_date",
        },
        {
            id: "duration-of-tour-to",
            fieldlabel: "Duration of Tour to Date",
            fieldname: "duration_of_tour_to",
            fieldtype: "date",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            default: "",
            fetchfrom: "imprest",
            fetchfield: "duration_to_date",
        },
        {
            id: "section-break-001",
            fieldlabel: "",
            fieldtype: "section-break",
        },
        {
            id: "places-visited",
            fieldlabel: "Places Visited",
            fieldname: "places_visited",
            fieldtype: "table",
            model: "Imprests_Places_Visited",
            columns: 4,
            placeholder: " ",
            required: false,
            hidden: false,
            fields:[
                {
                    id: "place",
                    fieldlabel: "Place",
                    fieldname: "place",
                    fieldtype: "text",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    default: ""
                },
            ]
        },
        {
            id: "column-break-003",
            fieldlabel: "",
            fieldtype: "column-break",
        },
        {
            id: "registration-vehicle",
            fieldlabel: "Registration Vehicle",
            fieldname: "registration_vehicle",
            fieldtype: "text",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            default: "",
            fetchfrom: "imprest",
            fetchfield: "registration_number_of_vechile",
        },
        {
            id: "vehicle-model",
            fieldlabel: "Vehicle Make",
            fieldname: "vehicle_model",
            fieldtype: "text",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            default: "",
            fetchfrom: "imprest",
            fetchfield: "vechile_make",
        },
        {
            id: "area-expenses",
            fieldlabel: "Areas of Expense",
            fieldname: "areas_of_expense",
            fieldtype: "table",
            model: "Imprest_Areas_of_Expense",
            columns: 9,
            placeholder: " ",
            required: false,
            hidden: false,
            fields: [
                {
                    id: "subsistance-allowance",
                    fieldlabel: "Subsistance Allowance",
                    fieldname: "subsistance_allowance",
                    fieldtype: "text",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    default: ""
                },                
                {
                    id: "usage-length",
                    fieldlabel: "Usage Length / Nights Spent",
                    fieldname: "usage_length",
                    fieldtype: "float",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    default: 0
                },             
                {
                    id: "unit-price-of-usage",
                    fieldlabel: "Unit Price of Usage / Per Night",
                    fieldname: "unit_price_of_usage",
                    fieldtype: "float",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    default: 0
                },            
                {
                    id: "total-spent",
                    fieldlabel: "Total Spent",
                    fieldname: "total_spent",
                    fieldtype: "read-only",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    default: 0
                },      
                {
                    id: "expense-attachment",
                    fieldlabel: "Expense Attachment",
                    fieldname: "expense_attachment",
                    fieldtype: "file",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    default: ""
                },                
            ]
        }, 
        {
            id: "imprest-obtained",
            fieldlabel: "Imprest Obtained",
            fieldname: "imprest_obtained",
            fieldtype: "read-only",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            default: "",
            fetchfrom: "imprest",
            fetchfield: "approved_amount",
        },   
        {
            id: "pending",
            fieldlabel: "Pending Amount",
            fieldname: "pending",
            fieldtype: "read-only",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            default: 0,
            fetchfrom: "imprest",
            fetchfield: "balance",
        },  
        {
            id: "retired-amount",
            fieldlabel: "Retired Amount",
            fieldname: "retired_amount",
            fieldtype: "read-only",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            default: 0
        },   
        {
            id: "balance-left",
            fieldlabel: "Balance Left",
            fieldname: "balance_left",
            fieldtype: "read-only",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            default: 0
        }, 
    ],
}