import { retire_imprest } from "../../overrides/form/staff/core.js"
export default {
    setup: {
        allow_submit: true,
        allow_download: false,
        allow_delete: false,
        allow_cancel: true,
        allow_print: false,
        allow_disable: false,
        new_form_id: 'new-si',
        info_form_id: 'si-info',
        title: "Imprest",
        layout_columns: 9,
        model: "ECZ_Imprest",
    },
    form_actions: [],
    fields: [
        {
            id: "request_date",
            fieldlabel: "Request Date",
            fieldname: "request_date",
            fieldtype: "date",
            columns: 4,
            placeholder: " ",
            required: true,
            hidden: false,
            default: lite.utils.today()
        },
        {
            id: "column-break-001",
            fieldtype: "column-break",
            columns: 1,
        },
        {
            id: "initiator",
            fieldlabel: "Initiator",
            fieldname: "initiator",
            fieldtype: "read-only",
            columns: 4,
            placeholder: " ",
            required: true,
            hidden: false,   
            default:lite?.employee_info?.name,
        },        
        {
            id: "bank_acc",
            fieldlabel: "Bank Account No",
            fieldname: "bank_acc_no",
            fieldtype: "text",
            columns: 2,
            required: false,
            hidden: false,
            default: lite?.employee_info?.account_no || "",
        },            
        {
            id: "sort_code",
            fieldlabel: "Branch Code",
            fieldname: "sort_code",
            fieldtype: "text",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,     
            fetchfrom:"initiator",
            fetchfield:"sort_code",
            default: lite?.employee_info?.sort_code || ""
        },
        {
            id: "column-break-002",
            fieldtype: "column-break",
            columns: 1,
        },
        {
            id: "recommender",
            fieldlabel: "Recommender",
            fieldname: "recommender",
            fieldtype: "link",
            model:"Employee",
            columns: 4,
            placeholder: " ",
            required: false,
            hidden: true,        
            default:lite?.employee_info?.reports_to,
        },
        {
            id: "initiator-first-name",
            fieldlabel: "Initiator First Name",
            fieldname: "initiator_first_name",
            fieldtype: "read-only",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,   
            default:lite?.employee_info?.first_name,    
        },
        {
            id: "initiator-last-name",
            fieldlabel: "Initiator Last Name",
            fieldname: "initiator_last_name",
            fieldtype: "read-only",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,   
            default:lite?.employee_info?.last_name,    
        },
        {
            id: "job-title",
            fieldlabel: "Job Title",
            fieldname: "job_title",
            fieldtype: "text",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,   
            default: lite?.employee_info?.designation,    
        },
        {
            id: "annual-salary",
            fieldlabel: "Annual Salary",
            fieldname: "annual_salary",
            fieldtype: "currency",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,   
            default: "",    
            default: lite?.employee_info?.basic_pay*12,   
        },
        {
            id: "place_of_visit",
            fieldlabel: "Place of Visit",
            fieldname: "desc",
            fieldtype: "section-break",
            columns: 9,
            required: true,
            hidden: false,
            addborder:true,
            height: 300        
        },

        {
            id: "country",
            fieldlabel: "Country",
            fieldname: "country",
            fieldtype: "link",
            model: "Country",
            columns: 2,
            required: false,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "column-break-003",
            fieldtype: "column-break",
        },
        {
            id: "column-break-004",
            fieldtype: "column-break",
        },
        {
            id: "column-break-005",
            fieldtype: "column-break",
        },
        {
            id: "duration-from-date",
            fieldlabel: "Duration From",
            fieldname: "duration_from_date",
            fieldtype: "date",
            columns: 2,
            required: false,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "duration-to-date",
            fieldlabel: "Duration To",
            fieldname: "duration_to_date",
            fieldtype: "date",
            columns: 2,
            required: false,
            hidden: false,
            placeholder: " ",
        },


        {
        id: "province-visited",
        fieldlabel: "Provinces Visited",
        fieldname: "province_visited",
        fieldtype: "table",
        columns: 4,
        required: true,
        hidden: false,
        fields: [
            {
                id: "province",
                fieldlabel: "Province",
                fieldname: "province",
                fieldtype: "text",
                columns: 4,
                required: false,
                hidden: false,
                addborder:true,
                placeholder: " ",
            },
        ],},
        {
            id: "column-break-006",
            fieldtype: "column-break",
        },
        {
        id: "district-visited",
        fieldlabel: "Districts Visited",
        fieldname: "district_visited",
        fieldtype: "table",
        columns: 4,
        required: true,
        hidden: false,
        fields: [
            {
                id: "district",
                fieldlabel: "District",
                fieldname: "district",
                fieldtype: "text",
                columns: 4,
                required: false,
                hidden: false,
                addborder:true,
                placeholder: " ",
            },
        ],},
        {
            id: "nature-of-offical-duty",
            fieldlabel: "Nature of Offical Duty",
            fieldname: "nature_of_offical_duty",
            fieldtype: "rich",
            columns: 4,
            required: false,
            hidden: false,
            placeholder: " ",
            height: 20,
        },
        
        {
            id: "column-break-007",
            fieldtype: "column-break",
            columns: 1,
        },
        {
            id: "mode-of-travel",
            fieldlabel: "Mode of Travel",
            fieldname: "mode_of_travel",
            fieldtype: "select",
            columns: 4,
            required: false,
            hidden: false,
            placeholder: " ",
            options:[
                "Car",
                "Bus",
                "Truck",
                "Motorcycle",
                "Bicycle",
                "Scooter",
                "Tram/Streetcar",
                "Segway",
                "Skateboard",
                "Train (Passenger & Freight)",
                "Metro/Subway",
                "Ferry",
                "Cruise Ship",
                "Cargo Ship",
                "Yacht",
                "Speedboat",
                "Sailboat",
                "Kayak/Canoe",
                "Submarine",               
                "Hovercraft",
                "Hydrofoil",
                "Air Transportation"
            ]  
        },
        {
            id: "registration-number-of-vechile",
            fieldlabel: "Registration Number of Vehicle",
            fieldname: "registration_number_of_vechile",
            fieldtype: "text",
            columns: 4,
            required: false,
            hidden: false,
            placeholder: " ",
            displayon:["mode-of-travel", "Car", "Motorcycle"]
        },
        
        {
            id: "column-break-008",
            fieldtype: "column-break",
            columns: 1,
        },
        {
            id: "vechile-make",
            fieldlabel: "Vehicle Make",
            fieldname: "vechile_make",
            fieldtype: "text",
            columns: 4,
            required: false,
            hidden: false,
            placeholder: " ",
            displayon:["mode-of-travel", "Car", "Motorcycle"],
        },
        {
            id: "amounts",
            fieldlabel: "Amounts",
            fieldname: "",
            fieldtype: "section-break",
            columns: 4,
            required: false,
            hidden: false,
            addborder:true,
            placeholder: " ",                
        },
        {
            id: "estimated-cost-of-travel",
            fieldlabel: "Estimated Cost of Travel",
            fieldname: "estimated_cost_of_travel",
            fieldtype: "currency",
            columns: 4,
            required: false,
            hidden: false,
            placeholder: " ",
        },

        {
            id: "retirement-item",
            fieldlabel: "Retirement Items",
            fieldname: "retirement_item",
            fieldtype: "table",
            columns: 9,
            required: true,
            hidden: false,
            fields: [
                {
                    id: "item-description",
                    fieldlabel: "Description",
                    fieldname: "description",
                    fieldtype: "text",
                    columns: 4,
                    required: false,
                    hidden: false,
                    addborder:true,
                    placeholder: " ",
                },
                {
                    id: "amounts",
                    fieldlabel: "Amounts",
                    fieldname: "amounts",
                    fieldtype: "text",
                    columns: 4,
                    required: false,
                    hidden: false,
                    addborder:true,
                    placeholder: " ",
                },
            ],
        },
        {
            id: "request_currency",
            fieldlabel: "Request Currency",
            fieldname: "request_currency",
            fieldtype: "link",
            model:"Currency",
            columns: 2,
            required: true,
            hidden: false,
            placeholder: " ",
            default:"0.00",
            default: lite.system_settings?.default_currency,
        },
        {
            id: "requested_amount",
            fieldlabel: "Requested Amount",
            fieldname: "requested_amount",
            fieldtype: "float",
            columns: 2,
            required: true,
            hidden: false,
            placeholder: " ",
            default:"0.00"                
        },
        {
            id: "requested_to_reporting_currency_convertion_rate",
            fieldlabel: "Requested to Reporting Convertion Rate",
            fieldname: "requested_to_reporting_currency_convertion_rate",
            fieldtype: "float",
            columns: 2,
            required: true,
            hidden: true,
            placeholder: " ",
            default:"0.00"                
        },
        
        {
            id: "column-break-001",
            fieldtype: "column-break",
            columns: 1,
        },
        {
            id: "approved_amount",
            fieldlabel: "Approved Amount",
            fieldname: "approved_amount",
            fieldtype: "float",
            columns: 4,
            required: true,
            hidden: false,
            placeholder: " ",
            default:"0.00"         
        },

        {
            id: "company",
            fieldlabel: "Inistitute",
            fieldname: "company",
            fieldtype: "link",
            model: "Company",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: true,  
            fetchfrom:"initiator",
            fetchfield:"company",
            default: lite?.user?.company?.name,
        },

        {
            id: "retired_amount",
            fieldlabel: "Retired Amount",
            fieldname: "retired_amount",
            fieldtype: "read-only",
            columns: 4,
            required: true,
            hidden: true,
            placeholder: " ",
            default:"0.00"                
        },
        {
            id: "column-break-001",
            fieldtype: "column-break",
            columns: 1,
        },
        {
            id: "balance",
            fieldlabel: "Balance",
            fieldname: "balance",
            fieldtype: "read-only",
            columns: 4,
            required: true,
            hidden: true,
            placeholder: " ",
            default:"0.00"                
        },
    ],
}