export default {
    setup: {
        new_form_id: 'new-leave-application',
        info_form_id: 'leave-info',
        title: "Leave Application",
        layout_columns: 12,
        allow_submit: true,
        allow_cancel: true,
        allow_delete: false,
        allow_print: false,
        allow_disable: false,
        allow_sending_mail: false,
        model: "Leave_Application",
    },
    fields: [
        {
            id: "employee",
            fieldlabel: "Employee No",
            fieldname: "employee",
            fieldtype: "read-only",
            columns: 4,
            placeholder: " ",
            required: false,
            hidden: true,
            filters: {
                status: "Active",
            },
            default: lite.employee_info?.name
        },
        {
            id: "employee-name",
            fieldlabel: "Employee Name",
            fieldname: "employee_name",
            fieldtype: "read-only",
            columns: 4,
            placeholder: " ",
            required: false,
            hidden: false,
            default: lite.employee_info?.full_name
        },
        {
            id: "leave_mode",
            fieldlabel: "Select Leave Mode",
            fieldname: "leave_mode",
            fieldtype: "select",
            options: ["Hourly Leave", "Days Leave"],
            placeholder: " ",
            columns: 4,
            required: true,
            hidden: false,
            default: "Days Leave",
        },
        {
            id: "leave_type",
            fieldlabel: "Leave Type",
            fieldname: "leave_type",
            fieldtype: "link",
            model: "Leave_Type",
            columns: 4,
            placeholder: " ",
            required: true,
            hidden: false,
        },


        {
            id: "company",
            fieldlabel: "Company",
            fieldname: "company",
            fieldtype: "read-only",
            columns: 4,
            placeholder: "Company",
            required: false,
            hidden: true,
            fetchfrom:"employee",
            fetchfield: "company",
            default: lite.user.company.name
        },
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "read-only",
            columns: 4,
            placeholder: " ",
            required: false,
            hidden: true,
            default: lite.user.company.department
        },
        {
            id: "attachment",
            fieldlabel: "Attachment",
            fieldname: "attachment",
            fieldtype: "file",
            columns: 4,
            placeholder: " ",
            required: false,
            hidden: false,
            istablefield: true,
        },
    
        {
            id: "details",
            fieldlabel: "Leave Duration",
            fieldname: "ci",
            fieldtype: "section-break",
            addborder: true,
            columns: 4,
            hidden: false,
        },
        {
            id: "from_time",
            fieldlabel: "Select From Time",
            fieldname: "from_time",
            fieldtype: "time",
            columns: 4,
            placeholder: " ",
            required: false,
            hidden: false,
            displayon: ["leave_mode", "Hourly Leave"]
        },
        {
            id: "to_time",
            fieldlabel: "Select to Time",
            fieldname: "to_time",
            fieldtype: "time",
            columns: 4,
            placeholder: " ",
            required: false,
            hidden: false,
            displayon: ["leave_mode", "Hourly Leave"]
        },
        {
            id: "from_date",
            fieldlabel: "From Date",
            fieldname: "from_date",
            fieldtype: "date",
            columns: 4,
            placeholder: " ",
            required: false,
            hidden: false,
            default: lite.utils.today(),
            displayon: ["leave_mode", "Days Leave"]
        },
        {
            id: "to_date",
            fieldlabel: "To Date",
            fieldname: "to_date",
            fieldtype: "date",
            columns: 4,
            placeholder: " ",
            required: true,
            hidden: false,
            default: lite.utils.today(),
            displayon: ["leave_mode", "Days Leave"]
        },
        {
            id: "time_duration_formatted",
            fieldlabel: "Total days",
            fieldname: "time_duration_formatted",
            fieldtype: "read-only",
            placeholder: " ",
            columns: 2,
            required: false,
            hidden: false,
        },

        {
            id: "total_days",
            fieldlabel: "Total Leave Duration",
            fieldname: "total_days",
            fieldtype: "read-only",
            placeholder: " ",
            columns: 2,
            required: false,
            hidden: false,
        },

        {
            id: "hov",
            fieldlabel: "Handovers",
            fieldname: "ci",
            fieldtype: "section-break",
            addborder: true,
            columns: 12,
            hidden: false,
        },
        {
            id: "delegated_officer",
            fieldlabel: "Delegated Officer's No",
            fieldname: "delegated_officer",
            fieldtype: "link",
            model: "Employee",
            linkfield: "name",
            columns: 4,
            placeholder: " ",
            required: true,
            hidden: false,
            filters: {
                status: "Active",
            },
        },
        {
            id: "delegated_officer_name",
            fieldlabel: "Employee Name",
            fieldname: "delegated_officer_name",
            fieldtype: "read-only",
            columns: 4,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom:"delegated_officer",
            fetchfield: "full_name"
        },
        {
            id: "handover_notes",
            fieldlabel: "Handover Notes",
            fieldname: "handover_notes",
            fieldtype: "file",
            columns: 4,
            placeholder: " ",
            required: false,
            hidden: false,
            istablefield: true,
        },
        {
            id: "return_date",
            fieldlabel: "Return Date",
            fieldname: "return_date",
            fieldtype: "date",
            columns: 4,
            placeholder: " ",
            required: false,
            hidden: false,
            default: lite.utils.today(),
            displayon: ["leave_mode", "Days Leave"]
        },
        {
            id: "details",
            fieldlabel: "Reason",
            fieldname: "ci",
            fieldtype: "section-break",
            addborder: true,
            columns: 12,
            hidden: false,
        },
        {
            id: "reason",
            fieldlabel: "Reason",
            fieldname: "reason",
            fieldtype: "longtext",
            classnames: "h-[200px]",
            columns: 12,
            required: true,
            hidden: false,
        },
    ],
}