export default {
    setup: {
        new_form_id: 'new-lts',
        info_form_id: 'lts-info',
        title: "Long Term Sponsorship",
        layout_columns: 4,
        allow_submit: true,
        model: "Long_Term_Sponsorship"
    },
    
    fields: [
        {
            id: "employee",
            fieldlabel: "Select Employee No",
            fieldname: "employee",
            fieldtype: "link",
            model: "Employee",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "last_name",
            fieldlabel: "Last Name",
            fieldname: "last_name",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "first_name"
        },
        {
            id: "basic_pay",
            fieldlabel: "Basic Pay",
            fieldname: "basic_pay",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
            fetchfrom: "employee",
            fetchfield: "basic_pay"
        },
        
        {
            id: "first_name",
            fieldlabel: "First Name",
            fieldname: "first_name",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "first_name"
        },
        {
            id: "middle_name",
            fieldlabel: "Other Names",
            fieldname: "middle_name",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "middle_name"
        },
        {
            id: "designation",
            fieldlabel: "Job Title",
            fieldname: "designation",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "designation"
        },
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "department"
        },
        {
            id: "salary_grade",
            fieldlabel: "Salary Grade",
            fieldname: "salary_grade",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "employee_grade"
        },
        {
            id: "type_of_advance",
            fieldlabel: "Advance Type",
            fieldname: "type_of_advance",
            fieldtype: "link",
            model: "Salary_Advance_Configuration",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
           
        },
        {
            id: "age",
            fieldlabel: "Age",
            fieldname: "age",
            fieldtype: "int",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "age"
        },
        {
            id: "end_of_contract",
            fieldlabel: "End of Contract Or Retirement",
            fieldname: "end_of_contract",
            fieldtype: "date",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "end_of_contract"
        },
        {
            id: "deduction_type",
            fieldlabel: "Deduction Type",
            fieldname: "deduction_type",
            fieldtype: "read-only",
            // fieldtype: "link",
            model: "Salary_Advance_Configuration",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
            default: "Long Term Sponsorship",
        },
        {
            id: "ssddd",
            fieldlabel: "Details Supporting Your Application",
            fieldname: "ssddd",
            fieldtype: "section-break",
            columns: 1,
            placeholder: " ",
        },
        {
            id: "course_of_study",
            fieldlabel: "Course of Study",
            fieldname: "course_of_study",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "mode_of_study",
            fieldlabel: "Mode of Study",
            fieldname: "mode_of_study",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "course_duration",
            fieldlabel: "Course Duration",
            fieldname: "course_duration",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "institution",
            fieldlabel: "Institution",
            fieldname: "institution",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "qualification_to_be_obtained",
            fieldlabel: "Name of Qualification to Be Obtained",
            fieldname: "qualification_to_be_obtained",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "reason",
            fieldlabel: "Reason For The Course",
            fieldname: "reason",
            fieldtype: "rich",
            columns: 4,
            height: 250,
            placeholder: " ",
            required: false,
            hidden: false,
        },

        {
            id: "current_responsibilities",
            fieldlabel: "Current Job Responsibilities",
            fieldname: "current_responsibilities",
            fieldtype: "rich",
            height: 250,
            columns: 4,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "current_highest_qualification",
            fieldlabel: "Your Highest Qualification",
            fieldname: "current_highest_qualification",
            fieldtype: "file",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "hfhhf",
            fieldlabel: "Training Costs Involved",
            fieldname: "hfhhf",
            fieldtype: "section-break",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "boarding_and_lodging",
            fieldlabel: "Boarding And Lodging",
            fieldname: "boarding_and_lodging",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "travel_costs",
            fieldlabel: "Travel Costs",
            fieldname: "travel_costs",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "lunch_allowance",
            fieldlabel: "Lunch Allowance",
            fieldname: "lunch_allowance",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "books_allowance",
            fieldlabel: "Books Allowance",
            fieldname: "books_allowance",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "tuition_fees",
            fieldlabel: "Tuition Fees",
            fieldname: "tuition_fees",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
    ],
}