const ss = await lite.connect.get_system_settings()

export default {
    setup: {
        new_form_id: 'new-staff-welfare',
        info_form_id: 'staff-welfare-info',
        title: "Recovery Of (50%) Medical Bills",
        layout_columns: 3,
        model: "Employee_Welfare",
        allow_submit: true,
    },
    fields: [

        {
            id: "column-break-2",
            fieldlabel: "Employee Details",
            fieldname: "ddd",
            fieldtype: "section-break",
            required: false,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "employee",
            fieldlabel: "Employee No",
            fieldname: "employee",
            fieldtype: "link",
            model: "Employee",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            default: lite?.employee_info?.name,
            filters: {
                status: "Active",
            }, 
        }, 
        {
            id: "employee_name",
            fieldlabel: "Employee Name",
            fieldname: "employee_name",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom:"employee",
            fetchfield: "full_name",
        },
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom:"employee",
            fetchfield: "department"
        }, 
        {
            id: "designation",
            fieldlabel: "Job Title",
            fieldname: "designation",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom:"employee",
            fetchfield: "designation"
        }, 
        {
            id: "section-break",
            fieldlabel: "Cost Distribution",
            fieldname: "section-break",
            fieldtype: "section-break",
            columns: 1,
            placeholder: " ",
        }, 
        {
            id: "welfare_type",
            fieldlabel: "Welfare Type",
            fieldname: "welfare_type",
            fieldtype: "link",
            model: "Welfare_Type",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        }, 
        {
            id: "welfare-expense",
            fieldlabel: "Welfare Expense",
            fieldname: "welfare_expense",
            fieldtype: "currency",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        }, 
        {
            id: "company-covered-expense",
            fieldlabel: "Council Covered Expense",
            fieldname: "company_covered_expense",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        }, 
        {
            id: "staff-covered-expense",
            fieldlabel: "Staff Covered Expense",
            fieldname: "staff_covered_expense",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "attach_receipt",
            fieldlabel: "Attach Receipt",
            fieldname: "attach_receipt",
            fieldtype: "file",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            displayon: ["payment_method", "Cash"]
        },
        // {
        //     id: "section-break",
        //     fieldlabel: "Pay Back Duration Limit",
        //     fieldname: "",
        //     fieldtype: "section-break",
        //     columns: 1, 
        //     required: false,
        //     hidden: false,
        //     placeholder: "",
        // },
        {
            id: "limit-unit",
            fieldlabel: "Limit Unit",
            fieldname: "limit_unit",
            fieldtype: "read-only",
            columns: 1, 
            required: false,
            hidden: false,
            placeholder: "Pick Limit Unit",
            fetchfrom: "welfare_type",
            fetchfield: "limit_unit",
            displayon: ["docstatus", 0],
        },
        {
            id: "limit-qty",
            fieldlabel: "Repayment Period",
            fieldname: "limit_qty",
            fieldtype: "read-only",
            columns: 1, 
            required: false,
            hidden: false,
            placeholder: " ",
            default: "1",
            fetchfrom: "welfare_type",
            fetchfield: "limit_qty",
            displayon: ["docstatus", 0],
        },
        // {
        //     id: "column-break-1",
        //     fieldlabel: "Pay Back Duration",
        //     fieldname: "",
        //     fieldtype: "column-break",
        //     columns: 1, 
        //     required: false,
        //     hidden: false,
        //     placeholder: "",
        // },
        
        {
            id: "payment_method",
            fieldlabel: "Payment Method",
            fieldname: "payment_method",
            fieldtype: "select",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            default: "Payroll",
            options: [
                "Payroll",
                "Cash",
            ]
        }, 
        {
            id: "payment-length-unit",
            fieldlabel: "Payment Period",
            fieldname: "pay_length_unit",
            fieldtype: "select",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
            fetchfrom: "welfare_type",
            fetchfield: "limit_unit",
            options: [
                "Day",
                "Week",
                "Months",
                "Year",
            ]
        }, 
        {
            id: "payment-length",
            fieldlabel: "Payment Period",
            fieldname: "payment_length",
            fieldtype: "int",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            default: "1",
            fetchfrom: "welfare_type",
            fetchfield: "limit_qty",
        }, 
    ],
}