export default {
    setup: {
        new_form_id: 'new-staff-memo',
        info_form_id: 'staff-memo-info',
        title: "Memo",
        layout_columns: 3,
        model: "Memo",
        allow_delete: false,
        allow_disable: false,
    },
    fields: [
        {
            id: "name",
            fieldlabel: "Memo Name",
            fieldname: "name",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        // {
        //     id: "to",
        //     fieldlabel: "To",
        //     fieldname: "to",
        //     fieldtype: "read-only",
        //     columns: 1,
        //     placeholder: "",
        //     required: true,
        //     hidden: false,
        // },
       
        {
            id: "from",
            fieldlabel: "From",
            fieldname: "sender",
            fieldtype: "read-only",
            columns: 1,
            required: false,
            hidden: false,
        },
        {
            id: "date",
            fieldlabel: "Date",
            fieldname: "date",
            fieldtype: "date",
            columns: 1,
            required: false,
            placeholder: " ",
            hidden: false,
        },
    
       
        {
            id: "subject",
            fieldlabel: "Subject",
            fieldname: "subject",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "memo-id",
            fieldlabel: "",
            fieldname: "si",
            fieldtype: "section-break",
            addborder: true,
            columns: 1,
            required: false,
            hidden: false,
        },
        {
            id: "attachment",
            fieldlabel: "Attachment",
            fieldname: "attachment",
            fieldtype: "file",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
        },

        {
            id: "body",
            fieldlabel: "Body",
            fieldname: "body",
            fieldtype: "rich",
            classnames: "h-[300px]",
            columns: 3,
            placeholder: " ",
            required: false,
            hidden: false,
        },
    
        {
            id: "salary-info",
            fieldlabel: "",
            fieldname: "si",
            fieldtype: "section-break",
            addborder: false,
            columns: 1,
            required: false,
            hidden: false,
        },
     
      
    ],
}