
export default {
    setup: {
        new_form_id: 'new-staff-oath-affirmation-of-secrecy',
        info_form_id: 'staff-oath-affirmation-of-secrecy-info',
        title: "Oath */ Affirmation of Secrecy",
        layout_columns: 6,
        model: "Oath_Affirmation"
    },
    fields:[
        {
            id: "employee-id",
            fieldlabel: "Employee No",
            fieldname: "empolyee_id",
            fieldtype: "link",
            model: "Employee",
            columns: 2,
            required: true,
            hidden: false,
            placeholder: " ",
            default: lite.employee_info.name,
        },
        {
            id: "employee-name",
            fieldlabel: "Employee Name",
            fieldname: "employee_name",
            fieldtype: "read-only",
            columns: 2,
            required: false,
            hidden: false,
            placeholder: "Employee Name",
            default:" ",
            fetchfrom: "employee-id",
            fetchfield: "full_name",
        },
        {
            id: "new-position",
            fieldlabel: "New Position",
            fieldname: "new_position",
            fieldtype: "link",
            model: "Designation",
            columns: 2,
            required: false,
            hidden: false,
            placeholder: " ",
            fetchfrom: "employee-id",
            fetchfield: "designation",
        },
        {
            id: "sworn-delcared-by-section",
            fieldlabel: "Sworn / Declared By",
            fieldname: "",
            fieldtype: "section-break",
        },
        {
            id: "sworn-declared-by",
            fieldlabel: "Sworn/Declared by",
            fieldname: "sworn_by",
            fieldtype: "link",
            model: "Employee",
            columns: 2,
            required: true,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "declarer-name",
            fieldlabel: "Declarer's Name",
            fieldname: "declarer_name",
            fieldtype: "read-only",
            columns: 2,
            required: false,
            hidden: false,
            placeholder: " ",
            fetchfrom: "sworn-declared-by",
            fetchfield: "full_name",
            // default: lite?.user?.company?.reporting_currency
        },
        {
            id: "sworn-declared-time-",
            fieldlabel: "Sworn/Declared time",
            fieldname: "sworn_in_time",
            fieldtype: "time",
            columns: 2,
            required: true,
            hidden: false,
            placeholder: "Select an Time",
            default:""
        },
        {
            id: "sworn-declared-day-",
            fieldlabel: "Sworn/Declared Day",
            fieldname: "sworn_in_day",
            fieldtype: "select",
            columns: 2,
            required: true,
            hidden: false,
            placeholder: "Select an Time",
            default:" ",
            options: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
        },
        {
            id: "sworn-declared-date-",
            fieldlabel: "Sworn/Declared Date",
            fieldname: "sworn_in_date",
            fieldtype: "date",
            columns: 2,
            required: true,
            hidden: false,
            placeholder: " ",
            default:""
        },
        {
            id: "witness-id",
            fieldlabel: "witness's id",
            fieldname: "witness_id",
            fieldtype: "link",
            model: "Employee",
            columns: 2,
            required: true,
            hidden: false,
            placeholder: " ",
            // default: lite?.user?.company?.reporting_currency
        },
        {
            id: "witness-name",
            fieldlabel: "Witness's Name",
            fieldname: "witness_name",
            fieldtype: "read-only",
            columns: 2,
            required: false,
            hidden: false,
            placeholder: " ",
            fetchfrom: "witness-id",
            fetchfield: "full_name",
            // default: lite?.user?.company?.reporting_currency
        },
    ]
}