export default {
    setup: {
        new_form_id: 'new-pla',
        info_form_id: 'pla-info',
        title: "Personal Loan Application",
        layout_columns: 3,
        model: "Personal_Loan_Application"
    },
    fields: [
        {
            id: "employee",
            fieldlabel: "Employee No",
            fieldname: "employee",
            fieldtype: "link",
            model: "Employee",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            default:lite?.employee_info?.name,
        },


        {
            id: "department",
            fieldlabel: "Department",
            fieldname: "department",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "department",
            default:lite?.employee_info?.department,
        },
        {
            id: "designation",
            fieldlabel: "Job Title",
            fieldname: "designation",
            fieldtype: "read-only",
            model: "Designation",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "designation",
            default:lite?.employee_info?.designation,
        },
        {
            id: "current_basic_pay",
            fieldlabel: "Basic Pay Per Annum",
            fieldname: "current_basic_pay",
            fieldtype: "read-only",
            model: "Designation",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "basic_pay",
            default:lite?.employee_info?.basic_pay,
        },
        {
            id: "section-break",
            fieldlabel: "Service Condition",
            fieldtype: "section-break",
            columns: 1,
            required: true,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "on_permanent_and_pensionable",
            fieldlabel: "On Permanent & Pensionable",
            fieldname: "on_permanent_and_pensionable",
            fieldtype: "check",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "on_fix_and_pensionable",
            fieldlabel: "On Permanent & Pensionable",
            fieldname: "on_fix_and_pensionable",
            fieldtype: "check",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "on_secondment",
            fieldlabel: "On Secondment",
            fieldname: "on_secondment",
            fieldtype: "check",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "contract_expiration_date",
            fieldlabel: "Contract Expiration Date",
            fieldname: "contract_expiration_date",
            fieldtype: "date",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            fetchfrom: "employee",
            fetchfield: "end_of_contract",
            displayon: ["on_fix_and_pensionable", 1]
        },

        {
            id: "contract_retirement_date",
            fieldlabel: "Retirement Date",
            fieldname: "contract_retirement_date",
            fieldtype: "date",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            fetchfrom: "employee",
            fetchfield: "end_of_retirement",
            displayon: ["on_permanent_and_pensionable", 1]
        },


        {
            id: "secondment_expiration_date",
            fieldlabel: "Secondment Expiration Date",
            fieldname: "secondment_expiration_date",
            fieldtype: "date",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            fetchfrom: "employee",
            fetchfield: "end_of_secondment",
            displayon: ["on_secondment", 1]
        },

        {
            id: "section-break",
            fieldlabel: "Loan Amount",
            fieldtype: "section-break",
            columns: 1,
            required: true,
            hidden: false,
            placeholder: " ",
        },

        {
            id: "loan_amount",
            fieldlabel: "Loan Amount",
            fieldname: "loan_amount",
            fieldtype: "int",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "loan_amount_in_words",
            fieldlabel: "Loan Amount In Words",
            fieldname: "loan_amount_in_words",
            fieldtype: "int",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "recovery_period",
            fieldlabel: "Recovery Period (Month)",
            fieldname: "recovery_period",
            fieldtype: "select",
            options: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36],
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            fetchfrom: "employee",
            fetchfield: "end_of_contract",
            displayon: ["on_fix_and_pensionable", 1]
        },
    ],
}