
export default {
    setup: {
        allow_submit: true,
        allow_download: true,
        allow_delete: false,
        allow_cancel: true,
        allow_print: true,
        allow_update: true,
        new_form_id: 'staff-petty-cash-form',
        info_form_id: 'staff-petty-cash-info',
        title: "Petty Cash",
        layout_columns: 9,
        model: "ECZ_Petty_Cash"
    },
    form_actions: [],
    fields: [
        {
            id: "request_date",
            fieldlabel: "Request Date",
            fieldname: "request_date",
            fieldtype: "date",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,
            default: lite.utils.today()
        },   
        {
            id: "initiator",
            fieldlabel: "Initiator",
            fieldname: "initiator",
            fieldtype: "link",
            model:"Employee",
            columns: 4,
            placeholder: " ",
            required: true,
            hidden: true,   
            default:lite?.employee_info?.name,
        },     
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "read-only",
            columns: 2,
            required: false,
            hidden: false,
            fetchfrom:"initiator",
            fetchfield:"department",
        },
        {
            id: "column-break-001",
            fieldtype: "column-break",
            columns: 1,
        },
        {
            id: "initiator-first-name",
            fieldlabel: "Initiator First Name",
            fieldname: "initiator_first_name",
            fieldtype: "read-only",
            columns: 2,
            placeholder: " ",
            required: true,
            hidden: false,   
            fetchfrom:"initiator",
            fetchfield:"first_name",
            default:lite?.employee_info?.first_name,
        },
        {
            id: "initiator-last-name",
            fieldlabel: "Initiator Last Name",
            fieldname: "initiator_last_name",
            fieldtype: "read-only",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,   
            fetchfrom:"initiator",
            fetchfield:"last_name",
            default:lite?.employee_info?.last_name, 
        },
        
        // {
        //     id: "column-break-001",
        //     fieldtype: "column-break",
        //     columns: 1,
        // },


        {
            id: "attachments",
            fieldlabel: "Attachments",
            fieldname: "attachments",
            fieldtype: "file",
            columns: 2,
            required: false,
            hidden: false,
        },
        {
            id: "column-break-002",
            fieldtype: "column-break",
            columns: 1,
        },
        {
            id: "column-break-003",
            fieldtype: "column-break",
            columns: 1,
        },
        {
            id: "column-break-005",
            fieldtype: "column-break",
            columns: 1,
        },
        
        {
            id: "request_currency",
            fieldlabel: "Request Currency",
            fieldname: "request_currency",
            fieldtype: "link",
            model:"Currency",
            columns: 2,
            required: true,
            hidden: false,
            placeholder: " ",
            default: lite.system_settings?.default_currency,
        },
        {
            id: "requested_amount",
            fieldlabel: "Amount applied for K",
            fieldname: "requested_amount",
            fieldtype: "float",
            columns: 2,
            required: true,
            hidden: false,
            placeholder: " ",
            default:"0.00"                
        },
        {
            id: "requested_amount",
            fieldlabel: "Amount in words",
            fieldname: "requested_amount_in_word",
            fieldtype: "text",
            columns: 2,
            required: false,
            hidden: false,
            placeholder: " ",
            default:""                
        },
        {
            id: "column-break-001",
            fieldtype: "column-break",
            columns: 1,
        },
        {
            id: "reporting_currency",
            fieldlabel: "Reporting Currency",
            fieldname: "reporting_currency",
            fieldtype: "read-only",
            columns: 2,
            required: false,
            hidden: true,
            placeholder: " ",
            default:lite.defaults?.currency?.symbol
        },
        
        {
            id: "description",
            fieldlabel: "Petty Cash Description",
            fieldname: "desc",
            fieldtype: "section-break",
            columns: 9,
            required: true,
            hidden: false,
            addborder:true,      
        },
        {
            id: "purpose",
            fieldlabel: "Purpose",
            fieldname: "purpose",
            fieldtype: "rich",
            columns: 9,
            required: true,
            hidden: false,
            placeholder: " ",
            height:150,
            classnames:"h-[200px]"   
        },
    ],
}