export default {
    setup: {
        new_form_id: 'new-staff-membership-subscription',
        info_form_id: 'staff-membership-subscription-info',
        title: "Membership Subscription",
        layout_columns: 4,
        model: "Membership_Subscription",
        allow_submit: true,
        allow_councel: false,
        allow_print: false,
        allow_delete: false,
    },
    fields: [
        {
            id: "employee_id",
            fieldlabel: "Employee No",
            fieldname: "employee_id",
            fieldtype: "link",
            model: "Employee",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            default: lite?.employee_info?.name,
        },
        {
            id: "employee-name",
            fieldlabel: "Employee Name",
            fieldname: "employee_name",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee_id",
            fetchfield: "full_name",
        },
        {
            id: "job-title",
            fieldlabel: "Job Title",
            fieldname: "job_title",
            fieldtype: "link",
            model: "Designation",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee_id",
            fetchfield: "designation",
        },
        {
            id: "salary-scale",
            fieldlabel: "Salary Grade",
            fieldname: "salary_scale",
            fieldtype: "link",
            model: "Employee_Grade",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee_id",
            fetchfield: "employee_grade",
        },
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "link",
            model: "Department",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee_id",
            fetchfield: "department",
        },
        {
            id: "section",
            fieldlabel: "Section",
            fieldname: "section",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "requested-amount",
            fieldlabel: "Requested Amount",
            fieldname: "requested_amount",
            fieldtype: "float",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            default: "0.00"
        },
        {
            id: "amount-in-words",
            fieldlabel: "Amount in Words",
            fieldname: "amount_in_words",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "nrc",
            fieldlabel: "National Registration Number",
            fieldname: "nrc",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "employee_id",
            fetchfield: "id_no",
        },
        {
            id: "professional-body",
            fieldlabel: "Name of Professional Body",
            fieldname: "professional_body",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "membership-type",
            fieldlabel: "Membership Type",
            fieldname: "membership_type",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "section-break-001",
            fieldlabel: "Bank Details Professional Body",
            fieldtype: "section-break"
        },
        
        {
            id: "account-name",
            fieldlabel: "Bank Account Name",
            fieldname: "account_name",
            fieldtype: "text",
            // model: "Bank_Account",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "account-number",
            fieldlabel: "Account Number",
            fieldname: "account_number",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "branch-code",
            fieldlabel: "Branch Name/Code",
            fieldname: "branch_code",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "sort-code",
            fieldlabel: "Sort Code",
            fieldname: "sort_code",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "section-break-001",
            fieldlabel: "Consent of Repayment",
            fieldtype: "section-break"
        },
        {
            id: "invoice-number",
            fieldlabel: "Invoice Number",
            fieldname: "invoice_number",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "subscrition-attachment",
            fieldlabel: "Attach Origin Invoice",
            fieldname: "subscrition_attachment",
            fieldtype: "file",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },  
        {
            id: "instalments_period",
            fieldlabel: "Instalments Period",
            fieldname: "instalments_period",
            fieldtype: "select",
            options: [1,2,3,4,5,6],
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "submittion-date",
            fieldlabel: "Submission Date",
            fieldname: "submittion_date",
            fieldtype: "date",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "subscrition-attachment",
            fieldlabel: "Attachments",
            fieldname: "subscrition_attachment",
            fieldtype: "file",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "section-break-001",
            fieldlabel: "I consent that the amount applied for should be deducted from my salary in the indicated period",
            fieldtype: "section-break"
        },
    ]
}