;;
export default {
    setup: {
        new_form_id: 'new-staff-employee-seperation',
        info_form_id: 'staff-employee-seperation-info',
        title: "Separation",
        layout_columns: 3,
        model: "Employee_Seperation",
        allow_submit: true,
        allow_cancel: true,
        allow_delete: false,
        allow_print: false,
        allow_sending_mail: false,
        allow_disable: false,
    },
    fields: [
        {
            id: "name",
            fieldlabel: "name ",
            fieldname: "name",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: true,
        },
        {
            id: "separation_type",
            fieldlabel: "Type of Separation",
            fieldname: "separation_type",
            fieldtype: "select",
            options: [
                "Resignation",
                "Early Retirement",
                "Retirement",
                "Abolition of Office",
                "Mutual Separation",
            ],
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            default: "Resignation",
        },
        {
            id: "employee",
            fieldlabel: "Employee ",
            fieldname: "employee",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            default: lite?.employee_info?.name,
        },
        {
            id: "employee-name",
            fieldlabel: "Employee Names",
            fieldname: "employee_name",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            default: lite?.employee_info?.full_name,
        },
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "link",
            model: "Department",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            default: lite?.employee_info?.department,
        },
        {
            id: "designation",
            fieldlabel: "Job Title",
            fieldname: "designation",
            fieldtype: "link",
            model: "Designation",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            default: lite?.employee_info?.designation,
        },
        // {
        //     id: "handover_notes",
        //     fieldlabel: "Attach Handover Notes",
        //     fieldname: "handover_notes",
        //     fieldtype: "file",
        //     columns: 1,
        //     placeholder: "Attach Handover Notes",
        //     required: true,
        //     hidden: false,
        //     value: lite.utils.today(),
        // },
        {
            id: "resignation-date",
            fieldlabel: "Date of Separation",
            fieldname: "resignation_date",
            fieldtype: "date",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            value: lite.utils.today()
        },
        {
            id: "reports-to",
            fieldlabel: "Reports To",
            fieldname: "reports_to",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom:"employee",
            fetchfield: "report_to"
        },
        {
            id: "notice-period",
            fieldlabel: "Notice Period of last days of work",
            fieldname: "notice_period",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
    
        // {
        //     id: "sec",
        //     fieldlabel: "Separation Activities",
        //     fieldname: "sec",
        //     fieldtype: "section-break",
        //     columns: 1,
        //     addborder: true,
        //     required: false,
        //     hidden: false,
        // },
    ],
}