export default {
    setup: {
        new_form_id: 'new-skills-gap',
        info_form_id: 'skills-gap-info',
        title: "Skills Gap",
        layout_columns: 9,
        allow_submit: true,
        allow_update: true,
        allow_delete:  true,
        allow_cancel: true,
        model: "Skill_Gap"
    },
    fields: [
        {
            id: "skills-gap",
            fieldlabel: "Skill Gap",
            fieldname: "name",
            fieldtype: "text",
            columns: 2,
            placeholder: "Enter Skill Gap",
            required: false,
            hidden: true,
        },
        {
            id: "initiator",
            fieldlabel: "Initiator",
            fieldname: "initiator",
            fieldtype: "link",
            model:"Lite_User",
            columns: 5,
            required: false,
            hidden: true,
            placeholder: " ",
            default: lite?.user?.name,
        },
        {
            id: "initiator",
            fieldlabel: "Initiator's Full Name",
            fieldname: "full_name",
            fieldtype: "link",
            model:"Lite_User",
            columns: 5,
            required: false,
            hidden: true,
            placeholder: " ",
            default: lite?.employee_info?.first_name +" "+lite?.employee_info?.last_name,
        },
        {
            id: "skill",
            fieldlabel: "Skill",
            fieldname: "skill",
            fieldtype: "link",
            model:"Skills",
            columns: 2,
            required: false,
            hidden: false,
            placeholder: " ",
            default:"",
            // filters: {
            //     "type": "Skill",
            // }
        },
        {
            id: "training-program",
            fieldlabel: "Training Program",
            fieldname: "training_program",
            fieldtype: "link",
            model:"Training_Program",
            columns: 2,
            required: false,
            hidden: false,
            placeholder: " ",
            default: "",
        },
        {
            id: "section-break-001",
            fieldlabel: "",
            fieldtype: "section-break",
            placeholder: "",
        },
        {
            id: "employees-lacking-the-skill",
            fieldlabel: "Employees Needing the Skill",
            fieldname: "employees_lacking_the_skill",
            fieldtype: "table",
            columns: 9,
            model:"Employees_Lacking_Skill",
            required: false,
            hidden: false,
            placeholder: " ",
            fields:[
                {
                    id: "employee",
                    fieldlabel:  "Employee No",
                    fieldname: "employee",
                    fieldtype: "link",
                    model:"Employee",
                    columns: 5,
                    required: false,
                    hidden: false,
                    placeholder: " ",
                    default:0,
                },
                {
                    id: "employee-full-name",
                    fieldlabel: "Employee's Full Name",
                    fieldname: "employee_full_name",
                    fieldtype: "read-only",
                    columns: 5,
                    required: false,
                    hidden: false,
                    placeholder: " ",
                    default:0,
                    fetchfrom: "employee",
                    fetchfield: "full_name",
                },
            ]
        },
    ],
}