;
export default {
    setup: {
        new_form_id: 'new-staff-house-loan-application',
        info_form_id: 'house-staff-loan-application-info',
        title: "House Loan Application",
        layout_columns: 3,
        allow_submit: true,
        model: "House_Loan_Application"
    },
    fields: [

        {
            id: "deduction_type",
            fieldlabel: "Deduction Type",
            fieldname: "deduction_type",
            fieldtype: "read-only",
            // fieldtype: "link",
            model: "Salary_Advance_Configuration",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
            default: "Long Term Sponsorship",
        },
        {
            id: "employee",
            fieldlabel: "Employee No",
            fieldname: "employee",
            fieldtype: "read-only",
            model: "Employee",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            default: lite.employee_info?.name,
        },
        {
            id: "full_name",
            fieldlabel: "Full Names",
            fieldname: "full_name",
            fieldtype: "read-only",
            columns: 1,
            required: true,
            hidden: false,
            placeholder: " ",
            default: lite.employee_info?.full_name,
        },
        {
            id: "nrc",
            fieldlabel: "NRC/ID",
            fieldname: "nrc",
            fieldtype: "read-only",
            columns: 1,
            required: false,
            hidden: true,
            placeholder: " ",
            default: lite.employee_info?.id_no,
            
        },
        {
            id: "date_of_birth",
            fieldlabel: "Date of Birth",
            fieldname: "date_of_birth",
            fieldtype: "date",
            columns: 1,
            required: false,
            hidden: false,
            default: lite.employee_info?.d_o_b,
        },
        {
            id: "employee_no",
            fieldlabel: "Employee Number",
            fieldname: "employee_no",
            fieldtype: "read-only",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            default: lite.employee_info?.name,
        },
        {
            id: "substantive_appointment",
            fieldlabel: "Substantive Appointment",
            fieldname: "substantive_appointment",
            fieldtype: "text",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            fetchfrom: "full_name",
            fetchfield: "substantive_appointment",
        },
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "read-only",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            default: lite.employee_info?.department,
        },
        {
            id: "date_of_engagement",
            fieldlabel: "Date of Engagement",
            fieldname: "date_of_engagement",
            fieldtype: "date",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            default: "",
        },
        {
            id: "section-break",
            fieldlabel: "Service Condition",
            fieldtype: "section-break",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: "",
        },
        {
            id: "on_permanent_and_pensionable",
            fieldlabel: "On Permanent & Pensionable",
            fieldname: "on_permanent_and_pensionable",
            fieldtype: "check",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "on_secondment",
            fieldlabel: "On Secondment",
            fieldname: "on_secondment",
            fieldtype: "check",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "contract_expiration_date",
            fieldlabel: "Contract Expiration Date",
            fieldname: "contract_expiration_date",
            fieldtype: "date",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            default: "",
        },
        {
            id: "section-break",
            fieldlabel: "Attachments",
            fieldtype: "section-break",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: "",
        },
        {
            id: "skeched_building_plan",
            fieldlabel: "Sketched Building Plan",
            fieldname: "skeched_building_plan",
            fieldtype: "file",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "approved_house_plan",
            fieldlabel: "Approved House Plan",
            fieldname: "approved_house_plan",
            fieldtype: "file",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "proof_of_ownership",
            fieldlabel: "Proof of Ownership",
            fieldname: "proof_of_ownership",
            fieldtype: "file",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "letter_of_sale",
            fieldlabel: "Letter of Sales",
            fieldname: "letter_of_sale",
            fieldtype: "file",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "caveat-agreement",
            fieldlabel: "Caveat Agreement",
            fieldname: "caveat_agreement",
            fieldtype: "file",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
        },
    ],
}