const employee_info = await lite.connect.get_system_settings()
export default {
    setup: {
        new_form_id: 'new-staff-commutation',
        info_form_id: 'staff-leave-commutation-info',
        title: "Leave Commutation",
        layout_columns: 12,
        allow_submit: true,
        allow_cancel: true,
        allow_delete: false,
        allow_print: false,
        allow_sending_mail: false,
        model: "Leave_Commutation",
    },
    fields: [
        {
            id: "employee",
            fieldlabel: "Employee No",
            fieldname: "employee",
            fieldtype: "link",
            model: "Employee",
            linkfield: "name",
            columns: 4,
            placeholder: " ",
            required: true,
            hidden: false,
            filters: {
                status: "Active",
            },
            default: lite.employee_info?.name,
        },
        {
            id: "employee-name",
            fieldlabel: "Employee Name",
            fieldname: "fullname",
            fieldtype: "text",
            columns: 4,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom:"employee",
            fetchfield: "full_name"
        },
        {
            id: "basic_pay",
            fieldlabel: "Basic Pay",
            fieldname: "basic_pay",
            fieldtype: "text",
            columns: 4,
            placeholder: " ",
            required: false,
            hidden: true,
            fetchfrom:"employee",
            fetchfield: "basic_pay"
        },
        {
            id: "working_days",
            fieldlabel: "Working Days",
            fieldname: "working_days",
            fieldtype: "text",
            columns: 4,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom:"employee",
            fetchfield: "working_days"
        },
        {
            id: "leave_type",
            fieldlabel: "Leave Type",
            fieldname: "leave_type",
            fieldtype: "link",
            model: "Leave_Type",
            columns: 4,
            placeholder: " ",
            required: false,
            hidden: false,
            filters: {
                is_commutable: 1,
            },
        },
        {
            id: "commutable_days",
            fieldlabel: "Commutable Days",
            fieldname: "commutable_days",
            fieldtype: "read-only",
            columns: 4,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom:"leave_type",
            fetchfield: "maximum_commutable_days"
        },
        {
            id: "commutated_days",
            fieldlabel: "Commutated Leave Days",
            fieldname: "commutated_days",
            fieldtype: "float",
            columns: 4,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "amount",
            fieldlabel: "Ammount",
            fieldname: "amount",
            fieldtype: "read-only",
            columns: 4,
            placeholder: " ",
            required: false,
            hidden: false,
        },
    ],
}