export default {
    setup: {
        allow_submit: true,
        new_form_id: 'new-advance-application',
        info_form_id: 'advance-application-info',
        title: "Salary Advance Application",
        layout_columns: 6,
        model: "Advance_Application",
        allow_delete: false,
        allow_disable: false,
    },
    form_actions: [],
    fields:[
        {
            id: "applicant",
            fieldlabel: "Applicant",
            fieldname: "applicant",
            fieldtype: "link",
            model: "Employee",
            columns: 2,
            required: true,
            hidden: true,
            placeholder: " ",
            default: lite?.employee_info?.name,
        },
        {
            id: "full_name",
            fieldlabel: "Full Names",
            fieldname: "full_name",
            fieldtype: "read-only",
            columns: 2,
            required: true,
            hidden: false,
            placeholder: " ",
            fetchfrom: "applicant",
            fetchfield: "full_name",

        },
        {
            id: "show_totals",
            fieldlabel: "Shows",
            fieldname: "show_totals",
            fieldtype: "select",
            options: ["Show"],
            columns: 2,
            required: false,
            hidden: true,
            placeholder: " ",
        },{
            id: "is_paid",
            fieldlabel: "is_paid",
            fieldname: "is_paid",
            fieldtype: "int",
            columns: 2,
            required: false,
            hidden: true,
            default: '0',
            placeholder: " ",
        },
        {
            id: "designation",
            fieldlabel: "Job Role",
            fieldname: "designation",
            fieldtype: "read-only",
            columns: 2,
            required: true,
            hidden: false,
            placeholder: " ",
            fetchfrom: "applicant",
            fetchfield: "designation",

        },
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "read-only",
            columns: 2,
            required: true,
            hidden: false,
            placeholder: " ",
            fetchfrom: "applicant",
            fetchfield: "department",

        },
        {
            id: "employment_type",
            fieldlabel: "Employment Type",
            fieldname: "employment_type",
            fieldtype: "read-only",
            columns: 2,
            required: false,
            hidden: true,
            placeholder: " ",
            fetchfrom: "applicant",
            fetchfield: "employment_type",

        },
        {
            id: "date_of_joining",
            fieldlabel: "Joining Date",
            fieldname: "date_of_joining",
            fieldtype: "read-only",
            columns: 2,
            required: false,
            hidden: true,
            placeholder: " ",
            fetchfrom: "applicant",
            fetchfield: "date_of_joining",

        },
        {
            id: "employee_grade",
            fieldlabel: "Salary Grade",
            fieldname: "employee_grade",
            fieldtype: "read-only",
            columns: 2,
            required: true,
            hidden: false,
            placeholder: " ",
            fetchfrom: "applicant",
            fetchfield: "employee_grade",

        },
        {
            id: "basic_pay",
            fieldlabel: "Basic Pay",
            fieldname: "basic_pay",
            fieldtype: "read-only",
            columns: 2,
            required: false,
            hidden: true,
            placeholder: " ",
            fetchfrom: "applicant",
            fetchfield: "basic_pay",

        },
        {
            id: "emp_status",
            fieldlabel: "Status",
            fieldname: "emp_status",
            fieldtype: "read-only",
            columns: 2,
            required: false,
            hidden: true,
            placeholder: " ",
            fetchfrom: "applicant",
            fetchfield: "status",

        },
        {
            id: "section",
            fieldlabel: "Section",
            fieldname: "section",
            fieldtype: "text",
            columns: 2,
            required: false,
            hidden: false,
            placeholder: " ",

        },
        {
            id: "type_of_advance",
            fieldlabel: "Type of Advance",
            fieldname: "type_of_advance",
            fieldtype: "link",
            model: "Salary_Advance_Configuration",
            columns: 2,
            required: true,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "amount",
            fieldlabel: "Amount",
            fieldname: "amount",
            fieldtype: "int",
            columns: 2,
            required: true,
            hidden: false,
            placeholder: " ",
            default: 0.0,
        },

        {
            id: "4rr",
            fieldlabel: "",
            fieldname: "4rr",
            fieldtype: "section-break",
            columns: 2,
            required: false,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "purpose",
            fieldlabel: "Purpose",
            fieldname: "purpose",
            fieldtype: "longtext",
            classnames: "p-2 h-[250px]",
            columns: 6,
            required: true,
            hidden: false,
            placeholder: " ",

        },
        {
            id: "total_monthly_amount",
            fieldlabel: "Monthly Amount",
            fieldname: "total_monthly_amount",
            fieldtype: "read-only",
            columns: 2,
            required: false,
            hidden: false,
            placeholder: " ",
            default: 0.0,
            displayon: ["show_totals", "Show"]
        },
        {
            id: "amount_with_interest",
            fieldlabel: "Amount With Interest",
            fieldname: "amount_with_interest",
            fieldtype: "read-only",
            columns: 2,
            required: false,
            hidden: false,
            placeholder: " ",
            default: 0.0,
            displayon: ["show_totals", "Show"]
        },
    ]
}