;
const empInfo = lite.system_settings.employee_info

export default {

    setup: {
        new_form_id: 'new-Scholarship-form',
        info_form_id: 'training-program-form-info',
        title: "Training Program",
        layout_columns: 4,
        model: "Training_Program",
        allow_submit: false,
        allow_disable: false,
    }, 
    fields: [
        {
            id: "initiator",
            fieldlabel: "Initiator ",
            fieldname: "initiator",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
            default: "Staff",
        },
        {
            id: "company",
            fieldlabel: "Company",
            fieldname: "company",
            fieldtype: "link",
            model: "Company",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
            default: lite.user.company.name
        },
        {
            id: "training",
            fieldlabel: "Training Program",
            fieldname: "name",
            fieldtype: "link",
            model: "Training_Program",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "type",
            fieldlabel: "Program Type",
            fieldname: "type",
            fieldtype: "link",
            model: "Training_Program_Type",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "training",
            fetchfield: "type"
        },

        {
            id: "sec",
            fieldlabel: "",
            fieldname: "sec",
            fieldtype: "section-break",
            columns: 1,
            addborder: true,
            required: false,
            hidden: false,
        },
        {
            id: "course",
            fieldlabel: "Course",
            fieldname: "course",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            displayon: ["type","Course"],
            fetchfrom: "training",
            fetchfield: "course",
        },

        {
            id: "location",
            fieldlabel: "Location",
            fieldname: "location",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "training",
            fetchfield: "location"

        },
        {
            id: "duration",
            fieldlabel: "Date",
            fieldname: "time_date",
            fieldtype: "read-only",
            columns: 1,
            required: true,
            hidden: false,
            placeholder: " ",
            default: "Date",
            fetchfrom: "training",
            fetchfield: "time_date"
        },
        {
            id: "start_date",
            fieldlabel: "Start Date",
            fieldname: "start_date",
            fieldtype: "date",
            columns: 1,
            required: false,
            placeholder: " ",
            hidden: false,
            default: lite?.utils?.today(),
            fetchfrom: "training",
            fetchfield: "start_date"
        },

        {
            id: "end_date",
            fieldlabel: "End Date",
            fieldname: "end_date",
            fieldtype: "date",
            placeholder: " ",
            columns: 1,
            required: false,
            hidden: false,
            // displayon: ["duration", "Date"],
            default: lite?.utils?.today(),
            fetchfrom: "training",
            fetchfield: "end_date",
        },

        {
            id: "program-duration",
            fieldlabel: "Program Duration (Days)",
            fieldname: "program_duration",
            fieldtype: "read-only",
            columns: 1,
            required: false,
            hidden: false,
            default: "1 Day",
            fetchfrom: "training",
            fetchfield: "program_duration",
        },

        {
            id: "trainer",
            fieldlabel: "Trainer Name",
            fieldname: "trainer",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "training",
            fetchfield: "trainer",
         
        },
        {
            id: "trainer-email",
            fieldlabel: "Trainer Email",
            fieldname: "trainer_email",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "training",
            fetchfield: "trainer_email",
        },
        {
            id: "contact",
            fieldlabel: "Contact Number",
            fieldname: "contact",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "training",
            fetchfield: "contact",           
        },
        {
            id: "sec",
            fieldlabel: "",
            fieldname: "sec",
            fieldtype: "section-break",
            columns: 1,
            addborder: false,
            required: false,
            hidden: false,
        },
        {
            id: "training-application-attachment",
            fieldlabel: "Training Attachment",
            fieldname: "training_application_attachment",
            fieldtype: "file",
            columns: 2,
            required: false,
            hidden: false,
            placeholder: " ",
        }, 
        {
            id: "sec",
            fieldlabel: "",
            fieldname: "sec",
            fieldtype: "section-break",
            columns: 1,
            addborder: false,
            required: false,
            hidden: false,
        },
        {
            id: "description",
            fieldlabel: "Program Description",
            fieldname: "description",
            fieldtype: "longtext",
            classnames:"h-[10rem]",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "training",
            fetchfield: "description",
        },
        {
            id: "reason",
            fieldlabel: "Reason For This Program",
            fieldname: "reason",
            fieldtype: "longtext",
            classnames:"h-[10rem]",
            columns: 2,
            placeholder: " ",
            required: false,
            hidden: false,
            fetchfrom: "training",
            fetchfield: "reason",
        }, 
        {
            id: "attendee",
            fieldlabel: "Attendee",
            fieldname: "attendee",
            fieldtype: "table",
            model: "Attendee",
            columns: 2,
            required: false,
            hidden: false,
            fetchfrom: "training",
            fetchfield: "attendee",            
            fields: [
                {
                    id: "employee",
                    fieldlabel:  "Employee No",
                    fieldname: "employee",
                    fieldtype: "link",
                    model: "Employee",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: false,
                    // default: lite?.employee_info?.name,
                },
                {
                    id: "email",
                    fieldlabel: "Employee Email",
                    fieldname: "email",
                    fieldtype: "read-only",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    fetchfrom: "employee",
                    fetchfield:"email",
                    // default: lite?.employee_info?.email,
                },
                {
                    id: "phone_no",
                    fieldlabel: "Employee Phone",
                    fieldname: "phone_no",
                    fieldtype: "read-only",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    fetchfrom: "employee",
                    fetchfield: ""
                    // default: lite?.employee_info?.contact,
                    
                },
            ]
        },
        {
            id: "expenses",
            fieldlabel: "Expense Breakdown",
            fieldname: "expenses",
            fieldtype: "table",
            model: "Program_Expense",
            columns: 2,
            required: false,
            hidden: false,
            fetchfrom: "training",
            fetchfield: "expenses",            
            fields: [
                {
                    id: "expense_type",
                    fieldlabel: "Select Expense",
                    fieldname: "expense_type",
                    fieldtype: "select",
                    options: [
                        "Venue and Logistics",
                        "Training Materials and Resources",
                        "Trainer or Facilitator Fees",
                        "Participant Expenses",
                        "Administrative and Overhead Costs",
                        "Technology and Equipment",
                        "Other Expenses"
                    ],
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: false,
                },
                {
                    id: "amount",
                    fieldlabel: "Expense Amount",
                    fieldname: "amount",
                    fieldtype: "currency",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                },
            ]
        }, 
        {
            id: "training_expense",
            fieldlabel: "Program Total Expense",
            fieldname: "training_expense",
            fieldtype: "read-only",
            columns: 1,
            required: false,
            hidden: false,
            default: '0.00',
            is_figure: true,
            fetchfrom: "training",
            fetchfield: "training_expense",   
        },     
    ],
}