export default {
    setup: {
        new_form_id: 'new-staff-verbal-warning',
        info_form_id: 'staff-verbal-warning-info',
        title: "Verbal Warning",
        layout_columns: 5,
        model: "Verbal_Warning"
    },
    fields: [
        {
            id: "date",
            fieldlabel: "Date",
            fieldname: "signing_date",
            fieldtype: "date",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },   
        {
            id: "employee-id",
            fieldlabel: "Issued To",
            fieldname: "employee_id",
            fieldtype: "link",
            model: "Employee",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },   
        {
            id: "column-break",
            fieldtype: "column-break",
            columns: 1
        },
        {
            id: "employee-full-name",
            fieldlabel: "Employee Full Name",
            fieldname: "employee_full_name",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            fetchfrom: "employee-id",
            fetchfield: "full_name"
        },   
        {
            id: "employee-job-title",
            fieldlabel: "Job Title",
            fieldname: "employee_job_title",
            fieldtype: "link",
            model: "Designation",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            fetchfrom: "employee-id",
            fetchfield: "designation"
        },   
        {
            id: "employee-department",
            fieldlabel: "Employee's Department",
            fieldname: "employee_department",
            fieldtype: "link",
            model: "Department",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
            fetchfrom: "employee-id",
            fetchfield: "department",
        },   
        {
            id: "date-of-violation",
            fieldlabel: "Date-Of-Violation",
            fieldname: "date_of_violation",
            fieldtype: "date",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },   
        {
            id: "column-break-001",
            fieldtype: "column-break",
            columns: 1
        },
        {
            id: "action-subject",
            fieldlabel: "Action Subject",
            fieldname: "action_subject",
            fieldtype: "select",
            columns: 1,
            placeholder: " ",
            options: ["Behaviour", "Performance", "Behaviour/Performance"],
            default: "Behaviour/Performance",
            required: true,
            hidden: false,
        },  
        {
            id: "advised-action",
            fieldlabel: "Advised Action",
            fieldname: "advised_action",
            fieldtype: "select",
            columns: 1,
            placeholder: " ",
            options: ["Change", "Improve", "Change/Improve"],
            default: "Change/Improve",
            required: true,
            hidden: false,
        },    
        {
            id: "discription-of-violation",
            fieldlabel: "Discription of Violation",
            fieldname: "discription_of_violation",
            fieldtype: "rich",
            columns: 5,
            placeholder: " ",
            required: true,
            hidden: false,
            height: "300px",
        },        
    ],
}