const ss = await lite.connect.get_system_settings()

export default {
    setup: {
        new_form_id: 'new-welfare',
        info_form_id: 'welfare-info',
        title: "Welfare",
        layout_columns: 3,
        model: "Employee_Welfare",
        allow_submit: true,
    },
    // form_actions: [
        // {
        //     title: "Approve",
        //     icon: "price_check",
        //     icon_color: "indigo",
        //     action: create_training_event,
        //     for_docstatus: [1],
        // },
    // ],
    
    fields: [

        {
            id: "column-break-2",
            fieldlabel: "Employee Details",
            fieldname: "ddd",
            fieldtype: "section-break",
            required: false,
            hidden: false,
            placeholder: "Fill in the Employee Details",
        },
        {
            id: "employee",
            fieldlabel: "Employee No",
            fieldname: "employee",
            fieldtype: "link",
            model: "Employee",
            columns: 1,
            placeholder: "Employee No",
            required: false,
            hidden: false,
            filters: {
                status: "Active",
            }, 
        }, 
        {
            id: "employee_name",
            fieldlabel: "Employee Name",
            fieldname: "employee_name",
            fieldtype: "read-only",
            columns: 1,
            placeholder: "",
            required: false,
            hidden: false,
            fetchfrom:"employee",
            fetchfield: "full_name",
        },
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "read-only",
            columns: 1,
            placeholder: "",
            required: false,
            hidden: false,
            fetchfrom:"employee",
            fetchfield: "department"
        }, 
        {
            id: "designation",
            fieldlabel: "Job Title",
            fieldname: "designation",
            fieldtype: "read-only",
            columns: 1,
            placeholder: "",
            required: false,
            hidden: false,
            fetchfrom:"employee",
            fetchfield: "designation"
        }, 
        {
            id: "section",
            fieldlabel: "Section",
            fieldname: "section",
            fieldtype: "text",
            columns: 1,
            placeholder: "",
            required: false,
            hidden: false,
        }, 
        {
            id: "salary-scale",
            fieldlabel: "Salary Grade",
            fieldname: "salary_scale",
            fieldtype: "link",
            model:"Employee_Grade",
            columns: 1,
            placeholder: "",
            required: false,
            hidden: false,
        }, 
        {
            id: "section-break",
            fieldlabel: "Cost Recovery",
            fieldname: "section-break",
            fieldtype: "section-break",
            columns: 1,
            placeholder: "",
        }, 
        {
            id: "welfare_type",
            fieldlabel: "Welfare Type",
            fieldname: "welfare_type",
            fieldtype: "link",
            model: "Welfare_Type",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
        }, 
        {
            id: "welfare-expense",
            fieldlabel: "Bill Utilized",
            fieldname: "welfare_expense",
            fieldtype: "currency",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        }, 
        {
            id: "company-covered-expense",
            fieldlabel: "Council Covered Expense",
            fieldname: "company_covered_expense",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
        }, 
        {
            id: "staff-covered-expense",
            fieldlabel: "Staff Amount to be Recovered",
            fieldname: "staff_covered_expense",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "staff-covered-expense",
            fieldlabel: "Staff Amount to be Recovered (In Words)",
            fieldname: "staff_covered_expense",
            fieldtype: "read-only",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
        },
        {
            id: "attach_receipt",
            fieldlabel: "Attach Receipt",
            fieldname: "attach_receipt",
            fieldtype: "file",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            displayon: ["payment_method", "Cash"]
        },
        
        {
            id: "limit-unit",
            fieldlabel: "Limit Unit",
            fieldname: "limit_unit",
            fieldtype: "read-only",
            columns: 1, 
            required: false,
            hidden: false,
            placeholder: " ",
            fetchfrom: "welfare_type",
            fetchfield: "limit_unit",
            displayon: ["payment_method", "Cash"]
        },
        {
            id: "limit-qty",
            fieldlabel: "Repayment Period",
            fieldname: "limit_qty",
            fieldtype: "read-only",
            columns: 1, 
            required: false,
            hidden: false,
            placeholder: " ",
            default: "1",
            fetchfrom: "welfare_type",
            fetchfield: "limit_qty",
            default: 8,
            displayon: ["docstatus", 0],
        },
        // {
        //     id: "column-break-1",
        //     fieldlabel: "Pay Back Duration",
        //     fieldname: "",
        //     fieldtype: "column-break",
        //     columns: 1, 
        //     required: false,
        //     hidden: false,
        //     placeholder: "",
        // },
        
        {
            id: "payment_method",
            fieldlabel: "Payment Method",
            fieldname: "payment_method",
            fieldtype: "select",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            default: "Payroll",
            options: [
                "Payroll",
                "Cash",
            ]
        }, 
        {
            id: "payment-length-unit",
            fieldlabel: "Repayment Period",
            fieldname: "pay_length_unit",
            fieldtype: "select",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: true,
            fetchfrom: "welfare_type",
            fetchfield: "limit_unit",
            options: [
                "Months",
            ]
        }, 
        {
            id: "payment-length",
            fieldlabel: "Repayment Period",
            fieldname: "payment_length",
            fieldtype: "int",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            default: "1",
            options: [1,2,3,4,5,6,7,8],
            fetchfrom: "welfare_type",
            fetchfield: "limit_qty",
            displayon: ["docstatus", 0],
        }, 
    ],
}