export default {
    setup: {
        new_form_id: 'new-job-application',
        info_form_id: 'job-application-info',
        title: "Job Application",
        layout_columns: 12,
        allow_delete: false,
        model: "Job_Application"
    },
    fields: [
        {
            id: "applicant_first_name",
            fieldlabel: "Last Name",
            fieldname: "applicant_first_name",
            fieldtype: "text",
            columns: 4,
            placeholder: "Enter Last Name",
            required: true,
            hidden: false,
        },
        {
            id: "applicant_middle_name",
            fieldlabel: "Middle Name",
            fieldname: "applicant_middle_name",
            fieldtype: "text",
            columns: 4,
            placeholder: "Enter Middle Name",
            required: false,
            hidden: false,
        },
        {
            id: "applicant_last_name",
            fieldlabel: "First Name",
            fieldname: "applicant_last_name",
            fieldtype: "text",
            columns: 4,
            placeholder: "Enter First Name",
            required: true,
            hidden: false,
        },
        {
            id: "email",
            fieldlabel: "Email Address",
            fieldname: "email",
            fieldtype: "text",
            columns: 4,
            placeholder: "Enter Email",
            required: true,
            hidden: false,
        },
        {
            id: "id_nrc",
            fieldlabel: "ID/NRC",
            fieldname: "id_nrc",
            fieldtype: "text",
            columns: 4,
            placeholder: "Enter ID/NRC",
            required: false,
            hidden: false,
          },
        {
            id: "mobile",
            fieldlabel: "Phone Number",
            fieldname: "mobile",
            fieldtype: "text",
            columns: 4,
            placeholder: "Enter Phone Number",
            required: true,
            hidden: false,
        },
        {
            id: "job_opening",
            fieldlabel: "Job Advertisement",
            fieldname: "job_opening",
            fieldtype: "link",
            model: "Job_Advertisement",
            columns: 4,
            placeholder: "Select Job Advertisement",
            required: false,
            hidden: false,
        },
        {
            id: "designation",
            fieldlabel: "Job Title",
            fieldname: "designation",
            fieldtype: "link",
            model:"Designation",
            columns: 4,
            placeholder: "Enter Job Title",
            required: false,
            hidden: false,
            fetchfrom: "job_opening",
            fetchfield: "designation"
        },

        {
            id: "country",
            fieldlabel: "Country",
            fieldname: "country",
            fieldtype: "link",
            model: "Country",
            columns: 4,
            placeholder: "Enter Country",
            required: false,
            hidden: false,
           
        },
        {
            id: "884",
            fieldlabel: "Qualifications and Skills",
            fieldtype: "section-break",
            addborder:true
        },
        {
            id: "attachments",
            fieldlabel: "Attachment",
            fieldname: "attachments",
            fieldtype: "table",
            model: "Attachment",
            required: false,
            hidden: false,
            columns: 6,
            addemptyrow: false,
            fields: [
                {
                    id: "qualification_type",
                    fieldlabel: "Qualification Type",
                    fieldname: "qualification_type",
                    fieldtype: "read-only",
                    columns: 10,
                    placeholder: "Qualification Type",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "qualification",
                    fieldlabel: "Attachment",
                    fieldname: "qualification",
                    fieldtype: "file",
                    columns: 10,
                    placeholder: "Attach File",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
            ]
        },

        {
            id: "job_skills",
            fieldlabel: "Job Skills",
            fieldname: "job_skills",
            fieldtype: "table",
            model: "Job_Application_Skill",
            required: false,
            hidden: false,
            columns: 6,
            addemptyrow: false,
            fields: [
                {
                    id: "skill",
                    fieldlabel: "Skill",
                    fieldname: "skill",
                    fieldtype: "read-only",
                    columns: 10,
                    placeholder: "Skill",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "has_skill",
                    fieldlabel: "Has Skill",
                    fieldname: "has_skill",
                    fieldtype: "check",
                    columns: 10,
                    placeholder: "Has Skill",
                    required: false,
                    hidden: true,
                    istablefield: true,
                },
            ]
        },
        {
            id: "resume",
            fieldlabel: "Resume",
            fieldname: "ci",
            fieldtype: "section-break",
            addborder: true,
            columns: 12,
            hidden: false,
        },
        {
            id: "cover-letter",
            fieldlabel: "Cover Letter",
            fieldname: "cover_letter",
            fieldtype: "rich",
            height: 300,
            columns: 12,
            placeholder: "Enter Cover Letter",
            required: false,
            hidden: false,
        },
        {
            id: "details",
            fieldlabel: "Salary Expectation",
            fieldname: "ci",
            fieldtype: "section-break",
            addborder: true,
            columns: 12,
            hidden: false,
        },
     
        {
            id: "currency",
            fieldlabel: "Currency",
            fieldname: "currency",
            fieldtype: "read-only",
            columns: 4,
            placeholder: "Enter Currency",
            required: false,
            hidden: false,
            fetchfrom: "job_opening",
            fetchfield: "currency"
          
        },
        
        {
            id: "lower-range",
            fieldlabel: "Lower Range",
            fieldname: "lower_range",
            fieldtype: "read-only",
            columns: 4,
            required: false,
            placeholder: "Enter Lower Range",
            hidden: false,
            fetchfrom: "job_opening",
            fetchfield: "lower_range",
            default: "0.00"
        },
    ],
}