export const individual = {
    setup: {
        new_form_id: 'new-tenant',
        info_form_id: 'tenant-info',
        title: "Tenant",
        layout_columns: 2,
        model: "Province"
    },
    fields: [
        {
            id: "country",
            fieldlabel: "Country",
            fieldname: "country",
            fieldtype: "link",
            model:"Country",
            columns: 1,
            placeholder: "Country",
            required: true,
            hidden: false,
            value:"Zambia"
        },
        {
            id: "first-name",
            fieldlabel: "First Name",
            fieldname: "first_name",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter First Name",
            required: true,
            hidden: false,
            description: "Enter First Name",
        },
        {
            id: "last-name",
            fieldlabel: "Last Name",
            fieldname: "last_name",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Last Name",
            required: true,
            hidden: false,
            description: "Enter Last Name",
        },
        {
            id: "other-name",
            fieldlabel: "Other Name",
            fieldname: "other_name",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Other Name",
            required: false,
            hidden: false,
            description: "Enter Other Name",
        },
        {
            id: "email",
            fieldlabel: "Email",
            fieldname: "email",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Email",
            required: true,
            hidden: false,
        },
        {
            id: "contact-no",
            fieldlabel: "Contact No",
            fieldname: "contact_no",
            fieldtype: "text",
            columns: 1,
            placeholder: "Contact No",
            required: true,
            hidden: false,
        },
        {
            id: "tax-identification-no",
            fieldlabel: "Tax Identification No",
            fieldname: "tax_identification_no",
            fieldtype: "text",
            columns: 1,
            placeholder: "Tax Identification No",
            required: true,
            hidden: false,
        },
        {
            id: "industry",
            fieldlabel: "Industry",
            fieldname: "industry",
            fieldtype: "link",
            model:"Industry",
            columns: 1,
            placeholder: "Industry",
            required: true,
            hidden: false,
        },
        {
            id: "sector",
            fieldlabel: "Sector",
            fieldname: "sector",
            fieldtype: "link",
            model:"Sector",
            columns: 1,
            placeholder: "Sector",
            required: true,
            hidden: false,
        },
        {
            id: "trade-type",
            fieldlabel: "Registration Category",
            fieldname: "customer_type",
            fieldtype: "link",
            model:"Registration_Type",
            columns: 1,
            placeholder: "Registration Category",
            required: true,
            hidden: false,
        },
        {
            id: "physical-address",
            fieldlabel: "Physical Address",
            fieldname: "physical_address",
            fieldtype: "text",
            columns: 1,
            placeholder: "Physical Address",
            required: true,
            hidden: false,
        }
    ],
}

export const organization = {
    setup: {
        new_form_id: 'new-tenant',
        info_form_id: 'tenant-info',
        title: "Tenant",
        layout_columns: 2,
        model: "Province"
    },
    fields: [
        {
            id: "country",
            fieldlabel: "Country",
            fieldname: "country",
            fieldtype: "link",
            model:"Country",
            columns: 1,
            placeholder: "Country",
            required: true,
            hidden: false,
            value:"Zambia"
        },
        {
            id: "name",
            fieldlabel: "Organization Name",
            fieldname: "name",
            fieldtype: "text",
            columns: 1,
            placeholder: "Organization Name",
            required: true,
            hidden: false,
        },
        
        {
            id: "email",
            fieldlabel: "Email",
            fieldname: "email",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Email",
            required: true,
            hidden: false,
        },
        {
            id: "contact-no",
            fieldlabel: "Contact No",
            fieldname: "contact_no",
            fieldtype: "text",
            columns: 1,
            placeholder: "Contact No",
            required: true,
            hidden: false,
        },
        {
            id: "tax-identification-no",
            fieldlabel: "Tax Identification No",
            fieldname: "tax_identification_no",
            fieldtype: "text",
            columns: 1,
            placeholder: "Tax Identification No",
            required: true,
            hidden: false,
        },
        {
            id: "industry",
            fieldlabel: "Industry",
            fieldname: "industry",
            fieldtype: "link",
            model:"Industry",
            columns: 1,
            placeholder: "Industry",
            required: true,
            hidden: false,
        },
        {
            id: "sector",
            fieldlabel: "Sector",
            fieldname: "sector",
            fieldtype: "link",
            model:"Sector",
            columns: 1,
            placeholder: "Sector",
            required: true,
            hidden: false,
        },
        {
            id: "trade-type",
            fieldlabel: "Registration Category",
            fieldname: "customer_type",
            fieldtype: "link",
            model:"Registration_Type",
            columns: 1,
            placeholder: "Registration Category",
            required: true,
            hidden: false,
        },
        {
            id: "physical-address",
            fieldlabel: "Physical Address",
            fieldname: "physical_address",
            fieldtype: "text",
            columns: 1,
            placeholder: "Physical Address",
            required: true,
            hidden: false,
        },
        {
            id: "vat-registration-no",
            fieldlabel: "VAT Registration No (Optional)",
            fieldname: "vat_registration_no",
            fieldtype: "text",
            columns: 1,
            placeholder: "VAT Registration No",
            required: false,
            hidden: false,
        }
    ],
}