
let opportunity = await lite.connect.x_post ("get_job_opening", {name: lite.utils.get_url_parameters ("op")})
if (opportunity.status == lite.status_codes.ok) {
    opportunity = opportunity.data
}else {
    opportunity = undefined
}
export default {
    setup: {
        new_form_id: 'new-career-medical-doc',
        info_form_id: 'job-career-application-info',
        title: "Job Application",
        layout_columns: 4,
        allow_submit: true,
        allow_update: false,
        allow_delete: false,
        allow_disable: false,
        allow_duplicate: false,
        allow_refresh: false,
        allow_cancel: false,
        allow_create: false,
        model: "Job_Application",
    },
    fields: [
        {
            id: "applicant_first_name",
            fieldlabel: "First Name",
            fieldname: "applicant_first_name",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter First Name",
            required: true,
          },
          {
            id: "applicant_middle_name",
            fieldlabel: "Middle Name",
            fieldname: "applicant_middle_name",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Middle Name",
            required: false,
          },
          {
            id: "applicant_last_name",
            fieldlabel: "Last Name",
            fieldname: "applicant_last_name",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Last Name",
            required: true,
          },
          {
            id: "date_of_birth",
            fieldlabel: "Date of Birth",
            fieldname: "date_of_birth",
            fieldtype: "date",
            columns: 1,
            required: true,
          },
          {
              id: "marital_status",
              fieldlabel: "Marital Status",
              fieldname: "marital_status",
              fieldtype: "select",
              options: ["Single", "Married"],
              columns: 1,
              required: true,
          },
          {
            id: "gender",
            fieldlabel: "Gender",
            fieldname: "gender",
            fieldtype: "select",
            options: ["Male", "Female", "Other"],
            columns: 1,
            required: false,
          },
          {
            id: "postal_address",
            fieldlabel: "Postal Address",
            fieldname: "postal_address",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Postal Address",
            required: true,
        },
        {
            id: "physical_address",
            fieldlabel: "Physical Address",
            fieldname: "physical_address",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Physical Address",
            required: true,
        },
        {
            id: "job-opening",
            fieldlabel: "Job Advertisement",
            fieldname: "job_opening",
            fieldtype: "read-only",
            columns: 1,
            placeholder: "Enter Job Advertisement",
            required: false,
            hidden: false,
            default: opportunity?.name
        },
        {
            id: "designation",
            fieldlabel: "Job Title",
            fieldname: "designation",
            fieldtype: "read-only",
            // model:"Designation",
            columns: 1,
            placeholder: "Enter Job Title",
            required: false,
            hidden: false,
            default: opportunity?.designation
        },
        {
            id: "country",
            fieldlabel: "Country",
            fieldname: "country",
            fieldtype: "link",
            model: "Country",
            columns: 1,
            placeholder: "Enter Country",
            required: false,
            hidden: false,
           
        },
        {
            id: "email",
            fieldlabel: "Email Address",
            fieldname: "email",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Email",
            required: true,
            hidden: false,
        },
        {
            id: "mobile",
            fieldlabel: "Phone Number",
            fieldname: "mobile",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Phone Number",
            required: true,
            hidden: false,
        },
        {
            id: "resume",
            fieldlabel: "Resume",
            fieldname: "ci",
            fieldtype: "section-break",
            addborder: true,
            columns: 1,
            hidden: false,
        },
        {
            id: "cover-letter",
            fieldlabel: "Cover Letter",
            fieldname: "cover_letter",
            fieldtype: "longtext",
            height: 180,
            columns: 4,
            placeholder: "Enter Cover Letter",
            required: false,
            hidden: false,
        },
        {
            id: "resume",
            fieldlabel: "Skills/Qualifications",
            fieldname: "ci",
            fieldtype: "section-break",
            addborder: true,
            columns: 1,
            hidden: false,
        },
        {
            id: "attachment",
            fieldlabel: "Documents/Qualifications",
            fieldname: "attachments",
            fieldtype: "table",
            model: "Attachment",
            required: false,
            hidden: false,
            columns: 2,
            fields: [
                {
                    id: "qualification",
                    fieldlabel: "Document",
                    fieldname: "qualification",
                    fieldtype: "file",
                    columns: 3,
                    placeholder: "Enter Skill",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "qualification_type",
                    fieldlabel: "Qualification Type",
                    fieldname: "qualification_type",
                    fieldtype: "text",
                    columns: 3,
                    placeholder: "Degree/Diploma",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
            ]
        },
        {
            id: "job_skills",
            fieldlabel: "Skills",
            fieldname: "job_skills",
            fieldtype: "table",
            model: "Job_Application_Skill",
            required: false,
            hidden: false,
            columns: 2,
            fields: [
                {
                    id: "skill",
                    fieldlabel: "Skill",
                    fieldname: "skill",
                    fieldtype: "text",
                    columns: 3,
                    placeholder: "Enter SKill",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "has_skill",
                    fieldlabel: "Must Have",
                    fieldname: "has_skill",
                    fieldtype: "check",
                    columns: 3,
                    placeholder: "Must Have",
                    required: false,
                    hidden: true,
                    istablefield: true,
                },
            ]
        },
        {
            id: "details",
            fieldlabel: "Salary Expectation",
            fieldname: "ci",
            fieldtype: "section-break",
            addborder: true,
            columns: 1,
            hidden: false,
        },
        {
            id: "currency",
            fieldlabel: "Currency",
            fieldname: "currency",
            fieldtype: "read-only",
            // model: "Currency",
            columns: 1,
            placeholder: "Enter Currency",
            required: false,
            hidden: false,
            default: opportunity?.currency
        },
        
        {
            id: "lower-range",
            fieldlabel: "Lower Range",
            fieldname: "lower_range",
            fieldtype: "read-only",
            columns: 1,
            required: false,
            placeholder: "Enter Lower Range",
            hidden: false,
            default: opportunity?.lower_range
        },
        {
            id: "upper-range",
            fieldlabel: "Upper Range",
            fieldname: "upper_range",
            fieldtype: "read-only",
            columns: 1,
            required: false,
            placeholder: "Enter Upper Range",
            hidden: false,
            default: opportunity?.upper_range
        },
    ],
}