export default {
    setup: {
        new_form_id: 'new-company',
        info_form_id: 'company-info',
        title: "company",
        layout_columns: 3,
        model: "Company",
        filters:{disabled__in:[0,1]}
    },
    fields: [
        {
            id: "name",
            fieldlabel: "Company Name",
            fieldname: "name",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Company Name",
            required: true,
            hidden: false,
            description: "Company Name",
        },
        
        {
            id: "company-industry",
            fieldlabel: "Company Industry",
            fieldname: "industry",
            fieldtype: "link",
            model: "Industry",
            columns: 1,
            placeholder: "Select Company Industry",
            required: true,
            hidden: false,
            description: ""
        },
        {
            id: "sector",
            fieldlabel: "Company Sector",
            fieldname: "sector",
            fieldtype: "link",
            model: "Sector",
            columns: 1,
            placeholder: "Select company Sector",
            required: false,
            hidden: false,
            description: ""
        },
        {
            id: "country",
            fieldlabel: "Country",
            fieldname: "country",
            fieldtype: "link",
            model: "Country",
            columns: 1,
            placeholder: "Select Country",
            required: true,
            hidden: false,
            
            default: "Zambia"
        },
        {
            id: "city",
            fieldlabel: "City",
            fieldname: "city",
            fieldtype: "link",
            model: "City",
            columns: 1,
            placeholder: "Select City",
            required: false,
            hidden: false,
            description: ""
        },
        {
            id: "tax-identification-number",
            fieldlabel: "Tax Identification Number",
            fieldname: "tax_identification_no",
            fieldtype: "text",
            columns: 1,
            placeholder: "Select Tax Identification Number",
            required: false,
            hidden: false,
            description: ""
        },
        {
            id: "email",
            fieldlabel: "Company Email",
            fieldname: "email",
            fieldtype: "text",
            columns: 1,
            placeholder: "company Email",
            required: false,
            hidden: false,
            description: ""
        },
        {
            id: "contact-no",
            fieldlabel: "Company Contact No",
            fieldname: "contact_no",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter company Contact No",
            required: false,
            hidden: false,
            description: ""
        },
        {
            id: "physical-address",
            fieldlabel: "Physical Address",
            fieldname: "physical_address",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Physical Address",
            required: false,
            hidden: false,
            description: ""
        },
        {
            id: "address-line-two",
            fieldlabel: "Postal Address",
            fieldname: "postal_address",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Postal Address",
            required: false,
            hidden: false,
            description: ""
        },
        {
            id: "reporting-currency",
            fieldlabel: "Reporting Currency",
            fieldname: "reporting_currency",
            fieldtype: "link",
            model: "Currency",
            columns: 1,
            placeholder: "Select Reporting Currency",
            required: true,
            hidden: false,
            description: ""
        },
        {
            id: "company-logo",
            fieldlabel: "Company Logo",
            fieldname: "company_logo",
            fieldtype: "file",
            columns: 1,
            placeholder: "Select Company Logo",
            required: false,
            hidden: false,
            description: "Select Company Logo",
        },
        {
            id: "cogroup",
            fieldlabel: "Company Grouping",
            fieldname: "cogroup",
            fieldtype: "section-break",
            required: true,
            hidden: false,
            addborder:true,
            height: 300         
        },
        {
            id: "is-group-company",
            fieldlabel: "Is Group company",
            fieldname: "is_group_company",
            fieldtype: "check",
            columns: 1,
            placeholder: "Is Group Company",
            required: false,
            hidden: false,
            default: 0
        },
        
        {
            id: "parent_company",
            fieldlabel: "Parent Company(Optional)",
            fieldname: "parent_company",
            fieldtype: "link",
            model:"Company",
            columns: 1,
            placeholder: "Select Parent Company",
            required: false,
            hidden: false,
            description: "Parent Company",
            filters:{is_group_company: 1},
            displayon:["is-group-company", 0]
        },
        {
            id: "theme",
            fieldlabel: "Theming",
            fieldname: "theme",
            fieldtype: "section-break",
            required: true,
            hidden: false,
            addborder:true,
            height: 300         
        },
        {
            id: "default-theme-color",
            fieldlabel: "Default Theme Color",
            fieldname: "default_theme_color",
            fieldtype: "color",
            columns: 1,
            placeholder: "Select Default Theme Color",
            required: false,
            hidden: false,
        },
        {
            id: "default-theme-text-color",
            fieldlabel: "Default Theme Text Color",
            fieldname: "default_theme_text_color",
            fieldtype: "color",
            columns: 1,
            placeholder: "Select Default Theme Text Color",
            required: false,
            hidden: false,
        },
        {
            id: "default-secondary-color",
            fieldlabel: "Default Secondary Color",
            fieldname: "default_secondary_color",
            fieldtype: "color",
            columns: 1,
            placeholder: "Select Default Secondary Color",
            required: false,
            hidden: false,
        },
        
        
    ],
}