export default {
    setup: {
        new_form_id: 'new-industry',
        info_form_id: 'industry-info',
        title: "Industry",
        layout_columns: 2,
        model: "Industry",
        allow_delete:true
    },
    fields: [
        {
            id: "name",
            fieldlabel: "Industry Name",
            fieldname: "name",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Industry Name",
            required: true,
            hidden: false,
            description: "Industry Name",
        },
        {
            id: "market-size",
            fieldlabel: "Market Size",
            fieldname: "market_size",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Market Size",
            required: false,
            hidden: false,
            description: "Market Size",
        },
        {
            id: "economic-impact",
            fieldlabel: "Economic Impact",
            fieldname: "economic_impact",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Economic Impact",
            required: false,
            hidden: false,
            description: "Economic Impact",
        },
        {
            id: "trade-associates",
            fieldlabel: "Trade Associates",
            fieldname: "trade_associates",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Trade Associates",
            required: false,
            hidden: false,
            description: "Trade Associates",
        },
        {
            id: "key-players",
            fieldlabel: "Key Players",
            fieldname: "key_players",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Key Players",
            required: false,
            hidden: false,
            description: "Key Players",
        }
    ],
}