export default {
    setup: {
        new_form_id: 'new-share',
        info_form_id: 'share-info',
        title: "Share",
        layout_columns: 3,
        model: "Shareholder"
    },
    fields: [
        {
            id: "first-name",
            fieldlabel: "First Name",
            fieldname: "first_name",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter First Name",
            required: true,
            hidden: false,
        },
        {
            id: "last-name",
            fieldlabel: "Last Name",
            fieldname: "last_name",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Last Name",
            required: true,
            hidden: false,
        },
        {
            id: "other-names",
            fieldlabel: "Other Names",
            fieldname: "other_names",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Other Names",
            required: false,
            hidden: false,
        },
        {
            id: "email",
            fieldlabel: "Email",
            fieldname: "email",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Email",
            required: true,
            hidden: false,
        },
        {
            id: "contact",
            fieldlabel: "Contact",
            fieldname: "contact",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Contact",
            required: true,
            hidden: false,
        },
    ],
}