export default {
    setup: {
        new_form_id: 'new-share',
        info_form_id: 'share-info',
        title: "Shares",
        layout_columns: 3,
        model: "Share",
        allow_submit:true,
        allow_cancel:true,
        allow_preview:true
    },
    fields: [
        {
            id: "share_type",
            fieldlabel: "Share Type",
            fieldname: "share_type",
            fieldtype: "link",
            model:"Share_Type",
            columns: 1,
            placeholder: "Select Share Type",
            required: true,
            hidden: false,
        },
        {
            id: "company",
            fieldlabel: "Company",
            fieldname: "company",
            fieldtype: "link",
            model: "Company",
            columns: 1,
            placeholder: "Select Company",
            required: true,
            hidden: false,
        },
        
        {
            id: "currency",
            fieldlabel: "Currency",
            fieldname: "currency",
            fieldtype: "read-only",
            model:"Currency",
            columns: 1,
            placeholder: "Select Currency",
            required: true,
            hidden: false,
            fetchfrom: "share_type",
            fetchfield: "currency"
        },
        {
            id: "total-shares",
            fieldlabel: "Total Shares",
            fieldname: "total_shares",
            fieldtype: "float",
            columns: 1,
            placeholder: "Total Shares",
            required: true,
            hidden: false,
        },
        {
            id: "price-per-share",
            fieldlabel: "Price Per Share",
            fieldname: "price_per_share",
            fieldtype: "float",
            columns: 1,
            placeholder: "Price Per Share",
            required: true,
            hidden: false,
            fetchfrom: "share_type",
            fetchfield: "price_per_share"
        },
        {
            id: "total-Value",
            fieldlabel: "Total Value",
            fieldname: "total_value",
            fieldtype: "read-only",
            columns: 1,
            placeholder: "Total Value",
            required: true,
            hidden: false,
            default:"0.00"
        },
        {
            id: "share-holder",
            fieldlabel: "Shareholders",
            fieldname: "shareholders",
            fieldtype: "table",
            model:"Share_Shareholder",
            columns: 3,
            placeholder: "Shareholders",
            required: true,
            hidden: false,
            fields:[
                {
                    id: "shareholder",
                    fieldlabel: "Shareholder",
                    fieldname: "shareholder",
                    fieldtype: "link",
                    model:"Shareholder",
                    columns: 3,
                    placeholder: "Shareholder",
                    required: true,
                    hidden: false,
                },
                {
                    id: "first-name",
                    fieldlabel: "First Name",
                    fieldname: "first_name",
                    fieldtype: "read-only",
                    columns: 3,
                    placeholder: "First Name",
                    fetchfrom:"shareholder",
                    fetchfield:"first_name",
                    required: true,
                    hidden: false,
                },
                {
                    id: "last-name",
                    fieldlabel: "Last Name",
                    fieldname: "last_name",
                    fieldtype: "read-only",
                    columns: 3,
                    placeholder: "Last Name",
                    fetchfrom:"shareholder",
                    fetchfield:"last_name",
                    required: true,
                    hidden: false,
                },
                {
                    id: "total-shares",
                    fieldlabel: "Total Shares",
                    fieldname: "shareholder_total_shares",
                    fieldtype: "float",
                    columns: 3,
                    placeholder: "Total Shares",
                    required: true,
                    hidden: false,
                },
                {
                    id: "share-percentage",
                    fieldlabel: "Share Percentage",
                    fieldname: "shareholder_share_percentage",
                    fieldtype: "read-only",
                    columns: 3,
                    placeholder: "Share Percentage",
                    required: true,
                    hidden: false,
                    default:"0.00"
                },
                {
                    id: "share-Value",
                    fieldlabel: "Share Value",
                    fieldname: "shareholder_share_value",
                    fieldtype: "read-only",
                    columns: 3,
                    placeholder: "Share Value",
                    required: true,
                    hidden: false,
                    default:"0.00"
                },
            ]
        },

        {
            id: "total-shareholders",
            fieldlabel: "Total Shareholders",
            fieldname: "total_shareholders",
            fieldtype: "read-only",
            columns: 1,
            placeholder: "Total Shareholders",
            required: true,
            hidden: false,
            default:"0"
        },
        {
            id: "total_owned_shares",
            fieldlabel: "Total Owned Shares",
            fieldname: "total_owned_shares",
            fieldtype: "read-only",
            columns: 1,
            placeholder: "Total Owned Shares",
            required: true,
            hidden: false,
            default:"0"
        },

        {
            id: "total_owned_value",
            fieldlabel: "Total Owned value",
            fieldname: "total_owned_value",
            fieldtype: "read-only",
            columns: 1,
            placeholder: "Total Owned value",
            required: true,
            hidden: false,
            default:"0"
        },
        {
            id: "total_unowned_shares",
            fieldlabel: "Total Unowned Shares",
            fieldname: "total_unowned_shares",
            fieldtype: "read-only",
            columns: 1,
            placeholder: "Total Unowned Shares",
            required: true,
            hidden: false,
            default:"0"
        },

        {
            id: "total_unowned_value",
            fieldlabel: "Total Unowned value",
            fieldname: "total_unowned_value",
            fieldtype: "read-only",
            columns: 1,
            placeholder: "Total Unowned value",
            required: true,
            hidden: false,
            default:"0"
        },
    ],
}