export default {
    setup: {
        allow_submit: false,
        new_form_id: 'new-user',
        info_form_id: 'user-info',
        title: "User",
        layout_columns: 3,
        model: "Lite_User"
    },
    form_actions: [
        { title: "Disable User", icon: "hide_source", icon_color: "orange", action: null, for_docstatus: ["draft"] }
    ],
    fields: [
        
        {
            id: "first-name",
            fieldlabel: "First Name",
            fieldname: "first_name",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter First Name",
            required: true,
            hidden: false,
        },
        {
            id: "middle-name",
            fieldlabel: "Middle Name",
            fieldname: "middle_name",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Middle Name",
            required: false,
            hidden: false,
        },
        {
            id: "Last Name",
            fieldlabel: "Last Name",
            fieldname: "last_name",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Last Name",
            required: false,
            hidden: false,
        },
        {
            id: "email",
            fieldlabel: "Email Address",
            fieldname: "email",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Email Address",
            required: true,
            hidden: false,
        },
        {
            id: "contact_no",
            fieldlabel: "Contact No",
            fieldname: "contact_no",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Contact No",
            required: true,
            hidden: false,
        },
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "link",
            model:"Department",
            columns: 1,
            placeholder: "Enter Department",
            required: true,
            hidden: false,
        },
        {
            id: "name",
            fieldlabel: "User Name",
            fieldname: "name",
            fieldtype: "read-only",
            columns: 1,
            placeholder: "Enter User Name",
            required: false,
            hidden: true,
        },
        {
            id: "main-role",
            fieldlabel: "Role",
            fieldname: "main_role",
            fieldtype: "link",
            model:"Role",
            columns: 1,
            placeholder: "Assign Role",
            required: true,
            hidden: false,
        },
        {
            id: "company",
            fieldlabel: "Company",
            fieldname: "default_company",
            fieldtype: "link",
            model: "Company",
            columns: 1,
            placeholder: "Company",
            required: true,
            hidden: false,
            default: lite?.defaults?.company?.name
        },
        {
            id: "lite-user-permitted-companies",
            fieldlabel: "Other Permitted Companies",
            fieldname: "permitted_companies",
            fieldtype: "table",
            model:"Lite_User_Permitted_Company",
            required: false,
            hidden: false,
            addemptyrow:false,
            fields:[
                {
                    id: "created_on",
                    fieldlabel: "Created On",
                    fieldname: "created_on",
                    fieldtype: "read-only",
                    required: false,
                    hidden: true,
                },
                {
                    id: "creation_time",
                    fieldlabel: "Creation Time",
                    fieldname: "creation_time",
                    fieldtype: "read-only",
                    required: false,
                    hidden: true,
                },
                {
                    id: "id",
                    fieldlabel: "ID",
                    fieldname: "id",
                    fieldtype: "read-only",
                    required: false,
                    hidden: true,
                },
                {
                    id: "company",
                    fieldlabel: "Company Name",
                    fieldname: "company",
                    fieldtype: "link",
                    model:"Company",
                    placeholder: "Select Company",
                    required: false,
                    hidden: false,
                    columns:10
                },
              
            ]
          }
    ],
}