export default {
    setup: {
        new_form_id: 'new-workflow',
        info_form_id: 'workflow-info',
        title: "Workflow",
        layout_columns: 3,
        model: "Workflow"
    },
    fields: [
        {
            id: "record_type",
            fieldlabel: "Record Type",
            fieldname: "record_type",
            fieldtype: "link",
            model:"Model",
            columns: 1,
            placeholder: "Select Record Type",
            required: true,
            hidden: false
        },
        {
            id: "is_role_based_workflow",
            fieldlabel: "Is Role Based Workflow",
            fieldname: "is_role_based_workflow",
            fieldtype: "check",
            columns: 1,
            placeholder: "Is Role Based Workflow",
            required: false,
            hidden: false,
            default:1
        },
        {
            id: "is_departmental_workflow",
            fieldlabel: "Is Departmental Workflow",
            fieldname: "is_departmental_workflow",
            fieldtype: "check",
            columns: 1,
            placeholder: "Is Departmental Workflow",
            required: false,
            hidden: false,
        },
        
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "link",
            model:"Department",
            columns: 1,
            placeholder: "Select Department",
            required: false,
            hidden: false,
            description: "Department",
            displayon:["is_departmental_workflow", 1],
        },
        {
            id: "sec",
            fieldlabel: "Actions",
            fieldname: "acts",
            fieldtype: "section-break",
            columns: 1,
            placeholder: "Actions",
            required: true,
            hidden: false,
            addborder: true
        },
        {
            id: "workflow-stage",
            fieldlabel: "Workflow Stages",
            fieldname: "workflow_stage",
            fieldtype: "table",
            model:"Workflow_Stage",
            placeholder: "Workflow Stages",
            required: true,
            hidden: false,
            fields:[
                {
                    id: "doc-status",
                    fieldlabel: "If Stage Is",
                    fieldname: "stage",
                    fieldtype: "link",
                    model:"Doc_Status",
                    columns: 5,
                    placeholder: "Select Doc Stage",
                    required: true,
                    hidden: false,
                },
                {
                    id: "action",
                    fieldlabel: "Action",
                    fieldname: "action",
                    fieldtype: "link",
                    model:"Workflow_Action",
                    columns: 5,
                    placeholder: "Select Workflow Action",
                    required: true,
                    hidden: false,
                },
                {
                    id: "next-stage",
                    fieldlabel: "Next Stage",
                    fieldname: "next_stage",
                    fieldtype: "link",
                    model:"Doc_Status",
                    columns: 5,
                    placeholder: "Select Next Doc Stage",
                    required: true,
                    hidden: false,
                },
                {
                    id: "approver_group",
                    fieldlabel: "Approver Group",
                    fieldname: "approver_group",
                    fieldtype: "link",
                    model:"Workflow_Approver_Group",
                    columns: 5,
                    placeholder: "Select Workflow Approver Group",
                    required: true,
                    hidden: false,
                    displayon:["is_role_based_workflow", 1],
                },
                {
                    id: "approver",
                    fieldlabel: "Approver",
                    fieldname: "approver",
                    fieldtype: "link",
                    model:"Lite_User",
                    columns: 5,
                    placeholder: "Select Approver",
                    required: true,
                    hidden: true,
                    displayon:["is_role_based_workflow", 0],
                },
            ]
        },        
    ],
}