from django.urls import path, include

urlpatterns = [
    path("", include("client_app.staff.staff_dashboard.urls"),name="staff_dashboard"),
    path("staff_dashboard", include("client_app.staff.staff_dashboard.urls"),name="staff_dashboard"),
    path("staff_advance/", include("client_app.staff.staff_advance.urls")),
    path("staff_appraisal/", include("client_app.staff.staff_appraisal.urls")),
    path("staff_360_deg_appraisal/", include("client_app.staff.staff_360_deg_appraisal.urls")),
    path("staff_imprest/", include("client_app.staff.staff_imprest.urls")),
    path("staff_leave/", include("client_app.staff.staff_leave.urls")),
    path("staff_payslip/", include("client_app.staff.staff_payslip.urls")),
    path("staff_performance/", include("client_app.staff.staff_performance.urls")),
    path("staff_profile/", include("client_app.staff.staff_profile.urls")),
    path("staff_purchase_requisition/", include("client_app.staff.staff_purchase_requisition.urls")),
    path("staff_query/", include("client_app.staff.staff_query.urls")),
    path("staff_workplan/", include("client_app.staff.staff_workplan.urls")),
    path("staff_leave_history/", include("client_app.staff.staff_leave_history.urls")),
    path("staff_earnings_and_deductions/", include("client_app.staff.staff_earnings_and_deductions.urls")),
    path("staff_advance_history/", include("client_app.staff.staff_advance_history.urls")),
    path("staff_memo/", include("client_app.staff.staff_memo.urls")),
    path("staff_query/", include("client_app.staff.staff_query.urls")),
    path("staff_policy/", include("client_app.staff.staff_policy.urls")),
    path("staff_announcement/", include("client_app.staff.staff_anouncement.urls")),
    path("staff_employee_grievance/", include("client_app.staff.staff_employee_grievance.urls")),
    path("staff_job_opening/", include("client_app.staff.staff_job_opening.urls")),
    path("staff_job_application/", include("client_app.staff.staff_job_application.urls")),
    path("staff_employee_feedback/", include("client_app.staff.staff_employee_feedback.urls")),
    path("staff_bulletin/", include("client_app.staff.staff_bulletin.urls")),
    path("staff_suggestion_box/", include("client_app.staff.staff_suggestion_box.urls")),
    path("staff_training_event/", include("client_app.staff.staff_training_event.urls")),
    path("staff_employee_files/", include("client_app.staff.staff_employee_files.urls")),
    path("staff_leave_plan/", include('client_app.staff.staff_leave_plan.urls')),
    path("staff_performance_agreement/", include('client_app.staff.staff_performance_agreement.urls')),
    path("resignation/", include("client_app.staff.submit_registration.urls")),
    path("training_program_application_form/", include("client_app.staff.training_program_application_form.urls")),
    path("staff_overtime/", include("client_app.staff.staff_overtime.urls")),
    path("staff_commission/", include("client_app.staff.staff_commission.urls")),
    path("staff_bid/", include("client_app.staff.staff_bid.urls")),
    path("staff_bid_evaluation/", include("client_app.staff.staff_bid_evaluation.urls")),
    path("staff_leave_commutation/", include("client_app.staff.staff_leave_commutation.urls")),
    path("staff_exit_interview_questionnair/", include("client_app.staff.staff_exit_interview_questionnair.urls")),
    path("staff_skill_profile/", include("client_app.staff.staff_skill_profile.urls")),
    path("staff_welfare/", include("client_app.staff.staff_welfare.urls")),
    path("staff_employee_welfare_feedback/", include("client_app.staff.staff_employee_welfare_feedback.urls")),
    # path("resignation/", include("client_app.staff.staff_commission.urls")),
    path("training_program_feedback/", include("client_app.staff.training_program_feedback.urls")),
    path("employee_task/", include("client_app.staff.employee_task.urls")),
    path("staff_reports/", include ("client_app.staff.staff_reports.urls")),
    path("approval/", include ("client_app.staff.approval.urls")),
    path("staff_petty_cash/", include("client_app.staff.staff_petty_cash.urls")),
    path("staff_training_resources/", include("client_app.staff.staff_training_resources.urls")),
    path("staff_interview_evaluator/", include("client_app.staff.staff_interview_evaluator.urls")),
    # path("transport_request/", include("client_app.staff.transport_request.urls")),
    path("staff_house_loan_application/", include("client_app.staff.staff_house_loan_application.urls")),
    path("house_loan_agreement/", include("client_app.payroll.house_loan_agreement.urls")),
    path("staff_statement_form/", include("client_app.staff.staff_statement_form.urls")),
    path("skills_gap/", include("client_app.staff.skills_gap.urls")),
    path("staff_clearance_form/", include("client_app.staff.staff_clearance_form.urls")),
    path("staff_ecz_imprest_retirement/", include("client_app.staff.staff_ecz_imprest_retirement.urls")),
    path('charge/', include('client_app.staff.charge.urls')),
    path('staff_verbal_warning/', include('client_app.staff.staff_verbal_warning.urls')),
    path ('graduate_development_enrollment/', include('client_app.hr.graduate_development_enrollment.urls')),
    path('staff_certificate_of_service/', include('client_app.staff.staff_certificate_of_service.urls')),
    path('staff_authority_to_council_car/', include('client_app.staff.staff_authority_to_council_car.urls')),
    path('staff_sitting_allowance_claim/', include('client_app.staff.staff_sitting_allowance_claim.urls')),
    path('staff_membership_subscription/', include('client_app.staff.staff_membership_subscription.urls')),
    path('staff_transport_request/', include('client_app.staff.staff_transport_request.urls')),
    path('staff_id_card/', include('client_app.staff.staff_id_card.urls')),
    path('staff_express_mail/', include('client_app.staff.staff_express_mail.urls')),
    path('staff_caveat_agreement/', include('client_app.staff.staff_caveat_agreement.urls')),
    path('staff_oath_affirmation_of_secrecy/', include('client_app.staff.staff_oath_affirmation_of_secrecy.urls')),
    path ('long_term_sponsorship/', include ('client_app.staff.slong_term_sponsorship.urls')),
    path ('witness/', include ('client_app.staff.witness.urls')),

    # NEW
    path('staff_requisition_form/', include ('client_app.hr.staff_requisition_form.urls')),
    path('job_advertisement/', include ('client_app.hr.job_advertisement.urls')),
    path('short_listed_applicants/', include ('client_app.hr.short_listed_applicants.urls')),
    path('interview_schedule/', include ('client_app.hr.interview_schedule.urls')),
    # path('interview_score_sheet/', include ('client_app.hr.interview_score_sheet.urls')),
    path('disciplinary_committee/', include ('client_app.hr.disciplinary_committee.urls')),
    path('sitting_summary/', include ('client_app.hr.sitting_summary.urls')),
    path('employee_grievance/', include ('client_app.hr.employee_grievance.urls')),
    path('personal_loan_agreement/', include ('client_app.hr.personal_loan_agreement.urls')),
    path ('application_for_a_personal/', include ('client_app.payroll.application_for_a_personal.urls')), 
    path('imprest_a/', include ("client_app.payroll.imprest_a.urls")),
    path('imprest_b/', include ('client_app.payroll.imprest_b.urls')), 
    path('imprest_c/', include ('client_app.payroll.imprest_c.urls')), 
    path('cash_repayment/', include ('client_app.payroll.cash_repayment.urls')),  
    path('petty_cash/', include ('client_app.payroll.petty_cash.urls')),
    path('staff_expense_retirement/', include ('client_app.payroll.staff_expense_retirement.urls')),
    path ('interview_panel/', include('client_app.hr.interview_panel.urls') ),
    path ('interview/', include ('client_app.hr.interview.urls')),   
    path ('interview_rating/', include('client_app.hr.interview_rating.urls')),   
    path ('job_application/', include ('client_app.hr.job_application.urls')),
    path ('advance_application/', include ('client_app.payroll.advance_application.urls')),
    path ('tution_adavance_of_salary/', include('client_app.hr.tution_advance_of_salary.urls')),
    path ('overtime_claim', include ("client_app.payroll.overtime_claim.urls")),
    path ("appeal/", include("client_app.hr.appeal.urls")),
    path('acting_appointment/', include('client_app.hr.acting_appointment.urls')),
    # path ("cash_repayment/", include("client_app.hr.cash_repayment.urls")),
    path('employee_transfer_memo/', include('client_app.hr.employee_transfer_memo.urls')),
]
