export default {
    sales_invoice: {
        endpoint: "https://sandbox.startappsolutions.com/api/post-data/",
        headers:{
            "api-key": "5YpOnhI5vEjAUdBQ7w6v4JxWcto8pb4p2",
            "model": "Smart_Invoice_Sale"
        },
        req: {
            "customer": "Smart Invoice Customer",
            "customer_tpin":"2001704506",
            "currency": "ZMW",
            "exchange_rate": 1,
            "payment_type": "",
            "__lpo_no": 123456789,
            "_destination_country": "united states",
            "line_items": [
                {
                    "item_name": "Software Development",
                    "item_code": 10103303913038,
                    "qty": 5,
                    "unit_price": 100,
                    "discount_percentage": 10.7,
                    "packing_unit": "Per Kilogram",
                    "quantity_unit": "cell",
                    "vat_type": "VAT standard rated goods",
                    "_excise_duty_type": "Excise on coal",
                    "tourism_levy_type": "Tourism levy",
                    "_insurance_premium_type": "re-Insurance"
                }
            ]
        },
        res: {
            "status": 200,
            "data": {
                "id": 933,
                "docstatus": 0,
                "owner": "admin@startappsolutions.com",
                "modified_by": "admin@startappsolutions.com",
                "idx": 0,
                "disabled": 0,
                "status": "Draft",
                "doctype": "Tax_Invoice",
                "name": "INV-2024-0588",
                "issue_date": "2024-08-18",
                "due_date": "2024-09-17",
                "issue_time": "2024-08-18T18:33:02Z",
                "reporting_currency": "ZMW",
                "currency": "ZMW",
                "convertion_rate": 1.0,
                "po_no": null,
                "from_quotation": null,
                "payment_term": null,
                "customer": "Bruce Chikola",
                "customer_tax_identification_no": "2001704506",
                "customer_email": "chikolabruce23@gmail.com",
                "customer_contact_no": "0987654321",
                "customer_physical_address": "Lusaka, Off Mass Media",
                "customer_postal_address": "10101",
                "customer_currency": "USD",
                "sales_person": null,
                "company": "ECZ HRMIS",
                "company_tax_identification_no": "",
                "company_physical_address": "Lusaka, Off Mass media",
                "company_postal_address": "1001697453",
                "update_stock": null,
                "is_return": null,
                "credit_note": null,
                "description": "\nNone ",
                "cost_center": "ECZ HRMIS Main",
                "destination_country": null,
                "sale_type": null,
                "target_country": null,
                "sales_order": null,
                "proforma_invoice": null,
                "po_reference_no": null,
                "total_qty": 1,
                "base_sub_total_amount": 100.0,
                "base_total_discount_amount": 0.0,
                "base_tax_exclusive_total_amount": 100.0,
                "base_total_taxes_amount": 16.0,
                "base_inclusive_total_amount": 116.0,
                "base_total_paid_amount": 0.0,
                "base_total_outstanding_amount": 116.0,
                "sub_total_amount": 100.0,
                "total_discount_amount": 0.0,
                "tax_exclusive_total_amount": 100.0,
                "total_taxes_amount": 16.0,
                "inclusive_total_amount": 116.0,
                "total_paid_amount": 0.0,
                "total_outstanding_amount": 116.0,
                "inclusive_in_words": null,
                "receivables_account": "Trade Receivables",
                "rcpt_no": null,
                "intrl_data": null,
                "rcpt_sign": null,
                "vsdc_rcpt_pbct_date": null,
                "sdc_id": null,
                "mrc_no": null,
                "qr_code_url": null,
                "qr_code_img": null,
                "lpo_no": null,
                "created_on": "2024-08-18",
                "creation_time": "2024-08-18T18:33:02.490Z",
                "last_modified": "2024-08-18",
                "linked_fields": {
                    "owner": {
                        "id": 1,
                        "last_login": null,
                        "is_superuser": false,
                        "docstatus": 0,
                        "owner": null,
                        "modified_by": 1,
                        "disabled": 0,
                        "status": 8,
                        "doctype": "Lite_User",
                        "name": "admin@startappsolutions.com",
                        "email": "admin@startappsolutions.com",
                        "first_name": "Administrator",
                        "middle_name": "",
                        "last_name": "",
                        "contact_no": "0987654321",
                        "department": "Development",
                        "gender": "",
                        "main_role": "Super Admin 2",
                        "default_company": "ECZ HRMIS",
                        "dp": "/media/startapperp.com/private/test2_KeCwQpa.avif",
                        "is_onboarded": 1,
                        "has_changed_default_password": 1,
                        "is_active": true,
                        "is_staff": false,
                        "user_permissions": "[]",
                        "groups": "[]"
                    },
                    "modified_by": {
                        "id": 1,
                        "last_login": null,
                        "is_superuser": false,
                        "docstatus": 0,
                        "owner": null,
                        "modified_by": 1,
                        "disabled": 0,
                        "status": 8,
                        "doctype": "Lite_User",
                        "name": "admin@startappsolutions.com",
                        "email": "admin@startappsolutions.com",
                        "first_name": "Administrator",
                        "middle_name": "",
                        "last_name": "",
                        "contact_no": "0987654321",
                        "department": "Development",
                        "gender": "",
                        "main_role": "Super Admin 2",
                        "default_company": "ECZ HRMIS",
                        "dp": "/media/startapperp.com/private/test2_KeCwQpa.avif",
                        "is_onboarded": 1,
                        "has_changed_default_password": 1,
                        "is_active": true,
                        "is_staff": false,
                        "user_permissions": "[]",
                        "groups": "[]"
                    },
                    "status": {
                        "id": 7,
                        "docstatus": 0,
                        "initial_docstatus": 0,
                        "doctype": "Doc_Status",
                        "idx": 0,
                        "disabled": 0,
                        "name": "Draft",
                        "status_color": "#F2BDED",
                        "inner_color": "#840E8C"
                    },
                    "reporting_currency": {
                        "id": 139,
                        "docstatus": 0,
                        "owner": 1,
                        "modified_by": 1,
                        "idx": 0,
                        "disabled": 0,
                        "status": 8,
                        "doctype": "Currency",
                        "company_id": null,
                        "name": "ZMW",
                        "country": 3,
                        "fraction": null,
                        "symbol": "ZMW",
                        "include_in_forex_table": 0,
                        "include_in_quick_rates": 0
                    },
                    "currency": {
                        "id": 139,
                        "docstatus": 0,
                        "owner": 1,
                        "modified_by": 1,
                        "idx": 0,
                        "disabled": 0,
                        "status": 8,
                        "doctype": "Currency",
                        "company_id": null,
                        "name": "ZMW",
                        "country": 3,
                        "fraction": null,
                        "symbol": "ZMW",
                        "include_in_forex_table": 0,
                        "include_in_quick_rates": 0
                    },
                    "customer": {
                        "id": 1,
                        "docstatus": 0,
                        "owner": 1,
                        "modified_by": 1,
                        "idx": 0,
                        "disabled": 0,
                        "status": 8,
                        "doctype": "Customer",
                        "company_id": null,
                        "name": "Bruce Chikola",
                        "tax_identification_no": "2001704506",
                        "registration_type": 12,
                        "industry": 572,
                        "sector": 5,
                        "country": 3,
                        "province": 1,
                        "city": 1,
                        "email": "chikolabruce23@gmail.com",
                        "contact_no": "0987654321",
                        "physical_address": "Lusaka, Off Mass Media",
                        "postal_address": "10101",
                        "reporting_currency": 5,
                        "registration_no": "84736538784394",
                        "bank_name": "",
                        "bank_account_no": "908765432",
                        "bank_branch_code": "87654323",
                        "bank_swift_code": "",
                        "bank_sort_code": "",
                        "customer_logo": null
                    },
                    "customer_currency": {
                        "id": 5,
                        "docstatus": 0,
                        "owner": 1,
                        "modified_by": 1,
                        "idx": 0,
                        "disabled": 0,
                        "status": 8,
                        "doctype": "Currency",
                        "company_id": null,
                        "name": "USD",
                        "country": 15,
                        "fraction": null,
                        "symbol": "USD",
                        "include_in_forex_table": 1,
                        "include_in_quick_rates": 1
                    },
                    "company": {
                        "id": 1,
                        "docstatus": 0,
                        "owner": 1,
                        "modified_by": 1,
                        "idx": 0,
                        "disabled": 0,
                        "status": 8,
                        "doctype": "Company",
                        "company_id": null,
                        "name": "ECZ HRMIS",
                        "industry": 572,
                        "sector": 6,
                        "country": 3,
                        "state": null,
                        "city": 1,
                        "tax_identification_no": "",
                        "email": "demo@gmail.com",
                        "contact_no": "260776975855",
                        "physical_address": "Lusaka, Off Mass media",
                        "postal_address": "1001697453",
                        "reporting_currency": 139,
                        "is_group_company": 0,
                        "company_logo": "/media/startapperp.com/private/darklogo_g09SNzA.png"
                    },
                    "cost_center": {
                        "id": 1,
                        "docstatus": 0,
                        "owner": 1,
                        "modified_by": 1,
                        "idx": 0,
                        "disabled": 0,
                        "status": 8,
                        "doctype": "Cost_Center",
                        "name": "ECZ HRMIS Main",
                        "parent_cost_center": null,
                        "project": null,
                        "customer": null,
                        "company": 1,
                        "is_group": null
                    },
                    "receivables_account": {
                        "id": 9,
                        "docstatus": 0,
                        "owner": 1,
                        "modified_by": 1,
                        "idx": 0,
                        "disabled": 0,
                        "status": 8,
                        "doctype": "Account",
                        "name": "Trade Receivables",
                        "account_number": "1/4",
                        "parent_account": 1,
                        "is_root": 0,
                        "is_group": 0,
                        "frozen": null,
                        "root_type": 4,
                        "account_type": 18,
                        "company": 1,
                        "currency": 139
                    }
                },
                "status_info": {
                    "id": 7,
                    "docstatus": 0,
                    "initial_docstatus": 0,
                    "doctype": "Doc_Status",
                    "idx": 0,
                    "disabled": 0,
                    "name": "Draft",
                    "status_color": "#F2BDED",
                    "inner_color": "#840E8C"
                },
                "line_items": [
                    {
                        "id": 89,
                        "docstatus": 0,
                        "owner": "admin@startappsolutions.com",
                        "modified_by": "admin@startappsolutions.com",
                        "idx": 0,
                        "disabled": 0,
                        "status": "Draft",
                        "parent_type": "Tax_Invoice",
                        "parent": "INV-2024-0588",
                        "doctype": "Tax_Invoice_Item",
                        "item_name": "Iphone",
                        "item_code": "Iphone",
                        "item_type": "Physical Stock",
                        "qty": 1,
                        "description": "",
                        "unit_price": 100.0,
                        "exclusive": 100.0,
                        "discount_percentage": 0.0,
                        "discount_amount": 0.0,
                        "tax_type": "VAT Standard Rated Goods",
                        "tax_percentage": 0.0,
                        "tax_amount": 16.0,
                        "inclusive": 116.0,
                        "created_on": "2024-08-18",
                        "creation_time": "2024-08-18T18:33:02.607Z",
                        "linked_fields": {
                            "owner": {
                                "id": 1,
                                "last_login": null,
                                "is_superuser": false,
                                "docstatus": 0,
                                "owner": null,
                                "modified_by": 1,
                                "disabled": 0,
                                "status": 8,
                                "doctype": "Lite_User",
                                "name": "admin@startappsolutions.com",
                                "email": "admin@startappsolutions.com",
                                "first_name": "Administrator",
                                "middle_name": "",
                                "last_name": "",
                                "contact_no": "0987654321",
                                "department": "Development",
                                "gender": "",
                                "main_role": "Super Admin 2",
                                "default_company": "ECZ HRMIS",
                                "dp": "/media/startapperp.com/private/test2_KeCwQpa.avif",
                                "is_onboarded": 1,
                                "has_changed_default_password": 1,
                                "is_active": true,
                                "is_staff": false,
                                "user_permissions": "[]",
                                "groups": "[]"
                            },
                            "modified_by": {
                                "id": 1,
                                "last_login": null,
                                "is_superuser": false,
                                "docstatus": 0,
                                "owner": null,
                                "modified_by": 1,
                                "disabled": 0,
                                "status": 8,
                                "doctype": "Lite_User",
                                "name": "admin@startappsolutions.com",
                                "email": "admin@startappsolutions.com",
                                "first_name": "Administrator",
                                "middle_name": "",
                                "last_name": "",
                                "contact_no": "0987654321",
                                "department": "Development",
                                "gender": "",
                                "main_role": "Super Admin 2",
                                "default_company": "ECZ HRMIS",
                                "dp": "/media/startapperp.com/private/test2_KeCwQpa.avif",
                                "is_onboarded": 1,
                                "has_changed_default_password": 1,
                                "is_active": true,
                                "is_staff": false,
                                "user_permissions": "[]",
                                "groups": "[]"
                            },
                            "status": {
                                "id": 7,
                                "docstatus": 0,
                                "initial_docstatus": 0,
                                "doctype": "Doc_Status",
                                "idx": 0,
                                "disabled": 0,
                                "name": "Draft",
                                "status_color": "#F2BDED",
                                "inner_color": "#840E8C"
                            },
                            "item_name": {
                                "id": 388,
                                "docstatus": 0,
                                "owner": 1,
                                "modified_by": 1,
                                "idx": 0,
                                "disabled": 0,
                                "status": 8,
                                "doctype": "Stock_Item",
                                "company_id": null,
                                "name": "Iphone",
                                "item_code": "Iphone",
                                "item_type": 1,
                                "default_unit_of_measure": 241,
                                "brand": null,
                                "unit_price": 1000.0,
                                "barcode": "1132029667144",
                                "barcode_image": "/media/startapperp.com/private/1132029667144.png",
                                "qr_code": null,
                                "description": null,
                                "tax_type": 1,
                                "reorder_point": 1,
                                "minimum_tax_value": 0.0,
                                "quantity_unit": "Cubic centimeter",
                                "packaging_unit": "Carton",
                                "item_classification": "Live misty white limonium",
                                "create_item_on_smart": null,
                                "country_of_origin": "ZAMBIA"
                            },
                            "item_type": {
                                "id": 1,
                                "docstatus": 0,
                                "owner": 1,
                                "modified_by": 1,
                                "idx": 0,
                                "disabled": 0,
                                "status": 8,
                                "doctype": "Item_type",
                                "company_id": null,
                                "name": "Physical Stock"
                            },
                            "tax_type": {
                                "id": 1,
                                "docstatus": 0,
                                "owner": 1,
                                "modified_by": 1,
                                "idx": 0,
                                "disabled": 0,
                                "status": 8,
                                "doctype": "Tax_Template",
                                "company_id": null,
                                "name": "VAT Standard Rated Goods"
                            }
                        }
                    }
                ],
                "taxes": [],
                "bank_accounts": [],
                "default_print_format": "Tax Invoice Standard Format",
                "workflow": {
                    "has_workflow": false,
                    "status": "",
                    "current_stage": {},
                    "allow_edit": true,
                    "available_actions": []
                }
            }
        }
    }
}