export default {
    setup: {
        new_form_id: 'new-module',
        info_form_id: 'module-info',
        title: "Module",
        layout_columns: 2,
        model: "Module"
    },
    fields: [
        {
            id: "name",
            fieldlabel: "Module Name",
            fieldname: "name",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Module Name",
            required: true,
            hidden: false,
            description: "Module Name",
        },
        {
            id: "title",
            fieldlabel: "Module Title",
            fieldname: "title",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Module Title",
            required: true,
            hidden: false,
            description: "Module Title",
        },
        {
            id: "icon",
            fieldlabel: "Module Icon",
            fieldname: "icon",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Module Icon",
            required: true,
            hidden: false,
            description: "Module Icon",
        },
        {
            id: "url",
            fieldlabel: "Module Url",
            fieldname: "url",
            fieldtype: "text",
            columns: 1,
            placeholder: "Enter Module Url",
            required: true,
            hidden: false,
            description: "Module Url",
        },
        {
            id: "available",
            fieldlabel: "Available",
            fieldname: "available",
            fieldtype: "check",
            columns: 1,
            placeholder: "Available",
            required: false,
            hidden: false,
            description: "Available",
        },
    ],
}