
export default {
    setup: {
        new_form_id: 'new-subscription',
        info_form_id: 'subscription-info',
        title: "Subscription",
        layout_columns: 3,
        model: "Subscription",
        allow_submit:true,
        allow_cancel:true,
        allow_delete:true
    },
    fields: [
        
        {
            id: "tenant",
            fieldlabel: "Tenat(Client)",
            fieldname: "tenant",
            fieldtype: "link",
            model:"Tenant",
            columns: 1,
            placeholder: "Select Tenant",
            required: true,
            hidden: false,
        },
        {
            id: "total_users",
            fieldlabel: "Total Users",
            fieldname: "total_users",
            fieldtype: "int",
            columns: 1,
            placeholder: "Enter Total Users",
            required: true,
            hidden: false,
            default:"0"
        },
        {
            id: "total_storage",
            fieldlabel: "Total Storage",
            fieldname: "total_storage",
            fieldtype: "int",
            columns: 1,
            placeholder: "Enter Total Storage",
            required: true,
            hidden: false,
            default:"0"
        },
        {
            id: "quotation",
            fieldlabel: "Linked Quotation",
            fieldname: "quotation",
            fieldtype: "link",
            model:"Quotation",
            columns: 1,
            placeholder: "Select Quotation",
            required: true,
            hidden: false,
        },
        {
            id: "invoice",
            fieldlabel: "Linked Tax Invoice",
            fieldname: "invoice",
            fieldtype: "link",
            model:"Tax_Invoice",
            columns: 1,
            placeholder: "Select Tax Invoice",
            required: true,
            hidden: false,
        },
        {
            id: "payment_reference",
            fieldlabel: "Receipt",
            fieldname: "receipt",
            fieldtype: "link",
            model:"Receipt",
            columns: 1,
            placeholder: "Select Receipt",
            required: true,
            hidden: false,
        },
        {
            id: "subscription_from",
            fieldlabel: "Subscription From",
            fieldname: "subscription_from",
            fieldtype: "date",
            columns: 1,
            placeholder: "Select Subscription Date",
            required: true,
            hidden: false,
        },
        {
            id: "subscription_to",
            fieldlabel: "Subscription To",
            fieldname: "subscription_to",
            fieldtype: "date",
            columns: 1,
            placeholder: "Select Subscription End Date",
            required: true,
            hidden: false,
        },
        {
            id: "frequency",
            fieldlabel: "Subscription Frequency",
            fieldname: "frequency",
            fieldtype: "select",
            columns: 1,
            placeholder: "Select Frequency",
            required: true,
            hidden: false,
            options:["Monthly", "Annually"]
        },
        {
            id: "is_active",
            fieldlabel: "Is Active",
            fieldname: "is_active",
            fieldtype: "check",
            columns: 1,
            placeholder: "Is Active",
            required: false,
            hidden: false,
        },
        {
            id: "subscription_modules",
            fieldlabel: "Subscription Modules",
            fieldname: "subscription_modules",
            fieldtype: "table",
            placeholder: "modules",
            required: true,
            hidden: false,
            fields:[
                {
                    id: "module_name",
                    fieldlabel: "Module Name",
                    fieldname: "module_name",
                    fieldtype: "link",
                    model:"Module",
                    columns: 10,
                    placeholder: "Select Module",
                    required: true,
                    hidden: false,
                },
            ]
        },
    ]
}