from django.urls import path, include

urlpatterns = [
   path ('', include ('client_app.hr.hr_dashboard.urls')),
   path ('hr_dashboard', include ('client_app.hr.hr_dashboard.urls')),
   path ('performance_dashboard', include ('client_app.hr.performance_dashboard.urls')),
   path ('employee/', include ('client_app.hr.employee.urls')),
   path ('employee_attendance/', include ('client_app.hr.employee_attendance.urls')),
   path ('employee_checkin/', include ('client_app.hr.employee_checkin.urls')),
   path ('employment_type/', include ('client_app.hr.employment_type.urls')),
   path ('appraisal_type/', include ('client_app.hr.appraisal_type.urls')),
   path ('employee_promotion/', include ('client_app.hr.employee_promotion.urls')),
   path ('leave_type/', include ('client_app.hr.leave_type.urls')),
   path ('leave_compensation/', include ('client_app.hr.leave_compensation.urls')),
   path ('leave_entry/', include ('client_app.hr.leave_entry.urls')),
   path ('leave_compensation/', include ('client_app.hr.leave_compensation.urls')),
   path ('leave_policy/', include ('client_app.hr.leave_policy.urls')),
   path ('designation/', include ('client_app.hr.designation.urls')),
   path ('leave_application/', include ('client_app.hr.leave_application.urls')),
   path ('leave_allocation/', include ('client_app.hr.leave_allocation.urls')),
   path ('performance_agreement/', include ('client_app.hr.performance_agreement.urls')),
   path ('appraisal/', include ('client_app.hr.appraisal.urls')),
   path ('appraisal_question/', include ('client_app.hr.appraisal_question.urls')),
   path ('appraisal_quarter/', include ('client_app.hr.appraisal_quarter.urls')),
   path ('self_appraisal_setup/', include ('client_app.hr.self_appraisal_setup.urls')),
   path ('self_appraisal/', include ('client_app.hr.self_appraisal.urls')),
   path ('leave/', include ('client_app.hr.leave.urls')),
   path ('leave_plan/', include ('client_app.hr.leave_plan.urls')),
   path ('leave_schedule/', include ('client_app.hr.leave_schedule.urls')),
   path ('hr_reports/', include ('client_app.hr.hr_reports.urls')),
   path ('work_plan/', include ('client_app.hr.work_plan.urls')),
   path ('staffing_plan/', include ('client_app.hr.staffing_plan.urls')),
   path ('job_advertisement/', include ('client_app.hr.job_advertisement.urls')),
   path ('job_application/', include ('client_app.hr.job_application.urls')),
   path ('job_offer/', include ('client_app.hr.job_offer.urls')),
   path ('interview_type/', include ('client_app.hr.interview_type.urls')),
   path ('interview_schedule/', include ('client_app.hr.interview_schedule.urls')),
   path ('interview/', include ('client_app.hr.interview.urls')),
   path ('interview_feedback/', include ('client_app.hr.interview_feedback.urls')),
   path ('interview_schedule/', include ('client_app.hr.interview_schedule.urls')),
   path ('appointment_letter/', include ('client_app.hr.appointment_letter.urls')),
   path ('memo/', include ('client_app.hr.memo.urls')),
   path ('query/', include ('client_app.hr.query.urls')),
   path ('announcement/', include('client_app.hr.announcement.urls')),
   path ('company_policies/', include ('client_app.hr.company_policies.urls')),
   path ('employee_feedback/', include ('client_app.hr.employee_feedback.urls')),
   path ('grievance_type/', include ('client_app.hr.grievance_type.urls')),
   path ('employee_grievance/', include ('client_app.hr.employee_grievance.urls')),
   path ('skill_levy/', include ('client_app.hr.skill_levy.urls')),
   path ('training_program/', include ('client_app.hr.training_program.urls')),
   path ('training_event/', include ('client_app.hr.training_event.urls')),
   path ('training_feedback/', include ('client_app.hr.training_feedback.urls')),
   path ('training_result/', include ('client_app.hr.training_result.urls')),
   path ('employee_separation/', include ('client_app.hr.employee_separation.urls')),
   path ('exit_interview/', include ('client_app.hr.exit_interview.urls')),
   path ('violation_type/', include ('client_app.hr.violation_type.urls')),
   path ('employee_disciplinary/', include ('client_app.hr.employee_disciplinary.urls')),
   path ('case_outcome/', include ('client_app.hr.case_outcome.urls')),
   path ('bulletin/', include('client_app.hr.bulletin.urls')),
   path ('suggestion_category/', include('client_app.hr.suggestion_category.urls')),
   path ('suggestion_box/', include('client_app.hr.suggestion_box.urls')),
   path ('final_statement/', include('client_app.hr.final_statement.urls')),
   path ('employee_files/', include('client_app.hr.employee_files.urls')),
   path ('employee_profile/', include('client_app.hr.employee_profile.urls')),
   path ('appraisal_setup/', include ('client_app.hr.appraisal_setup.urls')),
   path ('training_program_application/', include ('client_app.hr.training_program_application.urls')),
   path ('training_program_type/', include ('client_app.hr.training_program_type.urls')),
   path ('bonus/', include ('client_app.hr.bonus.urls')),
   path ('bonus_planing/', include ('client_app.hr.bonus_planing.urls')),
   path ('bonus_types/', include ('client_app.hr.bonus_types.urls')),
   path ('bonus_weightage/', include ('client_app.hr.bonus_weightage.urls')),
   path ('bonus_weightage/', include ('client_app.hr.bonus_threshold.urls')),
   path ('hr_settings/', include ('client_app.hr.hr_settings.urls')),
   path ('contract_type/', include ('client_app.hr.contract_type.urls')),
   path ('gratuity_setup/', include ('client_app.hr.gratuity_setup.urls')),
   path ('graduate/', include ('client_app.hr.graduate.urls')),
   path ('contract/', include ('client_app.hr.hr_contract.urls')),
   path ('employee_resignation/', include ('client_app.hr.employee_resignation.urls')),
   path ('disciplinary_committee/', include ('client_app.hr.disciplinary_committee.urls')),
   path ('leave_dashboard/', include ('client_app.hr.leave_dashboard.urls')),
   path ('recruitment_dashboard/', include ('client_app.hr.recruitment_dashboard.urls')),
   path ('industrial_relations_dashboard/', include ('client_app.hr.industrial_relations_dashboard.urls')),
   path ('employee_skill_distribution_dashboard', include ('client_app.hr.employee_skill_distribution_dashboard.urls')),
   path ('probation/', include('client_app.hr.probation.urls') ),
   path ('interview_panel/', include('client_app.hr.interview_panel.urls') ),
   path ('leave_commutation/', include('client_app.hr.leave_commutation.urls')),
   path ('exit_interview_questionnair/', include('client_app.hr.exit_interview_questionnair.urls')),
   path ('employee_separation_dashboard/', include('client_app.hr.employee_separation_dashboard.urls')),
   path ('training_resources/', include('client_app.hr.training_resources.urls')),
   path ('employee_welfare_dashboard/', include('client_app.hr.employee_welfare_dashboard.urls')),
   path ('welfare_type/', include('client_app.hr.welfare_type.urls')),
   path ('welfare/', include('client_app.hr.welfare.urls')),
   path ('employee_welfare_feedback/', include('client_app.hr.employee_welfare_feedback.urls')),
   path ('skills/', include('client_app.hr.skills.urls')),
   path ('skills_inventory_dashboard/', include('client_app.hr.skills_inventory_dashboard.urls')),
   path ('interview_rating/', include('client_app.hr.interview_rating.urls')),
   path ('long_term_sponsorship/', include ('client_app.hr.long_term_sponsorship.urls')),
   path ('applicant_short_list/', include('client_app.hr.short_listed_applicants.urls')),
   path ('training_plan/', include ('client_app.hr.training_plan.urls')),
   path ('disciplinary_statement_form/', include('client_app.hr.disciplinary_statement_form.urls')),
   path ('hr_text_templates/', include('client_app.hr.hr_text_templates.urls')),
   path ('budget_line/', include ('client_app.hr.budget_line.urls')),
   path ('hr_budget/', include('client_app.hr.hr_budget.urls')),
   path ('clearance_form/', include('client_app.hr.clearance_form.urls')),
   path ('charge_form/', include('client_app.hr.charge_form.urls')),
   path ('authority_to_council_car/', include ('client_app.hr.authority_to_council_car.urls')),
   path ('sitting_allowance_claim/', include ('client_app.hr.sitting_allowance_claim.urls')),
   path ('verbal_warning/', include('client_app.hr.verbal_warning.urls')),
   path ('graduate_development_enrollment/', include('client_app.hr.graduate_development_enrollment.urls')),
   path ('certificate_of_service/', include('client_app.hr.certificate_of_service.urls')),
   path ('membership_subscription/', include('client_app.hr.membership_subscription.urls')),
   path ('transport_request/', include('client_app.hr.transport_request.urls')),
   path ('id_card/', include('client_app.hr.id_card.urls')),
   path ('express_mail/', include('client_app.hr.express_mail.urls')),
   path ('oath_affirmation_of_secrecy/', include('client_app.hr.oath_affirmation_of_secrecy.urls')),
   path ('caveat_agreement/', include('client_app.hr.caveat_agreement.urls')),
   path ('locations/', include('client_app.hr.locations.urls')),
   path ('personal_loan/', include('client_app.hr.personal_loan.urls')),
   path ('section/', include('client_app.hr.section.urls')),

   path('personal_loan_agreement/', include('client_app.hr.personal_loan_agreement.urls')),
   path('tution_adavance_of_salary/', include('client_app.hr.tution_advance_of_salary.urls')),
   path('staff_requisition_form/', include('client_app.hr.staff_requisition_form.urls')),
   path("separation_type/", include("client_app.hr.separation_type.urls")),
   path("exit_interview_question/", include("client_app.hr.exit_interview_question.urls")),
   path("offence/", include("client_app.hr.offence.urls")),
   path("sanction_type/", include("client_app.hr.sanction_type.urls")),
   path("offence_category/", include("client_app.hr.offence_category.urls")),
   path("sitting_summary/", include("client_app.hr.sitting_summary.urls")),
   path("appeal/", include("client_app.hr.appeal.urls")),
   path("department/", include("client_app.core.department.urls")),
   path('acting_appointment/', include('client_app.hr.acting_appointment.urls')),
   path('employee_transfer_memo/', include('client_app.hr.employee_transfer_memo.urls')),
   path('salary_increment/', include('client_app.hr.salary_increment.urls')),
]