leave_type= {
    "model":"Leave_Type",
    "data": [
        {
            "name": "Mothers Day",
            "maximum_leave_allocated": 1,
            "total_days_allocated_per_month": 1,
            "is_compensatory": 1,
            "apply_on": "Female",
            "leave_days_type": "Working Days",
            "accrual_frequency": "Monthly",
            "leave_type_year": "Calendar Year",
            "is_commutable": 0,
            "maximum_commutable_days": 0,
            "is_on_probation": 0,
            "show_on_payslip": 0,
            "allow_system_auto_accrual": 1,
        },
        {
            "name": "Annual Leave",
            "maximum_leave_allocated": 2,
            "total_days_allocated_per_month": 2,
            "apply_on": "Both",
            "leave_days_type": "Working Days",
            "accrual_frequency": "Monthly",
            "leave_type_year": "Employee Year",
            "carry_forward": 1,
            "is_commutable": 1,
            "maximum_commutable_days": 24,
            "is_on_probation": 0,
            "show_on_payslip": 1,
            "allow_system_auto_accrual": 1,
        },
        {
            "name": "Maternity Leave",
            "maximum_leave_allocated": 98,
            "total_days_allocated_per_month": 98,
            "apply_on": "Female",
            "leave_days_type": "Working Days",
            "accrual_frequency": "Annually",
            "leave_type_year": "Employee Year",
            "carry_forward": 0,
            "maximum_carry_forward_days": 0,
            "is_commutable": 0,
            "maximum_commutable_days": 0,
            "is_on_probation": 0,
            "show_on_payslip": 0,
            "allow_system_auto_accrual": 1,
        },
        {
            "name": "Paternity Leave",
            "maximum_leave_allocated": 5,
            "total_days_allocated_per_month": 5,
            "apply_on": "Male",
            "leave_days_type": "Working Days",
            "accrual_frequency": "Annually",
            "leave_type_year": "Employee Year",
            "carry_forward": 0,
            "maximum_carry_forward_days": 0,
            "is_commutable": 0,
            "maximum_commutable_days": 0,
            "is_on_probation": 0,
            "show_on_payslip": 0,
            "allow_system_auto_accrual": 1,
        },
        {
            "name": "Study Leave",
            "maximum_leave_allocated": 14,
            "total_days_allocated_per_month": 14,
            "apply_on": "Both",
            "leave_days_type": "Working Days",
            "accrual_frequency": "Annually",
            "leave_type_year": "Calendar Year",
            "carry_forward": 0,
            "maximum_carry_forward_days": 0,
            "is_commutable": 0,
            "maximum_commutable_days": 0,
            "is_on_probation": 0,
            "show_on_payslip": 0,
            "allow_system_auto_accrual": 1,
        },
        {
            "name": "Compassionate Leave",
            "maximum_leave_allocated": 10,
            "total_days_allocated_per_month": 10,
            "apply_on": "Both",
            "leave_days_type": "Working Days",
            "accrual_frequency": "Annually",
            "leave_type_year": "Calendar Year",
            "carry_forward": 0,
            "maximum_carry_forward_days": 0,
            "is_commutable": 0,
            "maximum_commutable_days": 0,
            "is_on_probation": 0,
            "show_on_payslip": 0,
            "allow_system_auto_accrual": 1,
        },
         {
            "name": "Family Responsibility Leave",
            "maximum_leave_allocated": 3,
            "total_days_allocated_per_month": 3,
            "leave_days_type": "Working Days",
            "accrual_frequency": "Annually",
            "leave_type_year": "Calendar Year",
            "carry_forward": 0,
            "maximum_carry_forward_days": 0,
            "is_commutable": 0,
            "maximum_commutable_days": 0,
            "is_on_probation": 0,
            "show_on_payslip": 0,
            "allow_system_auto_accrual": 1,
        },
        {
            "name": "Sick Leave",
            "maximum_leave_allocated": 180,
            "total_days_allocated_per_month": 180,
            "apply_on": "Both",
            "leave_days_type": "Calendar Days",
            "accrual_frequency": "Annually",
            "leave_type_year": "Calendar Year",
            "carry_forward": 0,
            "maximum_carry_forward_days": 0,
            "is_commutable": 0,
            "maximum_commutable_days": 0,
            "is_on_probation": 0,
            "show_on_payslip": 0,
            "allow_system_auto_accrual": 1,
        },      
    ]
}