from django.urls import path, include
urlpatterns = [
    path('', include('client_app.core.core_dashboard.urls'), name='core_dashboard'),
    path('core_dashboard', include('client_app.core.core_dashboard.urls'), name='core_dashboard'),
    path('company/', include('client_app.core.company.urls'), name='company_dashboard'),
    path('cost_center/', include('client_app.core.cost_center.urls'), name='cost_center_dashboard'),
    path('country/', include('client_app.core.country.urls'), name='country_dashboard'),
    path('currency/', include('client_app.core.currency.urls'), name='currency_dashboard'),
    path('industry/', include('client_app.core.industry.urls'), name='industry_dashboard'),
    path('sector/', include('client_app.core.sector.urls'), name='sector_dashboard'),
    path('state/', include('client_app.core.state.urls'), name='state_dashboard'),
    path('city/', include('client_app.core.city.urls'), name='city_dashboard'),
    path('district/', include('client_app.core.district.urls'), name='district_dashboard'),
    path('province/', include('client_app.core.province.urls'), name='province_dashboard'),
    path('rating/', include('client_app.core.rating.urls'), name='rating'),
    path('branch/', include('client_app.core.branch.urls'), name='branch_dashboard'),
    path('gender/', include('client_app.core.gender.urls'), name='gender_dashboard'),
    path('location/', include('client_app.core.location.urls'), name='location_dashboard'),
    path('system_settings/', include('client_app.core.system_settings.urls'), name='system_settings_dashboard'),
    path('series/', include('client_app.core.series.urls'), name='series_dashboard'),
    path('doc_status/', include('client_app.core.doc_status.urls'), name='doc_status_dashboard'),
    path('data_importation/', include('client_app.core.data_importation.urls'), name='data_importation_dashboard'),
    path('print_configuration/', include('client_app.core.print_configuration.urls'), name='print_configuration_dashboard'),
    path('print_format/', include('client_app.core.print_format.urls'), name='print_format_dashboard'),
    path('print_doc/', include('client_app.core.print_doc.urls'), name='data_importation_dashboard'),
    path('user/', include('client_app.core.user.urls'), name='user'),
    path('role/', include('client_app.core.role.urls'), name='role'),
    path('workflow/', include('client_app.core.workflow.urls'), name='workflow'),
    path('advanced_access_control/', include('client_app.core.advanced_access_control.urls'), name='advanced_access_control'),
    path('email_config/', include('client_app.core.email_config.urls'), name='email_config'),
    path ("priority/", include("client_app.core.priority.urls")),
    path ("working_hours/", include("client_app.core.working_hours.urls")),
    path ('department/', include ('client_app.core.department.urls')),
    path('otp/', include('client_app.core.otp.urls'), name='otp'),
    path('share_management/', include('client_app.core.share_management.urls'), name='share_management'),
    path('default_dashboard/', include('client_app.core.default_dashboard.urls'), name='default_dashboard'),
    path('audit_trail/', include('client_app.core.audit_trail.urls'),),
    path('disabled_document/', include('client_app.core.disabled_document.urls'),),
    path('deleted_document/', include('client_app.core.deleted_document.urls'),),
    path('menu_card/', include('client_app.core.menu_card.urls'),),
    path('form_customization/', include('client_app.core.form_customization.urls'),),
    path('files/', include('client_app.core.files.urls'),),
    path('auth_trail/', include('client_app.core.core_reports.auth_trail.urls'),),
    path('audit_trail_report/', include('client_app.core.core_reports.audit_trail_report.urls'),),
    path('template_content/', include('client_app.core.template_content.urls'),),
]
