export default {
    setup: {
        new_form_id: 'new-overtime',
        info_form_id: 'overtime-info',
        title: "Overtime CLaim",
        layout_columns: 3,
        model: "Overtime_CLaim",
        allow_submit: true,
        allow_cancel: true,
        allow_delete: false,
        allow_print: false,
        allow_sending_mail: false,
    },
    fields: [
        {
            id: "employee",
            fieldlabel: "Employee No",
            fieldname: "employee",
            fieldtype: "link",
            model: "Employee",
            columns: 1,
            required: true,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "fullname",
            fieldlabel: "Full Names",
            fieldname: "fullname",
            fieldtype: "text",
            placeholder: " ",
            columns: 1,
            required: true,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "full_name",
        },
        {
            id: "salary_grade",
            fieldlabel: "Salary Grade",
            fieldname: "salary_grade",
            fieldtype: "rea-only",
            placeholder: " ",
            columns: 1,
            required: true,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "employee_grade",
        },
        {
            id: "designation",
            fieldlabel: "Job Title",
            fieldname: "designation",
            fieldtype: "rea-only",
            placeholder: " ",
            columns: 1,
            required: true,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "designation",
        },
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "rea-only",
            placeholder: " ",
            columns: 1,
            required: true,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "department",
        },
        {
            id: "month",
            fieldlabel: "Month",
            fieldname: "month",
            fieldtype: "select",
            options: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "attachment",
            fieldlabel: "Attach any supporting Document",
            fieldname: "attachment",
            fieldtype: "file",
            columns: 1,
            required: false,
            hidden: false,
        },
        
        {
            id: "purpose",
            fieldlabel: "Details of the Work",
            fieldname: "purpose",
            fieldtype: "rich",
            columns: 3,
            height: 200,
            required: true,
            hidden: false,
            placeholder: " ",

        },
        {
            id: "overtime_worked",
            fieldlabel: "Overtime Breakdown",
            fieldname: "overtime_worked",
            fieldtype: "table",
            columns: 4,
            required: false,
            hidden: false,
            model: "Overtime_Worked",
            fields: [
                {
                    id: "day",
                    fieldlabel: "Day",
                    fieldname: "day",
                    fieldtype: "text",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "date_of_work",
                    fieldlabel: "Date",
                    fieldname: "date_of_work",
                    fieldtype: "date",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "from_time",
                    fieldlabel: "From Time",
                    fieldname: "from_time",
                    fieldtype: "time",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "to_time",
                    fieldlabel: "To Time",
                    fieldname: "to_time",
                    fieldtype: "time",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "total_hours",
                    fieldlabel: "Total Hours",
                    fieldname: "total_hours",
                    fieldtype: "text",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "rate",
                    fieldlabel: "Rate",
                    fieldname: "rate",
                    fieldtype: "text",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "total_amount",
                    fieldlabel: "Total Amount",
                    fieldname: "total_amount",
                    fieldtype: "text",
                    columns: 4,
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
            ]
        },
    ],
}