;
export default {
    setup: {
        new_form_id: 'new-overtime-setup',
        info_form_id: 'overtime-setup-info',
        title: "Overtime Configuration",
        layout_columns: 6,
        model: "Overtime_Configuration"
    },
    fields:[
        {
            id: "name",
            fieldlabel: "Name",
            fieldname: "name",
            fieldtype: "text",
            columns: 2,
            required: true,
            hidden: true,
            placeholder: " ",
        },
        {
            id: "calculation_type",
            fieldlabel: "Calculation Scheme",
            fieldname: "calculation_type",
            fieldtype: "select",
            options: ["Fixed Rate", "Salary Based",],
            columns: 2,
            required: true,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "fixed_rate",
            fieldlabel: "Fixed Rate Amount Per Hour",
            fieldname: "fixed_rate",
            fieldtype: "float",
            columns: 2,
            required: false,
            hidden: false,
            placeholder: " ",
            displayon: ["calculation_type","Fixed Rate"],
            default:"0.00"
        },
        {
            id: "salary_type",
            fieldlabel: "Salary Type",
            fieldname: "salary_type",
            fieldtype: "read-only",
            columns: 2,
            required: true,
            hidden: false,
            placeholder: " ",
            default: "Basic",
            displayon: ["calculation_type","Salary Based"]
        },
        {
            id: "number_of_hours",
            fieldlabel: "Number of Working Hours",
            fieldname: "number_of_hours",
            fieldtype: "text",
            columns: 2,
            required: false,
            hidden: false,
            placeholder: " ",
            displayon: ["calculation_type","Salary Based"]
        },
        {
            id: "sc1",
            fieldlabel: "",
            fieldname: "sc1",
            fieldtype: "section-break",
            columns: 2,
            border: true
        },
        {
            id: "payment-on-payroll",
            fieldlabel: "Payment On Payroll",
            fieldname: "payment_on_payroll",
            fieldtype: "check",
            columns: 2,
            required: false,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "eligibility",
            fieldlabel: "Eligibility",
            fieldname: "eligibility",
            fieldtype: "table",
            model: "Overtime_Eligibility",
            placeholder: " ",
            required: false,
            hidden: false,
            fields: [
                {
                    id: "employment_type",
                    fieldlabel: "Employment Type",
                    fieldname: "employment_type",
                    fieldtype: "link",
                    columns: 4,
                    model: "Employment_Type",
                    placeholder: " ",
                    required: true,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "time_measure",
                    fieldlabel: "Unit of Time",
                    fieldname: "time_measure",
                    fieldtype: "select",
                    options: ["Days", "Weeks", "Months", "Years"],
                    columns: 2,
                    required: true,
                    hidden: false,
                    placeholder: " ",
                    default:`Month`,
                    istablefield: true,
                },
                {
                    id: "period_of_service",
                    fieldlabel: "Maximum Service Time",
                    fieldname: "period_of_service",
                    fieldtype: "int",
                    columns: 4,
                    model: "Employment_Type",
                    placeholder: " ",
                    required: true,
                    hidden: false,
                    istablefield: true,
                    default: 1,
                },
            ]
        },      
    ]
}