export default {
    setup: {
        new_form_id: 'new-overtime',
        info_form_id: 'overtime-info',
        title: "Overtime",
        layout_columns: 3,
        model: "Overtime",
        allow_submit: true,
        allow_cancel: true,
        allow_delete: false,
        allow_print: false,
        allow_sending_mail: false,
    },
    fields: [
        {
            id: "applicant",
            fieldlabel: "Employee No",
            fieldname: "applicant",
            fieldtype: "link",
            model: "Employee",
            addborder: true,
            placeholder: " ",
            columns: 1,
            required: true,
            hidden: false,
        },
        {
            id: "fullname",
            fieldlabel: "Full Names",
            fieldname: "fullname",
            fieldtype: "read-only",
            addborder: true,
            columns: 1,
            required: true,
            placeholder: " ",
            hidden: false,
            fetchfrom: "applicant",
            fetchfield: "full_name",
        },
        {
            id: "designation",
            fieldlabel: "Job Title",
            fieldname: "designation",
            fieldtype: "read-only",
            addborder: true,
            placeholder: " ",
            columns: 1,
            required: true,
            hidden: false,
            fetchfrom: "applicant",
            fetchfield: "designation",
        },
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "read-only",
            placeholder: " ",
            addborder: true,
            columns: 1,
            required: true,
            hidden: false,
            fetchfrom: "applicant",
            fetchfield: "department",
        },
        {
            id: "application_date",
            fieldlabel: "Date",
            fieldname: "application_date",
            placeholder: " ",
            fieldtype: "date",
            columns: 1,
            required: true,
            hidden: false,
        },
        {
            id: "from_date",
            fieldlabel: "From Date",
            fieldname: "from_date",
            fieldtype: "date",
            placeholder: " ",
            columns: 1,
            required: true,
            hidden: false,
        },
        {
            id: "to_date",
            fieldlabel: "To Date",
            fieldname: "to_date",
            fieldtype: "date",
            placeholder: " ",
            columns: 1,
            required: true,
            hidden: false,
        },
        {
            id: "supervisor",
            fieldlabel: "Officer to Supervise The Work",
            fieldname: "supervisor",
            fieldtype: "link",
            model: "Employee",
            placeholder: " ",
            columns: 1,
            required: true,
            hidden: false,
        },
        {
            id: "supervisor_name",
            fieldlabel: "Supervisors Fullname",
            fieldname: "supervisor_name",
            fieldtype: "read-only",
            columns: 1,
            required: true,
            placeholder: " ",
            hidden: false,
            fetchfrom: "supervisor",
            fetchfield: "full_name",
        },
        {
            id: "purpose",
            fieldlabel: "Details of The to Be Done",
            fieldname: "purpose",
            fieldtype: "rich",
            placeholder: " ",
            columns: 3,
            height:200,
            required: true,
            hidden: false,
        },
        {
            id: "why_working_hours",
            fieldlabel: "Reasons Why The Work Cannot Be Done During Work Hours",
            fieldname: "why_working_hours",
            fieldtype: "rich",
            columns: 3,
            placeholder: " ",
            height:200,
            required: true,
            hidden: false,
        },
        {
            id: "staff_to_work_on_overtime",
            fieldlabel: "Details of Staff Requested to Work",
            fieldname: "staff_to_work_on_overtime",
            fieldtype: "table",
            model: "Staffs_To_Work_This_Overtime",
            description: "add staff members that have been requested to work",
            placeholder: " ",
            columns: 3,
            required: true,
            hidden: false,
            fields: [
                {
                    id: "employee",
                    fieldlabel: "Staff No",
                    fieldname: "employee",
                    fieldtype: "link",
                    models: "Employee",
                    columns: 4,
                    required: true,
                    hidden: false,
                    placeholder: " ",
                },
                {
                    id: "fullname",
                    fieldlabel: "Employee Name",
                    fieldname: "fullname",
                    fieldtype: "read-only",
                    columns: 4,
                    required: true,
                    hidden: false,
                    placeholder: " ",
                    fetchfrom: "employee",
                    fetchfield: "full_name",
                },
            ]
        }
    ],
}