export default {
    setup: {
        new_form_id: 'new-pm',
        info_form_id: 'pm-info',
        title: "Professional Membership Subscription",
        layout_columns: 3,
        model: "Professional_Membership_Subscription",
        allow_submit: true,
        allow_cancel: true,
        allow_delete: false,
        allow_print: false,
        allow_sending_mail: false,
    },
    fields: [

        {
            id: "deduction_type",
            fieldlabel: "Deduction Type",
            fieldname: "deduction_type",
            fieldtype: "read-only",
            // fieldtype: "link",
            model: "Salary_Advance_Configuration",
            columns: 1,
            placeholder: " ",
            required: false,
            hidden: false,
            default: "Professional Membership Subscription",
        },
        {
            id: "employee",
            fieldlabel: "Employee No",
            fieldname: "employee",
            fieldtype: "link",
            model: "Employee",
            addborder: true,
            columns: 1,
            required: true,
            hidden: false,
            description: "Select Employee No",
            placeholder: " ",
        },
        {
            id: "fullname",
            fieldlabel: "Employee Full Name",
            fieldname: "fullname",
            fieldtype: "read-only",
            addborder: true,
            columns: 1,
            required: true,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "full_name",
        },
        {
            id: "designation",
            fieldlabel: "Job Title",
            fieldname: "designation",
            fieldtype: "read-only",
            addborder: true,
            columns: 1,
            required: true,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "designation",
        },
        {
            id: "salary_grade",
            fieldlabel: "Salary Grade",
            fieldname: "salary_grade",
            fieldtype: "read-only",
            addborder: true,
            columns: 1,
            required: true,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "employee_grade",
        },
        {
            id: "department",
            fieldlabel: "Department /  Unit",
            fieldname: "department",
            fieldtype: "read-only",
            addborder: true,
            columns: 1,
            required: true,
            hidden: false,
            fetchfrom: "employee",
            fetchfield: "department",
        },
        {
            id: "section",
            fieldlabel: "Section",
            fieldname: "section",
            fieldtype: "text",
            addborder: true,
            columns: 1,
            required: true,
            hidden: false,
        },
        {
            id: "amount",
            fieldlabel: "Requested Amount",
            fieldname: "amount",
            fieldtype: "text",
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "membership_type",
            fieldlabel: "Membership Type",
            fieldname: "membership_type",
            fieldtype: "select",
            options: ["Accounting", "Sections"],
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
          
        },
        {
            id: "ssdd",
            fieldlabel: "Professional Body Details",
            fieldname: "ssdd",
            fieldtype: "section-break",
            addborder: true,
            columns: 1,
            required: true,
            hidden: false,
        },
        {
            id: "name_of_professional_body",
            fieldlabel: "Professional Body's Name",
            fieldname: "name_of_professional_body",
            fieldtype: "text",
            addborder: true,
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "account_name",
            fieldlabel: "Account Name",
            fieldname: "account_name",
            fieldtype: "text",
            addborder: true,
            columns: 1,
            required: true,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "account_number",
            fieldlabel: "Account Number",
            fieldname: "account_number",
            fieldtype: "text",
            addborder: true,
            placeholder: " ",
            columns: 1,
            required: true,
            hidden: false,
        },
        {
            id: "account_branch_code",
            fieldlabel: "Account Branch Code/Name",
            fieldname: "account_branch_code",
            fieldtype: "text",
            addborder: true,
            columns: 1,
            placeholder: " ",
            required: true,
            hidden: false,
        },
        {
            id: "sort_code",
            fieldlabel: "Account Sort Code",
            fieldname: "sort_code",
            fieldtype: "text",
            placeholder: " ",
            addborder: true,
            columns: 1,
            required: true,
            hidden: false,
        },
        {
            id: "invoice_name",
            fieldlabel: "Invoice Name",
            fieldname: "invoice_name",
            fieldtype: "text",
            addborder: true,
            placeholder: " ",
            columns: 1,
            required: true,
            hidden: false,
        },
        {
            id: "attachment",
            fieldlabel: "Invoice Attachment",
            fieldname: "attachment",
            fieldtype: "file",
            placeholder: " ",
            addborder: true,
            columns: 1,
            required: true,
            hidden: false,
        },
    ],
}