import {apply_to_all_employees} from '../../overrides/form/payroll/core.js'
import {
    allocate_salary_component,
} from "../../overrides/form/payroll/core.js";
export default {
    setup: {
        new_form_id: 'new-salary-component',
        info_form_id: 'salary-component-info',
        title: "Salary Component",
        layout_columns: 4,
        model: "Salary_Component"
    },
    form_actions: [
        {
            title: "Allocate to All Employees",
            icon: "price_check",
            icon_color: "indigo",
            action: apply_to_all_employees,
            for_docstatus: [0],
            for_status: ["Active"],
        },
        {
            title: "Allocate to Selected Employees",
            icon: "price_check",
            icon_color: "indigo",
            action: allocate_salary_component,
            for_docstatus: [0],
            for_status: ["Active"],
        },
    ],
    fields: [
        {
            id: "name",
            fieldlabel: "Salary Component Name",
            fieldname: "name",
            columns: 1,
            required: true,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "component-type",
            fieldlabel: "Component Type",
            fieldname: "component_type",
            fieldtype: "select",
            columns: 1,
            required: true,
            hidden: false,
            placeholder: " ",
            options: ["Earning", "Deduction"]
        },
        {
            id: "value-type",
            fieldlabel: "Value Type",
            fieldname: "value_type",
            fieldtype: "select",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            options: ["Percentage","Fixed Amount", "Custom"]
        },
        {
            id: "percentage",
            fieldlabel: "Percentage",
            fieldname: "percentage",
            fieldtype: "percentage",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            classnames: "text-start",
            default: "0.00",
            displayon: ["value-type", "Percentage" ]
        },
        {
            id: "fixed-amount",
            fieldlabel: "Fixed Amount",
            fieldname: "fixed_amount",
            fieldtype: "currency",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            classnames: "text-end",
            default: "0.00",
            displayon: ["value-type","Fixed Amount"]
        },
        {
            id: "apply-on",
            fieldlabel: "Apply On",
            fieldname: "apply_on",
            fieldtype: "select",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            options:["Basic", "Gross","Net"],
            displayon:["component-type", "Deduction"]
        },
        {
            id: "sec",
            fieldlabel: "",
            fieldname: "sec",
            fieldtype: "section-break",
            placeholder: "",
        },
        {
            id: "is-standard-component",
            fieldlabel: "Is Standard Component",
            fieldname: "is_standard_component",
            fieldtype: "check",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            default: "0",
        },
        {
            id: "is-statutory-component",
            fieldlabel: "Is Statutory Component",
            fieldname: "is_statutory_component",
            fieldtype: "check",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            default: "0",
        },

        {
            id: "is_type",
            fieldlabel: "Component Purpose",
            fieldname: "is_type",
            fieldtype: "select",
            options: [
                "Overtime",
                "Advance",
                "Welfare",
                "Private Pension",
                "Commission",
                "Commutation",
            ],
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "has-ceiling",
            fieldlabel: "Has Ceiling",
            fieldname: "has_ceiling",
            fieldtype: "check",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            displayon: ["value-type", "Percentage"]
        },
        {
            id: "is-shared-deduction",
            fieldlabel: "Is Shared Deduction (50/50)",
            fieldname: "shared_deduction",
            fieldtype: "check",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            displayon:["component-type", "Deduction"]
        },
        {
            id: "is-shared-deduction-custom",
            fieldlabel: "Is Shared Deduction (Custom)",
            fieldname: "shared_deduction_custom",
            fieldtype: "check",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            displayon:["component-type", "Deduction"]
        },
        {
            id: "is-shared-deduction-custom-company",
            fieldlabel: "Employers Share (%)",
            fieldname: "shared_deduction_custom_company",
            fieldtype: "text",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            displayon:["is-shared-deduction-custom", 1]
        },
        {
            id: "is-shared-deduction-custom-emp",
            fieldlabel: "Employee Share (%)",
            fieldname: "shared_deduction_custom_emp",
            fieldtype: "text",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            displayon:["is-shared-deduction-custom", 1]
        },
        {
            id: "exclude_on_statutory_deductions",
            fieldlabel: "Exclude On Payroll Deductions and Taxes",
            fieldname: "exclude_on_statutory_deductions",
            fieldtype: "check",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            displayon:["component-type", "Earning"]
        },
        {
            id: "sec",
            fieldlabel: "",
            fieldname: "sec",
            fieldtype: "section-break",
            placeholder: "",
        },
        {
            id: "ceiling-amount",
            fieldlabel: "Ceiling Amount",
            fieldname: "ceiling_amount",
            fieldtype: "currency",
            columns: 1,
            required: false,
            hidden: false,
            placeholder: " ",
            default: "0.00",
            displayon:["has-ceiling", 1]
        },
        {
            id: "accounts",
            fieldlabel: "Component Accounts",
            fieldname: "accounts",
            fieldtype: "table",
            model: "Taxable_Salary_Band",
            description: "Add salary ranges on which tax band shall be calculated",
            required: true,
            hidden: false,
            addemptyrow: false,
            fields: [
                {
                    id: "company",
                    fieldlabel: "Company",
                    fieldname: "company",
                    fieldtype: "link",
                    model: "Company",
                    columns: 7,
                    required: true,
                    hidden: true,
                    placeholder: " ",
                    default: lite?.user?.company?.name,
                    filters: {
                        is_group: 0,
                        is_root: 0
                    }
                },
                {
                    id: "account",
                    fieldlabel: "Account",
                    fieldname: "account",
                    fieldtype: "link",
                    model: "Account",
                    columns: 7,
                    required: true,
                    hidden: false,
                    placeholder: " ",
                    filters: {
                        is_group: "0",
                    },
                },
                {
                    id: "expense-account",
                    fieldlabel: "Expense Account",
                    fieldname: "expense_account",
                    fieldtype: "link",
                    model: "Account",
                    columns: 7,
                    required: false,
                    hidden: false,
                    placeholder: " ",
                    filters: {
                        is_group: "0",
                    },
                }
            ]
        },
    ],
}