;
const user = lite.user
export default {
    setup: {
        new_form_id: 'new-advance-setup',
        info_form_id: 'advance-setup-info',
        title: "Setup",
        layout_columns: 12,
        model: "Salary_Advance_Configuration"
    },
    fields:[
        {
            id: "name",
            fieldlabel: "Setup Type Name",
            fieldname: "name",
            fieldtype: "text",
            columns: 3,
            required: true,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "advance_type",
            fieldlabel: "Select Setup Type",
            fieldname: "advance_type",
            fieldtype: "select",
            options: ["Loan", "Advance", "Subscription"],
            columns: 3,
            required: true,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "repayment_plan",
            fieldlabel: "Settlement Plan",
            fieldname: "repayment_plan",
            fieldtype: "select",
            options: ["Onces Off", "Over A Period of Time"],
            columns: 3,
            required: true,
            hidden: false,
            placeholder: " ",
            default:`Onces Off`
        },
        {
            id: "repayment_period_length",
            fieldlabel: "Settlement Period Length (Months)",
            fieldname: "repayment_period_length",
            fieldtype: "select",
            options: [1,2,3,4,5,6,7,8,9,10,11,12],
            columns: 3,
            required: false,
            hidden: false,
            placeholder: " ",
            default: 4,
            displayon: ['repayment_plan', "Over A Period of Time"]
        },
        {
            id: "maximum_open_advances",
            fieldlabel: "Maximum Open Advances/Loan",
            fieldname: "maximum_open_advances",
            fieldtype: "select",
            options: [1,2,3,4,5,6,7,8,9,10,11,12],
            columns: 3,
            required: false,
            hidden: false,
            placeholder: " ",
            default: 2,
        },
        {
            id: "max_take_home",
            fieldlabel: "Percentage of Pay After Deductions",
            fieldname: "max_take_home",
            fieldtype: "percentage",
            columns: 3,
            required: false,
            hidden: false,
            placeholder: " ",
            default: '0.00',
        },
        {
            id: "amount_value",
            fieldlabel: "Amount Value Type",
            fieldname: "amount_value",
            fieldtype: "select",
            options: ["Percentage of Basic Pay", `Employee's Full Basic`],
            columns: 3,
            required: false,
            hidden: false,
            default: "Employee's Full Basic",
            placeholder: " ",
        },
        {
            id: "amount_rate",
            fieldlabel: "Maximum Rate",
            fieldname: "amount_rate",
            fieldtype: "percentage",
            columns: 3,
            required: false,
            hidden: false,
            placeholder: " ",
            default: '0.00',
            displayon: ["amount_value", "Percentage of Basic Pay"]
        },
        {
            id: "grace_period",
            fieldlabel: "Repayment Shall Start Following Disbursement",
            fieldname: "grace_period",
            fieldtype: "select",
            options: [1,2,3,4,5,6,7,8,9,10,11,12],
            columns: 3,
            required: false,
            hidden: false,
            default: 1,
            placeholder: " ",
        },
        {
            id: "sc1",
            fieldlabel: "Configurations",
            fieldname: "sc1",
            fieldtype: "section-break",
            columns: 3,
            addborder: true
        },
        {
            id: "is_interest_applicable",
            fieldlabel: "Interest Applicable",
            fieldname: "is_interest_applicable",
            fieldtype: "check",
            columns: 3,
            required: false,
            hidden: false,
            placeholder: " ",
            displayon: ["advance_type", "Loan"]
        },
        {
            id: "has_bonding_period",
            fieldlabel: "Enable Bonding Period",
            fieldname: "has_bonding_period",
            fieldtype: "check",
            columns: 3,
            required: false,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "allowed_on_disciplinary",
            fieldlabel: "Allow Those on Discipline",
            fieldname: "allowed_on_disciplinary",
            fieldtype: "check",
            columns: 3,
            required: false,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "allowed_on_probation",
            fieldlabel: "Allow Those on Probation",
            fieldname: "allowed_on_probation",
            fieldtype: "check",
            columns: 3,
            required: false,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "sc",
            fieldlabel: "",
            fieldname: "sc",
            fieldtype: "section-break",
            columns: 2,
            addborder: true
        },
        {
            id: "interest_rate",
            fieldlabel: "Interest Rate",
            fieldname: "interest_rate",
            fieldtype: "percentage",
            columns: 3,
            required: false,
            hidden: false,
            default: '0.00',
            placeholder: " ",
            displayon: ["is_interest_applicable", 1]
        },
        {
            id: "loan_calculation_method",
            fieldlabel: "Loan Calculation Method",
            fieldname: "loan_calculation_method",
            fieldtype: "read-only",
            options: ["Simple Interest", "Compound Interest", "Amortized Loan", "Declining Balance", "Balloon Loan", "Graduated Payment Loan"],
            columns: 3,
            required: false,
            hidden: true,
            placeholder: " ",
            default: "Simple Interest",
            displayon: ['advance_type', "Loan"]
        },
        {
            id: "bonding_period",
            fieldlabel: "Bonding Period ",
            fieldname: "bonding_period",
            fieldtype: "select",
            options: ["Months", "Years"],
            columns: 3,
            required: false,
            hidden: false,
            placeholder: " ",
            default: "Years",
            displayon: ['has_bonding_period', 1]
        },
        {
            id: "bonding_period_length",
            fieldlabel: "Bonding Period Length",
            fieldname: "bonding_period_length",
            fieldtype: "text",
            columns: 3,
            required: false,
            hidden: false,
            placeholder: " ",
            default: 2,
            displayon: ['has_bonding_period', 1]
        },
        {
            id: "sww",
            fieldlabel: "Accounts",
            fieldname: "sww",
            fieldtype: "section-break",
            columns: 2,
            border: true
        },
        
        {
            id: "credit_account",
            fieldlabel: "Select Credit Account/Loan",
            fieldname: "credit_account",
            fieldtype: "link",
            model: "Account",
            filters: {
                is_group: 0
            },
            columns: 3,
            required: true,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "debit_account",
            fieldlabel: "Debit Account/Loan",
            fieldname: "debit_account",
            fieldtype: "link",
            model: "Account",
            filters: {
                is_group: 0
            },
            columns: 3,
            required: true,
            hidden: false,
            placeholder: " ",
        },
        {
            id: "credit_account_currency",
            fieldlabel: "Select Credit Account Currency",
            fieldname: "credit_account_currency",
            fieldtype: "read-only",
            columns: 3,
            required: true,
            hidden: true,
            fetchfrom:"credit_account",
            fetchfield:"currency",
            placeholder: " ",
        },
        {
            id: "debit_account_currency",
            fieldlabel: "Select Debit Account Currency",
            fieldname: "debit_account_currency",
            fieldtype: "read-only",
            columns: 3,
            required: true,
            hidden: true,
            fetchfrom:"debit_account",
            fetchfield:"currency",
            placeholder: " ",
        },

        {
            id: "reporting_currency",
            fieldlabel: "Reporting Currency",
            fieldname: "reporting_currency",
            fieldtype: "link",
            mode: "Currency",
            columns: 3,
            required: true,
            hidden: true,
            placeholder: " ",
            default: user?.company?.reporting_currency

        },
        {
            id: "sww",
            fieldlabel: "Eligibility",
            fieldname: "sww",
            fieldtype: "section-break",
            columns: 2,
            border: true
        },
        {
            id: "eligibility_type",
            fieldlabel: "Eligibility Type",
            fieldname: "eligibility_type",
            fieldtype: "select",
            options: ["All", "Customize Eligibility"],
            columns: 3,
            required: false,
            hidden: false,
            default: "All",
            placeholder: " ",
        },
        {
            id: "eligibility",
            fieldlabel: "Eligibility",
            fieldname: "eligibility",
            fieldtype: "table",
            displayon: ["eligibility_type", "Customize Eligibility"],
            model: "Salary_Advance_Eligibility",
            placeholder: "Enter Eligibility",
            required: false,
            hidden: false,
            addemptyrow: false,
            fields: [
                {
                    id: "employment_type",
                    fieldlabel: "Employment Type",
                    fieldname: "employment_type",
                    fieldtype: "link",
                    columns: 4,
                    model: "Employment_Type",
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                },
                {
                    id: "time_measure",
                    fieldlabel: "Time Measure",
                    fieldname: "time_measure",
                    fieldtype: "select",
                    options: ["Days", "Weeks", "Months", "Years"],
                    columns: 2,
                    required: false,
                    hidden: false,
                    placeholder: " ",
                    default:`Month`,
                    istablefield: true,
                },
                {
                    id: "period_of_service",
                    fieldlabel: "Time In Service",
                    fieldname: "period_of_service",
                    fieldtype: "int",
                    columns: 4,
                    model: "Employment_Type",
                    placeholder: " ",
                    required: false,
                    hidden: false,
                    istablefield: true,
                    default: 1,
                },
            ]
        },
    ]
}