doc_status = {
    "model": "Doc_Status",
    "data": [

        {"name":"Idle",  "status_color":"#D5B8E6", "inner_color":"#5208A6", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Running", "status_color":"#F2BDED", "inner_color":"#840E8C", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Exited", "status_color":"#F2BDED", "inner_color":"#840E8C", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Disabled", "status_color":"#F2BDED", "inner_color":"#840E8C", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Initialized", "status_color":"#F2BDED", "inner_color":"#840E8C", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Locked", "status_color":"#F2BDED", "inner_color":"#840E8C", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Unapproved", "status_color":"#F2BDED", "inner_color":"#840E8C", "doctype":"Doc_Status", "initial_docstatus":0},


        {"name":"Disbursed", "status_color":"#f7ece6", "inner_color":"#c77950", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Repaid", "status_color":"#e5dcf2", "inner_color":"#352375", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Partially Repaid", "status_color":"#eddcf2", "inner_color":"#8d2194", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Overdue | Partially Repaid", "status_color":"#edd8dd", "inner_color":"#c93057", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Written Off", "status_color":"#f0efd3", "inner_color":"#b0ad12", "doctype":"Doc_Status", "initial_docstatus":1},


        {"name":"Draft", "status_color":"#F2BDED", "inner_color":"#840E8C", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Active", "status_color":"#f2d7f4", "inner_color":"#810891", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Probation", "status_color":"#f2d7f4", "inner_color":"#810891", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Cancelled", "status_color":"#E8D7F8", "inner_color":"#D12E15", "doctype":"Doc_Status", "initial_docstatus":2},
        {"name":"Submitted", "status_color":"#e6e4fb", "inner_color":"#4112C7", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Discarded", "status_color":"#e6e4fb", "inner_color":"#D12E15", "doctype":"Doc_Status", "initial_docstatus":1},

        {"name":"Overdue", "status_color":"#fde8bd", "inner_color":"#d79005", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Overdue | Partially Receipted", "status_color":"#fde8bd", "inner_color":"#d79005", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Overdue | Partially Paid", "status_color":"#fde8bd", "inner_color":"#d79005", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Overdue | Outstanding", "status_color":"#fde8bd", "inner_color":"#d79005", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Overdue | Outstanding | Pending GRN", "status_color":"#fde8bd", "inner_color":"#d79005", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Overdue | Partially Returned", "status_color":"#fde8bd", "inner_color":"#d79005", "doctype":"Doc_Status", "initial_docstatus":1},
        
        {"name":"Pending Approval", "status_color":"#ffcc66", "inner_color":"#D06E0B", "doctype":"Doc_Status", "initial_docstatus": 0},
        {"name":"Approved", "status_color":"#D5B8E6", "inner_color":"#5208A6", "doctype":"Doc_Status", "initial_docstatus": 0},
        {"name":"Rejected", "status_color":"#ffe7e0", "inner_color":"#EB051C", "doctype":"Doc_Status", "initial_docstatus":3},
        {"name":"Separated", "status_color":"#ffe7e0", "inner_color":"#EB051C", "doctype":"Doc_Status", "initial_docstatus":3},
        {"name":"Unpaid", "status_color":"#f8e1d8", "inner_color":"#DE5826", "doctype":"Doc_Status", "initial_docstatus":1},
        
        {"name":"Pending Delivery", "status_color":"#f8e1d8", "inner_color":"#DE5826", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Pending Invoice", "status_color":"#f8e1d8", "inner_color":"#DE5826", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Delivered", "status_color":"#D5B8E6", "inner_color":"#5208A6", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Sales Order Issued", "status_color":"#D5B8E6", "inner_color":"#5208A6", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Proforma Invoice Issued", "status_color":"#D5B8E6", "inner_color":"#5208A6", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Tax Invoice Issued", "status_color":"#dbe6fb", "inner_color":"#0240A3", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Pending Allocation", "status_color":"#f8e1d8", "inner_color":"#DE5826", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Allocated", "status_color":"#dbe6fb", "inner_color":"#0240A3", "doctype":"Doc_Status", "initial_docstatus":1},



        # invoicing statuses
        {"name":"Unreceipted", "status_color":"#f8e1d8", "inner_color":"#DE5826",  "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Receipted", "status_color":"#dbe6fb", "inner_color":"#0240A3", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Partially Returned | Partially Receipted", "status_color":"#dcfcd4", "inner_color":"#53C213", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Partially Returned | Unreceipted", "status_color":"#dcfcd4", "inner_color":"#53C213", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Partially Receipted", "status_color":"#dcfcd4", "inner_color":"#53C213", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Overdue | Partially Receipted", "status_color":"#E8D7F8", "inner_color":"#53C213", "doctype":"Doc_Status", "initial_docstatus":1},
        
        
        {"name":"Outstanding", "status_color":"#E8D7F8", "inner_color":"#610E8C", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Outstanding | Partially Returned", "status_color":"#E8D7F8", "inner_color":"#610E8C", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Returned", "status_color":"#E8EDC7", "inner_color":"#4E990C", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Partially Returned", "status_color":"#f9ddc3", "inner_color":"#c37509", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Partially Paid | Partially Returned", "status_color":"#dccfe6", "inner_color":"#3a0b78", "doctype":"Doc_Status", "initial_docstatus":1},


        {"name":"Outstanding | Pending GRN", "status_color":"#E8D7F8", "inner_color":"#610E8C", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Outstanding | Partially Returned | Pending GRN", "status_color":"#E8D7F8", "inner_color":"#610E8C", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Pending GRN", "status_color":"#E8D7F8", "inner_color":"#610E8C", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Overdue | Partially Paid | Partially Returned", "status_color":"#f0dded", "inner_color":"#780b67", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Overdue | Partially Returned | Pending GRN", "status_color":"#f0dfe3", "inner_color":"#a80732", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Overdue | Pending GRN", "status_color":"#f0dfe3", "inner_color":"#a80732", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Overdue | Partially Paid | Pending GRN", "status_color":"#f0dfe3", "inner_color":"#a80732", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Overdue | Partially Paid | Partially Returned | Pending GRN", "status_color":"#f0dfe3", "inner_color":"#a80732", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Partially Paid | Partially Returned | Pending GRN", "status_color":"#f0dfe3", "inner_color":"#a80732", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Partially Paid | Pending GRN", "status_color":"#dcfcd4", "inner_color":"#53C213", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Paid | Partially Returned", "status_color":"#d3edeb", "inner_color":"#06968b", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Paid | Partially Returned | Pending GRN", "status_color":"#d3edeb", "inner_color":"#06968b", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Paid | Pending GRN", "status_color":"#E8D7F8", "inner_color":"#610E8C", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Partially Paid", "status_color":"#eee6f2", "inner_color":"#610873", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Paid", "status_color":"#dbe6fb", "inner_color":"#0240A3", "doctype":"Doc_Status", "initial_docstatus":1},
        
        # GRN X
        {"name":"Fully Accepted", "status_color":"#e9ebf7", "inner_color":"#2e2d5c", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Partially Accepted", "status_color":"#ede4df", "inner_color":"#703a11", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Returned To Supplier", "status_color":"#ebe1e7", "inner_color":"#7d0a4f", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Return Outward", "status_color":"#fcf1e3", "inner_color":"#cc780c", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Return Inward", "status_color":"#efe9f2", "inner_color":"#630ccc", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Adjustment In", "status_color":"#ebdae4", "inner_color":"#99095e", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Adjustment Out", "status_color":"#f2f1e1", "inner_color":"#756e00", "doctype":"Doc_Status", "initial_docstatus":1},


        {"name":"Fetched", "status_color":"#f2d7f4", "inner_color":"#810891", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Completed", "status_color":"#efdcf5", "inner_color":"#761994", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Pending", "status_color":"#d9f9ff", "inner_color":"#095157", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Unsettled", "status_color":"#d9f9ff", "inner_color":"#095157", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Accepted", "status_color":"#dcfce7", "inner_color":"#09752c", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Ordered", "status_color":"#dcfce7", "inner_color":"#09752c", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Debited", "status_color":"#C2C8ED", "inner_color":"#0334A6", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Credited", "status_color":"#F0E1C9", "inner_color":"#A66703", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Purchased", "status_color":"#DEFCEA", "inner_color":"#06515E", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Sold", "status_color":"#E1D5F2", "inner_color":"#290896", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Depleted", "status_color":"#E8F0D5", "inner_color":"#628709", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Depleting", "status_color":"#f7efdc", "inner_color":"#ed5912", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Unclosed", "status_color":"#f0dec7", "inner_color":"#9c6217", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Closed", "status_color":"#e0d8ed", "inner_color":"#5115ab", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Awaiting Final Approval", "status_color":"#e0d8ed", "inner_color":"#5115ab", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Transferred", "status_color":"#e0d8ed", "inner_color":"#5115ab", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Transfer In",  "status_color":"#dbe6fb", "inner_color":"#0240A3", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Disposed", "status_color":"#f8e1d8", "inner_color":"#ed5912", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Escalated To Disciplinary", "status_color":"#f8e1d8", "inner_color":"#ed5912", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Importation Successful", "status_color":"#C7D6ED", "inner_color":"#0E558F", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Resolved", "status_color":"#C7D6ED", "inner_color":"#0E558F", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Partially Imported", "status_color":"#EEDFF2", "inner_color":"#440447", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Pending Importation", "status_color":"#e7e1ed", "inner_color":"#7950c7", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Importation Failed", "status_color":"#F5E2D3", "inner_color":"#693206", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Open", "status_color":"#f8e1d8", "inner_color":"#DE5826",  "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Work in Progress", "status_color":"#f8e1d8", "inner_inner":"#DE5826", "doctype": "Doc_status", "initial_docstatus":0},
        {"name":"Pending Conversion", "status_color":"#f8e1d8", "inner_inner":"#DE5826", "doctype": "Doc_status", "initial_docstatus":0},
        {"name":"Lead Generated", "status_color":"#5208A6", "inner_inner":"#DE5826", "doctype": "Doc_status", "initial_docstatus":1},
        {"name":"Converted To Customer", "status_color":"#5208A6", "inner_inner":"#DE5826", "doctype": "Doc_status", "initial_docstatus":1},

        {"name":"Reopened", "status_color":"#A0F2EA", "inner_color":"#DE5826",  "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Expired", "status_color":"#f8e1d8", "inner_color":"#DE5826",  "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Used", "status_color":"#A0F2EA", "inner_color":"#08A696", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"In Progress", "status_color":"#A0F2EA", "inner_color":"#08A696", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"On Leave",  "status_color":"#E8D7F8", "inner_color":"#0240A3", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Resigned",  "status_color":"#D5B8E6", "inner_color":"#5208A6", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Left",  "status_color":"#D5B8E6", "inner_color":"#5208A6", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Ticket Escalated",  "status_color":"#D5B8E6", "inner_color":"#5208A6", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Ticket Re-Opened",  "status_color":"#D5B8E6", "inner_color":"#5208A6", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Awaiting Commencement",  "status_color":"#D5B8E6", "inner_color":"#5208A6", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Active Contract",  "status_color":"#D5B8E6", "inner_color":"#5208A6", "doctype":"Doc_Status", "initial_docstatus":1},        
        
        {"name":"Redundant",  "status_color":"#D5B8E6", "inner_color":"#5208A6", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Suspended",  "status_color":"#D5B8E6", "inner_color":"#5208A6", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Terminated",  "status_color":"#e6b7cb", "inner_color":"#a61f08", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Unretired",  "status_color":"#D5B8E6", "inner_color":"#5208A6", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Partially Retired",  "status_color":"#dcfcd4", "inner_color":"#53C213", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Retired",  "status_color":"#dbe6fb", "inner_color":"#0240A3", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Pending Submission",  "status_color":"#D6EDff", "inner_color":"#05276B", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Submission Successful",  "status_color":"#E1D5F2", "inner_color":"#290896", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Submission Failed",  "status_color":"#f7efdc", "inner_color":"#ed5912", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Pending Review",  "status_color":"#D6EDff", "inner_color":"#05276B", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Review",  "status_color":"#D6EDff", "inner_color":"#05276B", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Resignation Accepted",  "status_color":"#D6EDff", "inner_color":"#05276B", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"RFQ Raised",  "status_color":"#D6EDff", "inner_color":"#05276B", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Raised RFQ", "status_color":"#A0F2EA", "inner_color":"#08A696", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Raised RFP", "status_color":"#A0F2EA", "inner_color":"#08A696", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"PO Submitted", "status_color":"#A0F2EA", "inner_color":"#08A696", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Pending Importation", "status_color":"#D5B8E6", "inner_color":"#5208A6", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Importing", "status_color":"#efe9f2", "inner_color":"#8f50c7", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Reconciled Reduction", "status_color":"#D5B8E6", "inner_color":"#5208A6", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Project Review Scheduled", "status_color":"#fef08a", "inner_color":"#eab308", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Prospect", "status_color":"#5eead4", "inner_color":"#0f766e", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Qualification", "status_color":"#f0abfc", "inner_color":"#a21caf", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Needs Analysis", "status_color":"#a5b4fc", "inner_color":"#4338ca", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Proposal", "status_color":"#fca5a5", "inner_color":"#ea580c", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Negotiation", "status_color":"#D5B8E6", "inner_color":"#5208A6", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Conducted", "status_color":"#D5B8E6", "inner_color":"#5208A6", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Closing", "status_color":"#60a5fa", "inner_color":"#1e40af", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Won", "status_color":"#4ade80", "inner_color":"#14532d", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Lost", "status_color":"#f43f5e", "inner_color":"#4c0519", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Follow Up", "status_color":"#e879f9", "inner_color":"#701a75", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Renewal", "status_color":"#818cf8", "inner_color":"#1e1b4b", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Renewed", "status_color":"#818cf8", "inner_color":"#1e1b4b", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Inactive", "status_color":"#ef4444", "inner_color":"#450a0a", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Purchase Order Raised", "status_color":"#ef4444", "inner_color":"#450a0a", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Converted", "status_color":"#2e1065", "inner_color":"#e0e7ff", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Responded", "status_color":"#2e1065", "inner_color":"#4c1d95", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Finalize In Case Outcome | Resolved", "status_color":"#2e1065", "inner_color":"#4c1d95", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Unprocessed", "status_color":"#f8e1d8", "inner_color":"#DE5826", "doctype":"Doc_Status", "initial_docstatus":0},
        {"name":"Short Listed", "status_color":"#f8e1d8", "inner_color":"#DE5826", "doctype":"Doc_Status", "initial_docstatus":1},

        {"name":"Processed", "status_color":"#c0f2da", "inner_color":"#22b957", "doctype":"Doc_Status", "initial_docstatus":1},

        {"name":"Repackaged", "status_color":"#c0f2da", "inner_color":"#22b957", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Packaged", "status_color":"#c0f2da", "inner_color":"#22b957", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Applied", "status_color":"#7878FF", "inner_color":"#002387", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Accepted | Pending Confirmation", "status_color":"#dff282", "inner_color":"#98a300", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Confirmed", "status_color":"#00a33f", "inner_color":"#82f28f", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Active Asset", "status_color":"#a0f58f", "inner_color":"#00803e", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Pending Witness", "status_color":"#a0f58f", "inner_color":"#00803e", "doctype":"Doc_Status", "initial_docstatus":2},
        {"name":"Witnessed", "status_color":"#a0f58f", "inner_color":"#00803e", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Scheduled", "status_color":"#a0f58f", "inner_color":"#00803e", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Pending Short List Approval", "status_color":"#e1f58f", "inner_color":"#7c8000", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Cleared", "status_color":"#8fe2f5", "inner_color":"#007780", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"Over Retired", "status_color":"#f0dfe3", "inner_color":"#a80732", "doctype":"Doc_Status", "initial_docstatus":1},
        {"name":"ShortListed", "status_color":"#adf3b9", "inner_color":"#0f5400", "doctype":"Doc_Status", "initial_docstatus":1},
    ]
}