industry = {
    "model":"Industry",
    "data":[
        {"Name": "Accounting, Bookkeeping And Auditing Activities"},
        {"Name": "Act Of Collection Agencies,Credit Bureaus"},
        {"Name": "Act Of Households As Employers Of Dome Personnel"},
        {"Name": "Activities Of Amusement Parks And Theme Parks"},
        {"Name": "Activities Of Buss And Employers Membership Org"},
        {"Name": "Activities Of Call Centres"},
        {"Name": "Activities Of Employment Placement Agencies"},
        {"Name": "Activities Of Extraterritorial Org And Bodies"},
        {"Name": "Activities Of Head Offices"},
        {"Name": "Activities Of Holding Companies"},
        {"Name": "Activities Of Insurance Agents And Brokers"},
        {"Name": "Activities Of Other Membership Org"},
        {"Name": "Activities Of Political Organizations"},
        {"Name": "Activities Of Professional Membership Org"},
        {"Name": "Activities Of Religious Organizations"},
        {"Name": "Activities Of Sports Clubs"},
        {"Name": "Activities Of Trade Unions"},
        {"Name": "Administration Of Financial Markets"},
        {"Name": "Advertising"},
        {"Name": "Agriculture"},
        {"Name": "Airlines"},
        {"Name": "Arch,Engineering Act,Related Tech Consultancy"},
        {"Name": "Arts & Crafts"},
        {"Name": "Banking"},
        {"Name": "Beverage Serving Activities"},
        {"Name": "Book Publishing"},
        {"Name": "Bot And Zool Gardens,Nature Reserves Act"},
        {"Name": "Boutique"},
        {"Name": "Brewing (Beer)"},
        {"Name": "Broadcasting"},
        {"Name": "Building Completion And Finishing"},
        {"Name": "Building Of Pleasure And Sporting Boats"},
        {"Name": "Building Of Ships And Floating Structures"},
        {"Name": "Bureau De-Change"},
        {"Name": "Cabinet Office"},
        {"Name": "Camping Grounds,Recreationa Vehicle,Trailerparks"},
        {"Name": "Cargo Handling"},
        {"Name": "Carpentry & Joinery"},
        {"Name": "Casting Of Iron And Steel"},
        {"Name": "Casting Of Non-Ferrous Metals"},
        {"Name": "Central Banking"},
        {"Name": "Chemical Suppliers"},
        {"Name": "Civic Authorities"},
        {"Name": "Clearing & Forwarding"},
        {"Name": "Collection Of Hazardous Waste"},
        {"Name": "Collection Of Non-Hazardous Waste"},
        {"Name": "Combined Facilities Support Activities"},
        {"Name": "Combined Office Administrative Service Act"},
        {"Name": "Community Services (Ngos, Clubs)"},
        {"Name": "Comp Consultancy,Comp Facilities Management Act"},
        {"Name": "Compulsory Social Security Activities"},
        {"Name": "Computer Programming Activities"},
        {"Name": "Computer Services"},
        {"Name": "Construction"},
        {"Name": "Construction Of Buildings"},
        {"Name": "Construction Of Other Civil Engineering Projects"},
        {"Name": "Construction Of Roads And Railways"},
        {"Name": "Construction Of Utility Projects"},
        {"Name": "Consultants"},
        {"Name": "Courier Activities"},
        {"Name": "Creative, Arts And Entertainment Act"},
        {"Name": "Cultural Education"},
        {"Name": "Cutting, Shaping And Finishing Of Stone"},
        {"Name": "Data Processing, Hosting And Related Act"},
        {"Name": "Defence Activities"},
        {"Name": "Demolition"},
        {"Name": "Development Work"},
        {"Name": "Distilling, Rectifying And Blending Of Spirits"},
        {"Name": "Distribution Of Gaseous Fuels Through Mains"},
        {"Name": "Education"},
        {"Name": "Educational Materials"},
        {"Name": "Educational Support Activities"},
        {"Name": "Electric Power Generation,Transmission,Distb"},
        {"Name": "Electrical"},
        {"Name": "Electrical Installation"},
        {"Name": "Electricity"},
        {"Name": "Electronics"},
        {"Name": "Employer Of Domestic Worker"},
        {"Name": "Event Catering"},
        {"Name": "Extraction Of Peat"},
        {"Name": "Extraction Of Salt"},
        {"Name": "Farming"},
        {"Name": "Finance"},
        {"Name": "Financial Leasing"},
        {"Name": "Finishing Of Textiles"},
        {"Name": "Fishing"},
        {"Name": "Foreign Affairs"},
        {"Name": "Forestery"},
        {"Name": "Forgg,Pressg,Stamping,Rollg,Powder Metal-Metal"},
        {"Name": "Freight Air Transport"},
        {"Name": "Freight Rail Transport"},
        {"Name": "Freight Transport By Road"},
        {"Name": "Freshwater Aquaculture"},
        {"Name": "Freshwater Fishing"},
        {"Name": "Fund Management Activities"},
        {"Name": "Funeral And Related Activities"},
        {"Name": "Gambling And Betting Activities"},
        {"Name": "Gathering Of Non-Wood Forest Products"},
        {"Name": "General Cleaning Of Buildings"},
        {"Name": "General Public Administration Activities"},
        {"Name": "General Secondary Education"},
        {"Name": "Goverment"},
        {"Name": "Growg Of Cereals(Except Rice),Legum Crops&Oil Seed"},
        {"Name": "Growing Of Beverage Crops"},
        {"Name": "Growing Of Citrus Fruits"},
        {"Name": "Growing Of Fibre Crops"},
        {"Name": "Growing Of Grapes"},
        {"Name": "Growing Of Oleaginous Fruits"},
        {"Name": "Growing Of Other Non-Perennial Crops"},
        {"Name": "Growing Of Other Perennial Crops"},
        {"Name": "Growing Of Other Tree And Bush Fruits And Nuts"},
        {"Name": "Growing Of Pome Fruits And Stone Fruits"},
        {"Name": "Growing Of Rice"},
        {"Name": "Growing Of Spices, Aromatic, Drug And Pharma Crops"},
        {"Name": "Growing Of Sugar Cane"},
        {"Name": "Growing Of Tobacco"},
        {"Name": "Growing Of Tropical And Subtropical Fruits"},
        {"Name": "Growing Of Vegetables And Melons, Roots And Tubers"},
        {"Name": "Hairdressing And Other Beauty Treatment"},
        {"Name": "Health Services"},
        {"Name": "Higher Education"},
        {"Name": "Hospital Activities"},
        {"Name": "Hotels"},
        {"Name": "Hunting, Trapping And Related Service Activities"},
        {"Name": "Information Technology"},
        {"Name": "Inland Freight Water Transport"},
        {"Name": "Inland Passenger Water Transport"},
        {"Name": "Installation Of Industrial Machinery,Equipment"},
        {"Name": "Insurance"},
        {"Name": "Investigation Activities"},
        {"Name": "Judicial Services"},
        {"Name": "Landscape Care And Maintenance Service Act"},
        {"Name": "Leasing Of Intellect Property,Similar Products"},
        {"Name": "Legal Activities"},
        {"Name": "Legal Services"},
        {"Name": "Library And Archives Activities"},
        {"Name": "Life Insurance"},
        {"Name": "Logging"},
        {"Name": "Maintenance And Repair Of Motor Vehicles"},
        {"Name": "Management Consultancy Activities"},
        {"Name": "Manuf Machinery-Mining,Quarrying,Construction"},
        {"Name": "Manuf Of Medical,Dental Instrument,Supplies"},
        {"Name": "Manuf Of Metal-Forming Machinery,Machine Tools"},
        {"Name": "Manuf Of Other Fabricated Metal Products N.E.C."},
        {"Name": "Manuf Of Pharma,Medicinachemical,Botanical Prod"},
        {"Name": "Manuf Of Tanks,Reservoirs,Containers Of Metal"},
        {"Name": "Manuf&Containers Of Corrugated Paper&Paperboard"},
        {"Name": "Manuf&Produ-Soft Drinks,Mineral&Bottled Waters"},
        {"Name": "Manuf,Retreading Of Rubber Tyres And Tubes"},
        {"Name": "Manuf,Varnishes, Oatings,Printing Ink,Mastics"},
        {"Name": "Manuf-Basic Precious,Other Non-Ferrous Metals"},
        {"Name": "Manuf-Bearings, Gears, Gearing,Driving Elements"},
        {"Name": "Manuf-Cocoa, Chocolate And Sugar Confectionery"},
        {"Name": "Manuf-Elec Motors,Gen,Transf,Dist,Control Appara"},
        {"Name": "Manuf-Irradiation,Electromedical,Therapeutic Eqp"},
        {"Name": "Manuf-Luggage,Handbags,The Like,Saddlery&Harness"},
        {"Name": "Manuf-Macaroni,Noodles,Couscous&Farinaceous Prod"},
        {"Name": "Manuf-Machinery-Textile,Apparel,Leather Produ"},
        {"Name": "Manuf-Made-Up Textile Articles,Except Apparel"},
        {"Name": "Manuf-Measuring,Test,Navigate,Control Equipment"},
        {"Name": "Manuf-Of Engines,Turbines,Vehicle,Cycle Engines"},
        {"Name": "Manuf-Optical Instruments And Photographic Eqp"},
        {"Name": "Manuf-Other Articles Of Paper&Paperboard"},
        {"Name": "Manuf-Other Electronic Wires And Cables"},
        {"Name": "Manuf-Other Prod-Wood,Articles,Straw&Plaiting Mat"},
        {"Name": "Manuf-Ovens, Furnaces And Furnace Burners"},
        {"Name": "Manuf-Pesticides And Other Agrochemical Prod"},
        {"Name": "Manuf-Plastics&Synthetic Rubber In Primary Forms"},
        {"Name": "Manuf-Pumps, Compressors, Taps And Valves"},
        {"Name": "Manuf-Soap,Cleaning,Polishing Prep,Perfumes"},
        {"Name": "Manuf-Steam Generators,Except Central Boilers"},
        {"Name": "Manufa-Machinery-Food,Beverage,Tobacco Proces"},
        {"Name": "Manufa-Other Non-Metallic Mineral Prod N.E.C."},
        {"Name": "Manufacture Of Agricultural,Forestry Machinery"},
        {"Name": "Manufacture Of Air,Spacecraft,Related Machinery"},
        {"Name": "Manufacture Of Articles Of Fur"},
        {"Name": "Manufacture Of Bakery Products"},
        {"Name": "Manufacture Of Basic Chemicals"},
        {"Name": "Manufacture Of Basic Iron And Steel"},
        {"Name": "Manufacture Of Batteries And Accumulators"},
        {"Name": "Manufacture Of Bicycles And Invalid Carriages"},
        {"Name": "Manufacture Of Bodies (Coachwork)-Motor Vehicles"},
        {"Name": "Manufacture Of Builders Carpentry And Joinery"},
        {"Name": "Manufacture Of Carpets And Rugs"},
        {"Name": "Manufacture Of Cement, Lime And Plaster"},
        {"Name": "Manufacture Of Clay Building Materials"},
        {"Name": "Manufacture Of Coke Oven Products"},
        {"Name": "Manufacture Of Communication Equipment"},
        {"Name": "Manufacture Of Computers&Peripheral Equipment"},
        {"Name": "Manufacture Of Consumer Electronics"},
        {"Name": "Manufacture Of Cordage, Rope, Twine And Netting"},
        {"Name": "Manufacture Of Dairy Products"},
        {"Name": "Manufacture Of Domestic Appliances"},
        {"Name": "Manufacture Of Electric Lighting Equipment"},
        {"Name": "Manufacture Of Electronic Components And Boards"},
        {"Name": "Manufacture Of Fertilizers And Nitrogen Compounds"},
        {"Name": "Manufacture Of Fibre Optic Cables"},
        {"Name": "Manufacture Of Fluid Power Equipment"},
        {"Name": "Manufacture Of Footwear"},
        {"Name": "Manufacture Of Furniture"},
        {"Name": "Manufacture Of Games And Toys"},
        {"Name": "Manufacture Of Glass And Glass Products"},
        {"Name": "Manufacture Of Grain Mill Products"},
        {"Name": "Manufacture Of Jewellery And Related Articles"},
        {"Name": "Manufacture Of Knitted And Crocheted Apparel"},
        {"Name": "Manufacture Of Knitted And Crocheted Fabrics"},
        {"Name": "Manufacture Of Lifting And Handling Equipment"},
        {"Name": "Manufacture Of Machinery For Metallurgy"},
        {"Name": "Manufacture Of Magnetic And Optical Media"},
        {"Name": "Manufacture Of Malt Liquors And Malt"},
        {"Name": "Manufacture Of Man-Made Fibres"},
        {"Name": "Manufacture Of Military Fighting Vehicles"},
        {"Name": "Manufacture Of Motor Vehicles"},
        {"Name": "Manufacture Of Motorcycles"},
        {"Name": "Manufacture Of Musical Instruments"},
        {"Name": "Manufacture Of Office Machinery And Equipment"},
        {"Name": "Manufacture Of Other Chemical Products N.E.C."},
        {"Name": "Manufacture Of Other Electrical Equipment"},
        {"Name": "Manufacture Of Other Food Products N.E.C."},
        {"Name": "Manufacture Of Other General-Purpose Machinery"},
        {"Name": "Manufacture Of Other Porcelain And Ceramic Prod"},
        {"Name": "Manufacture Of Other Rubber Products"},
        {"Name": "Manufacture Of Other Special-Purpose Machinery"},
        {"Name": "Manufacture Of Other Textiles N.E.C."},
        {"Name": "Manufacture Of Other Transport Equipment N.E.C."},
        {"Name": "Manufacture Of Plastics Products"},
        {"Name": "Manufacture Of Power-Driven Hand Tools"},
        {"Name": "Manufacture Of Prepared Animal Feeds"},
        {"Name": "Manufacture Of Prepared Meals And Dishes"},
        {"Name": "Manufacture Of Pulp, Paper And Paperboard"},
        {"Name": "Manufacture Of Railway Locomotives,Rolling Stock"},
        {"Name": "Manufacture Of Refined Petroleum Products"},
        {"Name": "Manufacture Of Refractory Products"},
        {"Name": "Manufacture Of Sports Goods"},
        {"Name": "Manufacture Of Starches And Starch Products"},
        {"Name": "Manufacture Of Structural Metal Products"},
        {"Name": "Manufacture Of Sugar"},
        {"Name": "Manufacture Of Tobacco Products"},
        {"Name": "Manufacture Of Vegetable And Animal Oils And Fats"},
        {"Name": "Manufacture Of Veneer Sheets & Wood-Based Panels"},
        {"Name": "Manufacture Of Watches And Clocks"},
        {"Name": "Manufacture Of Weapons And Ammunition"},
        {"Name": "Manufacture Of Wearing Apparel,Except Fur Apparel"},
        {"Name": "Manufacture Of Wines"},
        {"Name": "Manufacture Of Wiring Devices"},
        {"Name": "Manufacture Of Wooden Containers"},
        {"Name": "Manufacture,Articles Of Concrete,Cement,Plaster"},
        {"Name": "Manufacture-Imitation Jewellery,Related Articles"},
        {"Name": "Manufactureaccessories For Motor Vehicles"},
        {"Name": "Manufacturing"},
        {"Name": "Manufof Cutlery,Hand Tools,General Hardware"},
        {"Name": "Marine Aquaculture"},
        {"Name": "Marine Fishing"},
        {"Name": "Market Research And Public Opinion Polling"},
        {"Name": "Materials Recovery"},
        {"Name": "Medical And Dental Practice Activities"},
        {"Name": "Mining & Quarrying"},
        {"Name": "Mining Of Chemical And Fertilizer Minerals"},
        {"Name": "Mining Of Hard Coal"},
        {"Name": "Mining Of Iron Ores"},
        {"Name": "Mining Of Lignite"},
        {"Name": "Mining Of Other Non-Ferrous Metal Ores"},
        {"Name": "Mining Of Uranium And Thorium Ores"},
        {"Name": "Ministry Of Agriculture Food & Fisheries"},
        {"Name": "Ministry Of Commerce"},
        {"Name": "Ministry Of Community Development"},
        {"Name": "Ministry Of Defence"},
        {"Name": "Ministry Of Education"},
        {"Name": "Ministry Of Energy"},
        {"Name": "Ministry Of Enviroment"},
        {"Name": "Ministry Of Finance & Economic Development"},
        {"Name": "Ministry Of Foreign Affairs"},
        {"Name": "Ministry Of Health"},
        {"Name": "Ministry Of Home Affairs"},
        {"Name": "Ministry Of Information & Broadcasting"},
        {"Name": "Ministry Of Labour & Social Security"},
        {"Name": "Ministry Of Lands"},
        {"Name": "Ministry Of Legal Affairs"},
        {"Name": "Ministry Of Local Government & Housing"},
        {"Name": "Ministry Of Mines & Minerals Development"},
        {"Name": "Ministry Of Science & Technology"},
        {"Name": "Ministry Of Tourism"},
        {"Name": "Ministry Of Transport & Communication"},
        {"Name": "Ministry Of Works & Supply"},
        {"Name": "Mixed Farming"},
        {"Name": "Motion Pictur,Video,Television Programme Prod Act"},
        {"Name": "Motion Picture Projection Activities"},
        {"Name": "Motion Picture, Video And T.V Programme Dist Act"},
        {"Name": "Motion Picture, Video And T.Vpgr Post-Prod Act"},
        {"Name": "Motor Industry"},
        {"Name": "Museums Act And Operation Of Hist Sites,Build"},
        {"Name": "News Agency Activities"},
        {"Name": "Ngos"},
        {"Name": "Non-Life Insurance"},
        {"Name": "Non-Specialized Wholesale Trade"},
        {"Name": "Office Of Minister Without Portifolio"},
        {"Name": "Office Of The Vice President"},
        {"Name": "Operation Of Sports Facilities"},
        {"Name": "Organization Of Conventions And Trade Shows"},
        {"Name": "Other Accommodation"},
        {"Name": "Other Act Auxiliary To Ins,Pension Funding"},
        {"Name": "Other Activities Auxiliary To Fin Service Act"},
        {"Name": "Other Amusement And Recreation Activities N.E.C."},
        {"Name": "Other Building And Ind Cleaning Activities"},
        {"Name": "Other Business Support Service Activities N.E.C"},
        {"Name": "Other Construction Installation"},
        {"Name": "Other Credit Granting"},
        {"Name": "Other Education N.E.C."},
        {"Name": "Other Fins Service Act,Exp Ins,Pension Fundingact"},
        {"Name": "Other Food Service Activities"},
        {"Name": "Other Human Health Activities"},
        {"Name": "Other Human Resources Provision"},
        {"Name": "Other Information Service Activities N.E.C."},
        {"Name": "Other Information Technology,Comp Service Act"},
        {"Name": "Other Manufacturing N.E.C."},
        {"Name": "Other Mining And Quarrying N.E.C."},
        {"Name": "Other Monetary Intermediation"},
        {"Name": "Other Passenger Land Transport"},
        {"Name": "Other Personal Service Activities N.E.C."},
        {"Name": "Other Professional,Scientific And Tech Act N.E.C"},
        {"Name": "Other Publishing Activities"},
        {"Name": "Other Reservation Service And Related Activities"},
        {"Name": "Other Residential Care Activities"},
        {"Name": "Other Retail Sale In Non-Specialized Stores"},
        {"Name": "Other Retail Sale Not In Stores,Stalls,Markets"},
        {"Name": "Other Retail Sale Of New Goods In Spl Str"},
        {"Name": "Other Social Work Activities Without Acc"},
        {"Name": "Other Specialized Construction Activities"},
        {"Name": "Other Sports Activities"},
        {"Name": "Other Telecommunications Activities"},
        {"Name": "Other Transportation Support Activities"},
        {"Name": "Packaging Activities"},
        {"Name": "Passenger Air Transport"},
        {"Name": "Passenger Rail Transport, Interurban"},
        {"Name": "Pension Funding"},
        {"Name": "Photocopying,Doc Prep,Other Spl Office Supp Act"},
        {"Name": "Photographic Activities"},
        {"Name": "Plant Propagation"},
        {"Name": "Plumbing, Heat And Air-Conditioning Installation"},
        {"Name": "Post-Harvest Crop Activities"},
        {"Name": "Postal Activities"},
        {"Name": "Pre-Primary And Primary Education"},
        {"Name": "Preparation And Spinning Of Textile Fibres"},
        {"Name": "Presidential Office"},
        {"Name": "Print Media"},
        {"Name": "Printing"},
        {"Name": "Private Security Activities"},
        {"Name": "Processg&Preserving-Fish,Crustaceans&Molluscs"},
        {"Name": "Processing And Preserving Of Fruit And Vegetables"},
        {"Name": "Processing And Preserving Of Meat"},
        {"Name": "Public Order And Safety Activities"},
        {"Name": "Publishing Of Directories And Mailing Lists"},
        {"Name": "Publishing Of Newspapers, Journals,Periodicals"},
        {"Name": "Quarrying Of Stone, Sand And Clay"},
        {"Name": "Radio Broadcasting"},
        {"Name": "Railways"},
        {"Name": "Raising Of Camels And Camelids"},
        {"Name": "Raising Of Cattle And Buffaloes"},
        {"Name": "Raising Of Horses And Other Equines"},
        {"Name": "Raising Of Other Animals"},
        {"Name": "Raising Of Poultry"},
        {"Name": "Raising Of Sheep And Goats"},
        {"Name": "Raising Of Swine/Pigs"},
        {"Name": "Real Estate"},
        {"Name": "Real Estate Act On A Fee Or Contract Basis"},
        {"Name": "Real Estate Act With Own Or Leased Property"},
        {"Name": "Reg-Contribution To More Effi Operation Of Buss"},
        {"Name": "Reg-Prov Health Care,Edu,Cult Serv,Soc Serv"},
        {"Name": "Reinsurance"},
        {"Name": "Religious"},
        {"Name": "Remediation Activities,Waste Management Services"},
        {"Name": "Renting And Leasing Of Motor Vehicles"},
        {"Name": "Renting And Leasing Of Recreational,Sports Goods"},
        {"Name": "Renting Of Video Tapes And Disks"},
        {"Name": "Renting,Leasing Of Other Mach, Eqp,Tangibl Goods"},
        {"Name": "Renting,Leasing-Other Personal,Household Goods"},
        {"Name": "Repair Of Communication Equipment"},
        {"Name": "Repair Of Computers And Peripheral Eqp"},
        {"Name": "Repair Of Consumer Electronics"},
        {"Name": "Repair Of Electrical Equipment"},
        {"Name": "Repair Of Electronic And Optical Equipment"},
        {"Name": "Repair Of Fabricated Metal Products"},
        {"Name": "Repair Of Footwear And Leather Goods"},
        {"Name": "Repair Of Furniture And Home Furnishings"},
        {"Name": "Repair Of Household Appliances,Home,Garden Eqp"},
        {"Name": "Repair Of Machinery"},
        {"Name": "Repair Of Other Equipment"},
        {"Name": "Repair Of Other Personal,Household Goods"},
        {"Name": "Repair Of Transport Equipment,Exp Motor Vehicles"},
        {"Name": "Reproduction Of Recorded Media"},
        {"Name": "Resd Care Act-Mental Ret,Mental Health,Sub Abuse"},
        {"Name": "Research,Exp Dev On Natural Sciences And Engg"},
        {"Name": "Research,Exp Dev On Social Sciences,Humanities"},
        {"Name": "Residential Care Act For The Elderly,Disabled"},
        {"Name": "Residential Nursing Care Facilities"},
        {"Name": "Restaurants"},
        {"Name": "Restaurants And Mobile Food Service Activities"},
        {"Name": "Retail Sale Of Audio,Video Eqp In Special Stores"},
        {"Name": "Retail Sale Of Automotive Fuel In Special Stores"},
        {"Name": "Retail Sale Of Beverages In Specialized Stores"},
        {"Name": "Retail Sale Of Food In Specialized Stores"},
        {"Name": "Retail Sale Of Games And Toys In Spl Stores"},
        {"Name": "Retail Sale Of Hware,Paints,Glass In Spl Stores"},
        {"Name": "Retail Sale Of Second-Hand Goods"},
        {"Name": "Retail Sale Of Sporting Equipment In Spl Stores"},
        {"Name": "Retail Sale Of Textiles In Specialized Stores"},
        {"Name": "Retail Sale Of Tobacco Prod In Special Stores"},
        {"Name": "Retail Sale Stores With Food,Beverages,Tobacco"},
        {"Name": "Retail Sale Via Mail Order Houses,Via Internet"},
        {"Name": "Retail Sale Via Stalls,Markets Of Other Goods"},
        {"Name": "Retail Sale-Computers,Software,Telecom Eqp"},
        {"Name": "Risk And Damage Evaluation"},
        {"Name": "Rtl Sale Of Books,Newspapers,Stati In Spl Stores"},
        {"Name": "Rtl Sale Of Music,Video Recordings In Spl Stores"},
        {"Name": "Rtl Sale Via Stalls,Food,Bevg,Tobacco Prod"},
        {"Name": "Rtl Sale Via Stalls,Markets Of Clothing,Fwear"},
        {"Name": "Rtlsale-Carpets,Rugs,Wall,Flrcovrngs In Spl Strs"},
        {"Name": "Rtlsale-Cloth,Footwear,Leather Articles Instores"},
        {"Name": "Rtlsale-Elechousehold Appl,Furn,Light Eqp Spl Str"},
        {"Name": "Rtlsalepharma,Medl Goods,Cosmetic,Articles In Str"},
        {"Name": "Sale Of Motor Vehicle Parts And Accessories"},
        {"Name": "Sale Of Motor Vehicles"},
        {"Name": "Sale, Maintenance,Repair Of Motorcycles&Parts"},
        {"Name": "Sanitation"},
        {"Name": "Satellite Telecommunications Activities"},
        {"Name": "Sawmilling And Planing Of Wood"},
        {"Name": "Sea And Coastal Freight Water Transport"},
        {"Name": "Sea And Coastal Passenger Water Transport"},
        {"Name": "Security And Commodity Contracts Brokerage"},
        {"Name": "Security Services"},
        {"Name": "Security Systems Service Activities"},
        {"Name": "Seed Processing For Propagation"},
        {"Name": "Self Employed"},
        {"Name": "Seminary"},
        {"Name": "Service Activities Incidental To Air Transp"},
        {"Name": "Service Activities Incidental To Land Transp"},
        {"Name": "Service Activities Incidental To Water Transp"},
        {"Name": "Service Activities Related To Printing"},
        {"Name": "Sewerage"},
        {"Name": "Short Term Accommodation Activities"},
        {"Name": "Silviculture And Other Forestry Activities"},
        {"Name": "Site Preparation"},
        {"Name": "Soc Work Act Without Acc-The Elderly,Disabled"},
        {"Name": "Software Publishing"},
        {"Name": "Sound Recording And Music Publishing Activities"},
        {"Name": "Specialized Design Activities"},
        {"Name": "Sports And Recreation Education"},
        {"Name": "Stationery"},
        {"Name": "Steam And Air Conditioning Supply"},
        {"Name": "Support Activities For Animal Production"},
        {"Name": "Support Activities For Crop Production"},
        {"Name": "Support Activities For Other Mining And Quarrying"},
        {"Name": "Mining and Quarrying"},
        {"Name": "Support Activities-Petroleum&Natural Gas Extrac"},
        {"Name": "Support Services To Forestry"},
        {"Name": "Surveying & Country Planning"},
        {"Name": "Tailoring & Designing"},
        {"Name": "Tanning&Dressing-Leather,Dressing&Dyeing Of Fur"},
        {"Name": "Technical And Vocational Secondary Education"},
        {"Name": "Technical Testing And Analysis"},
        {"Name": "Telecommunication"},
        {"Name": "Television Programming And Broadcasting Act"},
        {"Name": "Temporary Employment Agency Activities"},
        {"Name": "Tour Operator Activities"},
        {"Name": "Tourism"},
        {"Name": "Trading"},
        {"Name": "Transport (Bus)"},
        {"Name": "Transport Via Pipeline"},
        {"Name": "Travel Agency Activities"},
        {"Name": "Treatment And Coating Of Metals; Machining"},
        {"Name": "Treatment And Disposal Of Hazardous Waste"},
        {"Name": "Treatment And Disposal Of Non-Hazardous Waste"},
        {"Name": "Trusts, Funds And Similar Financial Entities"},
        {"Name": "Undiff Goods-Prod Act Of Pvt Households-Own Use"},
        {"Name": "Undiff Srv-Prod Act-Pvt Households For Own Use"},
        {"Name": "Urban And Suburban Passenger Land Transport"},
        {"Name": "Veterinary Activities"},
        {"Name": "Veterinary Services"},
        {"Name": "Warehousing And Storage"},
        {"Name": "Washing And (Dry-) Cleaning Of Textile,Fur Prod"},
        {"Name": "Water"},
        {"Name": "Water Collection, Treatment And Supply"},
        {"Name": "Weaving Of Textiles"},
        {"Name": "Web Portals"},
        {"Name": "Welding"},
        {"Name": "Wholesale Of Agri Machinery, Equipment"},
        {"Name": "Wholesale Of Agricultural Raw Mat&Live Animals"},
        {"Name": "Wholesale Of Electronic And Telecomm Eqp"},
        {"Name": "Wholesale Of Food, Beverages And Tobacco"},
        {"Name": "Wholesale Of Metals And Metal Ores"},
        {"Name": "Wholesale Of Other Household Goods"},
        {"Name": "Wholesale Of Other Machinery And Equipment"},
        {"Name": "Wholesale Of Solid,Liquid&Gas Fuels&Related Prod"},
        {"Name": "Wholesale Of Textiles, Clothing And Footwear"},
        {"Name": "Wholesale Of Waste,Scrap,Other Products N.E.C."},
        {"Name": "Wholesale On A Fee Or Contract Basis"},
        {"Name": "Wholesale&Peripheral Comp  Eqp & Software"},
        {"Name": "Wholesale-Construction,Hardware,Plumbg,Heatg Eqp"},
        {"Name": "Wholesaling"},
        {"Name": "Wired Telecommunications Activities"},
        {"Name": "Wireless Telecommunications Activities"},
        {"Name": "Pharmaceuticals and medical supplies"},
        {"Name": "Investment and Asset Management"},
        {"Name": "Road transport and haulage"},
        {"Name": "Copper mining"},
        {"Name": "Health and Social Work"},
        {"Name": "Energy and Water"},
        {"Name": "Government and Public Administration"},
        {"Name": "Accommodation and lodging"},
        {"Name": "Defense and security"},
        {"Name": "Supermarkets & grocery Stores"},
        {"Name": "Property development"},
        {"Name": "Vocational training"},
        {"Name": "Primary and secondary education"},
        {"Name": "Pharmaceuticals"},
        {"Name": "Higher Education and Universities"},
        {"Name": "Electricity generation, transmission, and distribution"},
        {"Name": "General construction"},
        {"Name": "Electrical and plumbing"},
        {"Name": "Hospitals and Clinics"},
        {"Name": "Investment Banking"},
        {"Name": "Renewable energy"},
        {"Name": "Water supply and sanitation"},
        {"Name": "Central government administration"},
        {"Name": "Local Government Administration"},
        {"Name": "Banking and lending"},
        {"Name": "Forestry and logging"},
        {"Name": "Livestock farming"},
        {"Name": "Fisheries and aquaculture"},
        {"Name": "Crop production"},
        {"Name": "Building materials and supplies"},
        {"Name": "Internet service providers"},
        {"Name": "Software and application development"},
        {"Name": "Air transport and aviation services"},
        {"Name": "Shipping and maritime services."},
        {"Name": "Convenience Stores and Gas Stations"},
        {"Name": "Wholesale distributors"},
        {"Name": "Real estate agents and brokers"},
        {"Name": "Property rental and management"},
        {"Name": "Accounting and auditing"},
        {"Name": "Cobalt mining"},
        {"Name": "Gold mining"},
        {"Name": "Chemicals and pharmaceuticals"},
        {"Name": "Textile and clothing manufacturing"},
        {"Name": "Food processing and beverage production"},
        {"Name": "Travel agencies and tour operators"},
        {"Name": "Food and beverage services"},
        {"Name": "Branding & Printing"},
        {"Name":"Information Technology (IT)"},
        {"Name":"Electrical construction industry"},
        {"Name":"Professional Services"},
        {"Name":"Food Industry"},
        {"Name":"Telecommunication Services"},
        {"Name":"Textile & Fabrics"},
        {"Name":"General Supplies"},
        {"Name":"State-owned Enterprise"},
        {"Name":"Social security"},
        {"Name":"Medical Services"},
        {"Name":"Data Centre Services"},
        {"Name":"Air Transport & Aviation Services"},
        {"Name":"Computer consultancy"},
        {"Name":"cleaning Services"},
        {"Name":"computer supply"},
        {"Name":"Textile & Clothing Manufacturing"},
        {"Name":"General supplies of non-specialized items"},
        {"Name":"NGO/ Developmental"},
        {"Name":"Central Government"},
        {"Name":"Insurance and Risk Management"},
        {"Name":"Social Services and Welfare"},
        {"Name":"Telecommunications Services"},
        {"Name":"Telecommunications"},
        {"Name":"Internet Service Provider"},
        {"Name":"Automotive Industry"},
        {"Name":"Consulting Services"},
        {"Name":"Religious and Spiritual Services"},
        {"Name":"Software & Application Development"},
        {"Name":"Travel Agencies and Tour Operations"},
        {"Name":"Creative Arts and Entertainment"},
        {"Name":"Professional Services"},
        {"Name":"Public Administration & Social Development"},
        {"Name":"Road Transport & Haulage"},
        {"Name":"Consultancy, Brokerages & Support Services"},
        {"Name":"Agriculture, Farming or Forestry"},
        {"Name":"Food and Beverages Services"},
        {"Name":"Real Estate Agent & Broker"},
        {"Name":"Information & Communication Technology (ICT)"},
        {"Name":"Textile and Clothing Manufacturing"},
        {"Name":"Financial Services and Insurance"},
        {"Name":"Manufacturing and Processing"},
        {"Name":"Building & Construction"},
        {"Name":"Betting"},
        {"Name":"Vocation Training"},
        {"Name":"Branding and Printing"},
        {"Name":"Manufacturing"},
        {"Name":"Electricity Generation Transmission & Distribution"},
        {"Name":"Mail and Courier Services"},
    ]
}