series = {
    "model": "Series",
    "data": [
        # HR naming series
        {"name":"Leave_Setup", "name_format":"{leave_type}", "series_count":0, "series_digits":4},
        {"name":"Payroll_Recovery", "name_format":"RCY - {employee_names} - {DATE} - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Payroll_Arrears", "name_format":"PAL-ARS - {employee_names} - {DATE} - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Payroll_Refunds", "name_format":"RE-FND - {employee_names} - {DATE} - {series_count}", "series_count":0, "series_digits":4},
        {"name":"With_Hold_Employee_Pay", "name_format":"WHE-PAY - {posting_date} - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Employee_Transfer_Memo", "name_format":"EMP-TSF-MEMO - {transfer_employee_name} - {DATE} - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Advance_And_Pension_Entries", "name_format":"SVG - {salary_component} - {DATE} - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Leave_Allocation", "name_format":"ALLOC - {DATE} - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Leave_Entry", "name_format":"LENT - {DATE} - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Training_Feedback", "name_format":"TRN-FDBK - {employee} - {training_program} - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Leave_Plan", "name_format":"LVE-PLN - {planner} - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Leave_Commutation", "name_format":"LVE-CMT - {fullname} - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Leave_Commutation_Memo", "name_format":"LVE-CMT-Memo - {fullname} - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Skill_Levy", "name_format":"Skill-Levy - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Employee_Welfare_Survey", "name_format":"EMP-FEEDBACK - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Interview_Rating", "name_format":"RATING -{evaluator}- {series_count}", "series_count":0, "series_digits":4},
        {"name":"Applicant_Short_List", "name_format":"APPLICANT -{applicant_first_name}-{applicant_last_name}- {series_count}", "series_count":0, "series_digits":4},
        {"name":"Applicant_Short_List", "name_format":"APPLICANT -{applicant_first_name}-{applicant_last_name}- {series_count}", "series_count":0, "series_digits":4},
        {"name":"Self_Appraisal", "name_format":"APPLICANT -{appraisee_name} - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Enabled_Bonding_Period", "name_format":"BP-{employee}-{series_count}", "series_count":0, "series_digits":4},

        {"name":"Employee", "name_format":"{first_name} {last_name} - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Appraisal_Setup", "name_format":"STP-{DATE}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Appraisal", "name_format":"APPR-{appraisee_name}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Appraise_Your_Self", "name_format":"SLF-RTI-{full_name}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Self_Appraisal_Setup", "name_format":"APPR-STP-{appraisee_name}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Performance_Agreement", "name_format":"PFAT-{employee_id}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Training_Event", "name_format":"TRF-{YEAR}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Employee_Disciplinary", "name_format":"DISC-{YEAR}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Work_Plan", "name_format":"WRKPLN-{YEAR}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Employee_Checkin", "name_format":"CHCK-{YEAR}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Employee_Promotion", "name_format":"PROM-{employee_name}-{DATE}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Leave_Application", "name_format":"APP-{YEAR}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Leave_Compensation", "name_format":"COPMP-{YEAR}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Leave_Policy", "name_format":"LP-{title}--{series_count}", "series_count":0, "series_digits":4},
        {"name":"Employee_File", "name_format":"{employee_name}-{DATE}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Job_Offer", "name_format":"OFFR-{YEAR}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Job_Application", "name_format":"JA-{applicant_first_name}-{job_advertisement}", "series_count":0, "series_digits":4},
        {"name":"Interview", "name_format":"INT-{short_listed_applicant}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Interview_Feedback", "name_format":"FEED-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Appointment_Letter", "name_format":"LETTR-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Payroll_Processor", "name_format":"PAYRL-{DATE}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"House_Loan_Application", "name_format":"HLA-{full_name}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Skills_Gap", "name_format":"{skill}-Gap-{full_name}-{series_count}", "series_count":0, "series_digits":4},

        {"name":"Payslip", "name_format":"SLIP-{employee}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Appraisal_Form", "name_format":"APPR-FRM-{appraisee_name}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Calender", "name_format":"{YEAR}", "series_count":0, "series_digits":4},
        {"name":"Employee_Seperation", "name_format":"EMP-SEP-{employee} {department}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Exit_Interview", "name_format":"EXT-INTW-{employee} {department}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Job_Advertisement", "name_format":"ADVERT-{designation}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Final_Statement", "name_format":"FNAL-STMT-{employee} {department}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Employee_Grievance", "name_format":"EMP-GRV-{employee_name}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Case_Outcome", "name_format":"CAS-OUT-{employee_disciplinary}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Result", "name_format":"OUTCOME-{training_event}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Training_Result", "name_format":"TRN-RST-{DATE}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Memo", "name_format":"MEMO-{subject}-{DATE}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Employee_Attendance", "name_format":"ATT-{employee_name}-{DATE}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Bonus", "name_format":"BONUS-{bonus_type}-{DATE}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Hr_Contract", "name_format":"Contract-With-{full_name} - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Recovery_Of_Medical_Bills", "name_format":"EMP-MDCL-- {series_count}", "series_count":0, "series_digits":4},
        {"name":"Staff_Feedback", "name_format":"EMP-FEEDBACK - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Transport_Request", "name_format":"TRASNPORT-REQ - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Long_Term_Sponsorship", "name_format":"LTS-APP - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Training_Plan", "name_format":"{plan_period}-Training Plan-{DATE}",},
        {"name":"HR_Budget", "name_format":"BUDGET - {from_date} - {to_date}- {series_count}", "series_count":0, "series_digits":4},
        {"name":"Training_Plan", "name_format":"{plan_period}-Training Plan-{DATE}",},
        {"name":"HR_Budget_Entries", "name_format":"BGT-ENT - {year} - {series_count}", "series_count":0, "series_digits":4},
        {"name":"DiscHR_Budgetiplinary_Statement_Form", "name_format":"{charge}-{role_in_charge_at_hand}-Statement-{series_count}", "series_count":0, "series_digits":4},
        {"name":"ECZ_Imprest", "name_format":"IMP-{initiator_first_name}-{initiator_last_name}-{request_date}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"ECZ_Imprest_Retirement", "name_format":"{imprest}-Retirement-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Petty_Cash", "name_format":"{request_date}-PC-{series_count}", "series_count":0, "series_digits":4},
        {"name":"ECZ_Petty_Cash", "name_format":"{request_date}-PC-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Graduate", "name_format":"{employee_name}-Gratuity-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Exit_Interview_Questionnair", "name_format":"Exit-Interview-{employee}", "series_count":0, "series_digits":0},
        {"name":"Skill_Gap", "name_format":"{skill}-Skill-Gap-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Clearance_Form", "name_format":"{employee_name}-Clearance", "series_count":0, "series_digits":0},
        {"name":"Charge_Form", "name_format":"Charge-{employee_name}", "series_count":1, "series_digits":4},
        {"name":"Graduate", "name_format":"{employee_name}-Gratuity-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Employee_Pay_And_Salary", "name_format":"{employee}-SALARY-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Verbal_Warning", "name_format":"VERBAL-WARNING-{warning_date}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Announcement", "name_format":"ANN-{name_doc}-{series_count}", "series_count":0, "series_digits":4},

        {"name":"Request_Task_Adjustment", "name_format":"REQ-TSK-ADJ-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Request_For_Council_Car", "name_format":"Vehicle-Request-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Sitting_Allowance", "name_format":"Sitting-Allowance-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Graduate_Development_Enrollment", "name_format":"GDE-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Certificate_Of_Service", "name_format":"Certificate-Of-Service-{series_count}", "series_count":0, "series_digits":4},
        {"name":"CS_Seasonal_Employment", "name_format":"CS-Seasonal-Employment-{series_count}", "series_count":0, "series_digits":4},
        {"name":"ID_Card", "name_format":"ID-Card-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Express_Mail", "name_format":"Express-Mail-Request-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Caveat_Agreement", "name_format":"Caveat-Agreement-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Oath_Affirmation", "name_format":"Oath-Affirmation-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Witnessing", "name_format":"WND-{document_type}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Tuition_Advance_For_Salary_Form", "name_format":"TAS-APP-{series_count}", "series_count":0, "series_digits":4},

        {"name":"Staff_Requisition", "name_format":"SRF-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Leave_Schedule", "name_format":"LVE-SHL-{department}-{series_count}", "series_count":0, "series_digits":4},


        # PAYROLL 
        {"name":"Pay_For_Temps_Or_Seasonal_Employee", "name_format":"TMP-EMP-PAY- {DATE} - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Advance_Application", "name_format":"SLY-ADCE-{employee_id} {advance_type} -- {series_count}", "series_count":0, "series_digits":4},
        {"name":"Second_Salary_Advance_Application", "name_format":"SLY-ADCE-{employee_id} {advance_type} -- {series_count}", "series_count":0, "series_digits":4},
        {"name":"Overtime", "name_format":"OVTM - {DATE} - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Salary_Advance_Entries", "name_format":"ADV-ENT- {applicant} - {DATE} - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Professional_Membership_Subscription", "name_format":"MSP-{fullname} - {series_count}", "series_count":0, "series_digits":4},
        {"name":"Welfare_Entries", "name_format":"WFE- {series_count}", "series_count":0, "series_digits":4},
        {"name":"Advance_Memo", "name_format":"ADVC-MEMO-{DATE}-{series_count}","series_count":3, "series_digits":4},
        {"name":"Payroll_Activity_Entry", "name_format":"PYR-ACT-ENT-{DATE}-{series_count}","series_count":3, "series_digits":4},
        {"name":"Long_Term_Sponsorship_Fund_Request", "name_format":"LTS-REQ-FUD-{DATE}-{series_count}","series_count":3, "series_digits":4},
        {"name":"Personal_Loan_Application", "name_format":"PL-{series_count}","series_count":3, "series_digits":4},
        {"name":"Cash_Repayment", "name_format":"CR-{repayment_reference}-{series_count}","series_count":3, "series_digits":4},

        # CORE
        {"name":"Data_Importation", "name_format":"{model}-{DATE}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Rating", "name_format":"{model}-{YEAR}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Shareholder", "name_format":"{first_name} {last_name}", "series_count":0, "series_digits":4},
        {"name":"Share", "name_format":"{share_type}", "series_count":0, "series_digits":4},
        {"name":"Auth_Trail", "name_format":"{first_name} {last_name}-{DATE}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"License", "name_format":"0183550ERP001{series_count}", "series_count":0, "series_digits":6},
        
        # CONTROLLER
        {"name":"Subscription", "name_format":"{tenant}-{subscription_from}-{subscription_to}-{series_count}", "series_count":0, "series_digits":4},

        {"name":"Imprest_Form_20_A", "name_format":"IMP-{series_count}","series_count":3, "series_digits":4},
        {"name":"Imprest_Form_20_B", "name_format":"IMP-{series_count}","series_count":3, "series_digits":4},
        {"name":"Imprest_Form_20_C", "name_format":"IMP-{series_count}","series_count":3, "series_digits":4},
        {"name":"Expense_Retirement", "name_format":"RET-{series_count}","series_count":3, "series_digits":4},
        {"name":"Interview_Schedule", "name_format":"IS-{series_count}","series_count":3, "series_digits":4},
        {"name":"Overtime_CLaim", "name_format":"OT-CLM-{DATE}-{series_count}","series_count":3, "series_digits":4},
        {"name":"Staffs_To_Work_This_Overtime", "name_format":"STF-ON-OT-{DATE}-{series_count}","series_count":3, "series_digits":4},
        {"name":"Certificate_of_Service_Temporal_Employee", "name_format":"CRT-OF-SER-{DATE}-{series_count}","series_count":3, "series_digits":4},

        # PORTAL
        {"name":"OTP", "name_format":"OTP-{DATE}", "series_count":0, "series_digits":4},
        {"name":"Disciplinary_Statement_Form", "name_format":"{employee_name}-{employee_name}-Statement", "series_count":0, "series_digits":4},
        {"name":"Sitting_Summary", "name_format":"{sitting_type}-{Date}-{series_count}", "series_count":0, "series_digits":4},

        {"name":"Pre_Payroll_payment", "name_format":"{DATE}-Pre-Payment-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Acting_Appointment_Memo", "name_format":"{acting_officer_name}-AS-{job_title}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Acting_Appointment", "name_format":"{acting_officer_name}-AS-{job_title}-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Salary_Increment", "name_format":"Salary_Increment-{series_count}", "series_count":0, "series_digits":4},
        {"name":"Appeal", "name_format":"{for_type}-Appeal-{series_count}", "series_count":0, "series_digits":4},
    ]
}