from django.urls import path, include
from . import views

urlpatterns = [
   path ('', include ('client_app.payroll.payroll_dashboard.urls')),
   path ('payroll_setup', include ('client_app.payroll.payroll_setup.urls')),
   path ('payroll_dashboard', include ('client_app.payroll.payroll_dashboard.urls')),
   path ('payroll_processor/', include ('client_app.payroll.payroll_processor.urls')),
   path ('payslip/', include ('client_app.payroll.payslip.urls')),
   path ('income_tax_band/', include ('client_app.payroll.income_tax_band.urls')),
   path ('salary_component/', include ('client_app.payroll.salary_component.urls')),
   path ('employee_grade/', include ('client_app.payroll.employee_grade.urls')),
   path ('advance_application/', include ('client_app.payroll.advance_application.urls')),
   path ('advance_setup/', include ('client_app.payroll.advance_setup.urls')),
   path ('advance_balance/', include ('client_app.payroll.advance_balance.urls')),
   path ('deduction_register/', include ('client_app.payroll.deduction_register.urls')),
   path ('payroll_reports/', include ('client_app.payroll.payroll_reports.urls')),
   path ('overtime/', include ('client_app.payroll.overtime.urls')),
   path ('professional_membership', include ("client_app.payroll.professional_membership.urls")),
   path ('overtime_setup/', include ('client_app.payroll.overtime_setup.urls')),
   path ('commission_setup/', include('client_app.payroll.commission_setup.urls')),
   path ('commission/', include('client_app.payroll.commission_setup.urls')),
   path ('payroll_loans_dashboard/', include ('client_app.payroll.payroll_loans_dashboard.urls')),
   path ('overtime_claim', include ("client_app.payroll.overtime_claim.urls")),
   path ('house_loan_application/', include ('client_app.payroll.house_loan_application.urls')), 
   path ('house_loan_agreement/', include ('client_app.payroll.house_loan_agreement.urls')), 
   path ('petty_cash/', include ('client_app.payroll.petty_cash.urls')),
   path ('imprest_a/', include ("client_app.payroll.imprest_a.urls")),
   path ('imprest_b/', include ('client_app.payroll.imprest_b.urls')), 
   path ('imprest_c/', include ('client_app.payroll.imprest_c.urls')), 
   path ('staff_expense_retirement/', include ('client_app.payroll.staff_expense_retirement.urls')),
   path ('application_for_a_personal/', include ('client_app.payroll.application_for_a_personal.urls')), 
   path ('cash_repayment/', include ('client_app.payroll.cash_repayment.urls')),  
   path ("allowance_and_benefit/", include("client_app.payroll.allowance_and_benefit.urls")),
   path ('pre_payroll_payment', include('client_app.payroll.pre_payroll_payment.urls')),
   path ("recoveries/", include("client_app.payroll.recoveries.urls")),
   path ("refunds/", include("client_app.payroll.refunds.urls")),
   path ("pay_temp/", include("client_app.payroll.pay_temp.urls")),
   path ("banking/", include("client_app.payroll.banking.urls")),
   path ("with_hold_pay/", include("client_app.payroll.with_hold_pay.urls")),
   path ("arrears/", include("client_app.payroll.arrears.urls")),
]
